Improve unpack tar balls error handling
This is not a complete fix for error handling by any means, but it does
mean we will detect more errors with symlinks in TO-UNPACK, and clean
up better on some of the error conditions.

We have improved the "find" commands used to fetch all the data about
the tar balls to be processed so that we don't have to use the "du"
command, and we still process all the symlinks, including the bad ones.

We have added a unit test which exercises all the functional code
paths of the pbench-unpack-tarballs code.  It does not yet come close
to getting coverage of all the minor error paths.

We have made changes to those error paths so that we can tell a bit
more about what result tar ball had those errors.

We now unpack the tar ball to a special unpack directory so that we
can be sure the top level of the tar ball only has the result name, and
ignore any other data, with the ignored data counted as a warning.

We have made the first argument optional.

If the incoming directory is the same as the unpack path we were given
in the first argument, we now set the link destination to MOVED-UNPACKED
instead of UNPACKED.

Lastly, if a result tar ball has already been unpacked into the incoming
directory (either the temporary or the real one), we now error out so
that we can track that error condition.

diff --git a/server/pbench/bin/pbench-unpack-tarballs b/server/pbench/bin/pbench-unpack-tarballs
--- a/server/pbench/bin/pbench-unpack-tarballs
+++ b/server/pbench/bin/pbench-unpack-tarballs
@@ -51,8 +51,9 @@ case $opts in
         ;;
 esac
 
+# Optional argument for the unpack path to use that could be different
+# than the incoming directory.
 UNPACK_PATH=$1
-#mkdir -p $UNPACK_PATH
 
 # TOP, ARCHIVE, INCOMING, RESULTS, USERS are all defined by the base file
 . $dir/pbench-base.sh
@@ -64,6 +65,12 @@ log_init $(basename $0) $LOGSDIR/$(basename $0)
 test -d $ARCHIVE || doexit "Bad ARCHIVE=$ARCHIVE"
 test -d $INCOMING || doexit "Bad INCOMING=$INCOMING"
 test -d $RESULTS || doexit "Bad RESULTS=$RESULTS"
+test -d $USERS || doexit "Bad USERS=$USERS"
+if [ -z "$UNPACK_PATH" ]; then
+    UNPACK_PATH="$INCOMING"
+else
+    test -d $UNPACK_PATH || doexit "Bad UNPACK_PATH=$UNPACK_PATH"
+fi
 
 # make sure only one copy is running.
 # Use 'flock -n $LOCKFILE /home/pbench/bin/pbench-unpack-tarballs' in the
@@ -72,34 +79,49 @@ test -d $RESULTS || doexit "Bad RESULTS=$RESULTS"
 
 # the link source and destination for this script
 linksrc=TO-UNPACK
-linkdest=UNPACKED
+if [ "$INCOMING" = "$UNPACK_PATH" ]; then
+    linkdest=MOVED-UNPACKED
+else
+    linkdest=UNPACKED
+fi
+
 echo $TS
-
 tmp=$TMP/$PROG.$$
-
 trap 'rm -rf $tmp' EXIT INT QUIT
 
 mkdir -p $tmp
 
-# accumulate errors in a file for mailing at end
+# Accumulate errors and logs in files for reporting at the end.
 mail_content=$tmp/mail_content.log
 index_content=$tmp/index_mail_contents
 
 # get the list of files we'll be operating on - sort them by size
 list=$tmp/$PROG.list
 
-# find command will not generate any result if the linksrc is empty,
-# and because of that, du will not get any result to calculate the
-# size. In that scenario, du generates the size of the current
-# directory as output; to handle that exclude the current directory.
-find $ARCHIVE/*/$linksrc -type l -name '*.tar.xz' -printf "%l\n" 2>/dev/null | grep -v DUPLICATE | xargs du -b --exclude "." 2>/dev/null | sort -n > $list
+# Find all the links in all the $ARCHIVE/<controller>/$linksrc
+# directories, emitting a list of their full paths with the size
+# in bytes of the file the link points to, and then sort them so
+# that we process the smallest tar balls first.
+> ${list}.unsorted
+# First we find all the $linksrc directories
+for linksrc_dir in $(find $ARCHIVE/ -maxdepth 2 -name $linksrc); do
+    # Find all the links in a given $linksrc directory that are
+    # links to actual files (bad links are not emitted!).
+    find -L $linksrc_dir -type f -name '*.tar.xz' -printf "%s %p\n" 2>/dev/null >> ${list}.unsorted
+    # Find all the links in the same $linksrc directory that don't
+    # link to anything so that we can count them as errors below. 
+    find -L $linksrc_dir -type l -name '*.tar.xz' -printf "%s %p\n" 2>/dev/null >> ${list}.unsorted
+done
+sort -n ${list}.unsorted > ${list}
+rm -f ${list}.unsorted
 
 typeset -i ntb=0
 typeset -i ntotal=0
 typeset -i nerrs=0
 typeset -i ndups=0
+typeset -i nwarn=0
 
-# Initialize mail content
+# Initialize report content
 > $mail_content
 > $index_content
 
@@ -107,83 +129,121 @@ while read size result ;do
     ntotal=$ntotal+1
 
     link=$(readlink -e $result)
-    if [ ! -f "$link" ] ;then
-        echo "$TS: $link does not exist" | tee -a $mail_content >&4
+    if [ -z "$link" ] ;then
+        echo "$TS: symlink target for $result does not exist" | tee -a $mail_content >&4
         nerrs=$nerrs+1
+        # FIXME: quarantine $result
         continue
     fi
     resultname=$(basename $result)
     resultname=${resultname%.tar.xz}
-    hostname=$(basename $(dirname $link))
 
-    # echo "Link=$link"
-    # echo "Resultname=$resultname"
-    # echo "Hostname=$hostname"
-    # continue
+    # XXXX - for now, if it's a duplicate name, just punt and avoid
+    # producing the error
+    if [ ${resultname%%.*} == "DUPLICATE__NAME" ] ;then
+        ndups=$ndups+1
+        # FIXME: quarantine $result
+        continue
+    fi
+
+    basedir=$(dirname $link)
+    hostname=$(basename $basedir)
 
     # make sure that all the relevant state directories exist
     mk_dirs $hostname
     # ... and a couple of other necessities.
     if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $hostname processing directories failed: code $status" | tee -a $mail_content >&4
+        echo "$TS: Creation of $hostname processing directories failed for $result: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
+        # FIXME: quarantine $result
         continue
     fi
     mkdir -p $INCOMING/$hostname
     if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $INCOMING/$hostname failed: code $status" | tee -a $mail_content >&4
+        echo "$TS: Creation of $INCOMING/$hostname failed for $result: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
+        # FIXME: quarantine $result
+        continue
+    fi
+    incoming=$INCOMING/$hostname/$resultname
+    if [ -e $incoming ]; then
+        echo "$TS: Incoming result, $INCOMING/$hostname/$resultname/, already exists, skipping $result" | tee -a $mail_content >&4
+        nerrs=$nerrs+1
+        # FIXME: quarantine $result
         continue
     fi
 
     mkdir -p $UNPACK_PATH/$hostname
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: mkdir -p $UNPACK_PATH/$hostname failed: code $status" | tee -a $mail_content >&4
+        echo "$TS: mkdir -p $UNPACK_PATH/$hostname failed for $result: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
+        # FIXME: quarantine $result
+        continue
+    fi
+    if [ -e $UNPACK_PATH/$hostname/${resultname} ]; then
+        echo "$TS: $UNPACK_PATH/$hostname/${resultname} already exists for $result" | tee -a $mail_content >&4
+        nerrs=$nerrs+1
+        # FIXME: quarantine $result
         continue
     fi
 
-    # XXXX - for now, if it's a duplicate name, just punt and avoid producing the error - the full
-    # solution will involve renaming the unpacked directory appropriately.
-    if [ ${resultname%%.*} == "DUPLICATE__NAME" ] ;then
-        ndups=$ndups+1
+    mkdir $UNPACK_PATH/$hostname/${resultname}.unpack
+    status=$?
+    if [[ $status -ne 0 ]] ;then
+        echo "$TS: 'mkdir ${resultname}.unpack' failed for $result: code $status" | tee -a $mail_content >&4
+        nerrs=$nerrs+1
+        # FIXME: quarantine $result
+        popd > /dev/null 2>&1
         continue
     fi
-
-    let start_time=$(date +%s)
-    pushd $UNPACK_PATH/$hostname > /dev/null 2>&1
-    tar --extract --no-same-owner --no-overwrite-dir --touch --file="$result"
+    let start_time=$(timestamp-seconds-since-epoch)
+    tar --extract --no-same-owner --touch --delay-directory-restore --file="$result" --force-local --directory="$UNPACK_PATH/$hostname/${resultname}.unpack"
     status=$?
     if [[ $status -ne 0 ]] ;then
         echo "$TS: 'tar -xf $result' failed: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
-        popd > /dev/null 2>&1
+        # FIXME: quarantine $result
         continue
+    fi
+    mv $UNPACK_PATH/$hostname/${resultname}.unpack/${resultname} $UNPACK_PATH/$hostname/${resultname}
+    status=$?
+    if [[ $status -ne 0 ]] ;then
+        echo "$TS: '$result' does not contain ${resultname} directory at the top level; skipping" | tee -a $mail_content >&4
+        rm -rf $UNPACK_PATH/$hostname/${resultname}.unpack
+        nerrs=$nerrs+1
+        # FIXME: quarantine $result
+        continue
+    fi
+    rmdir $UNPACK_PATH/$hostname/${resultname}.unpack
+    status=$?
+    if [[ $status -ne 0 ]] ;then
+        echo "$TS: WARNING - '$result' should only contain the ${resultname} directory at the top level, ignoring other content" | tee -a $mail_content >&4
+        rm -rf $UNPACK_PATH/$hostname/${resultname}.unpack
+        nwarn=$nwarn+1
     fi
 
     # chmod directories to at least 555
-    find . -type d -print0 | xargs -0 chmod ugo+rx
+    find $UNPACK_PATH/$hostname/${resultname} -type d -print0 | xargs -0 chmod ugo+rx
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: 'chmod ugo+rx' of subdirs failed: code $status" | tee -a $mail_content >&4
+        echo "$TS: 'chmod ugo+rx' of subdirs $resultname for $result failed: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
-        rm -rf $resultname
-        popd > /dev/null 2>&1
+        rm -rf $UNPACK_PATH/$hostname/$resultname
+        # FIXME: quarantine $result
         continue
     fi
 
     # chmod files to at least 444
-    chmod -R ugo+r .
+    chmod -R ugo+r $UNPACK_PATH/$hostname/$resultname
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: 'chmod -R ugo+r .' failed: code $status" | tee -a $mail_content >&4
+        echo "$TS: 'chmod -R ugo+r $resultname' for $result failed: code $status" | tee -a $mail_content >&4
         nerrs=$nerrs+1
-        rm -rf $resultname
-        popd > /dev/null 2>&1
+        rm -rf $UNPACK_PATH/$hostname/$resultname
+        # FIXME: quarantine $result
         continue
     fi
-    popd > /dev/null 2>&1
 
     # Version 002 agents use the metadata log to store a prefix.
     # They may also store a user option in the metadata log.
@@ -192,12 +252,9 @@ while read size result ;do
     prefix=$(getconf.py -C $UNPACK_PATH/$hostname/$resultname/metadata.log prefix run)
     user=$(getconf.py -C $UNPACK_PATH/$hostname/$resultname/metadata.log user run)
 
-    # Version 001 agents use a prefix file
-    # If there is a prefix file, create a link as specified by the
-    # prefix.  Even if no prefix is specified, we still want to link
-    # from the results/ hierarchy to incoming/.
-    basedir=$(dirname $link)
-    # pbench-dispatch has already moved it to the .prefix subdir
+    # Version 001 agents use a prefix file.  If there is a prefix file,
+    # create a link as specified in the prefix file.  pbench-dispatch
+    # has already moved it to the .prefix subdir
     prefixfile=$basedir/.prefix/$resultname.prefix
     if [ -f $prefixfile ] ;then
         # add the slash to make both cases uniform in what follows
@@ -209,11 +266,12 @@ while read size result ;do
         prefix=${prefix}/
     fi
 
-    incoming=$INCOMING/$hostname/$resultname
     mkdir -p $RESULTS/$hostname/$prefix
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: code $status: mkdir -p $RESULTS/$hostname/$prefix" | tee -a $mail_content >&4
+        echo "$TS: mkdir -p $RESULTS/$hostname/$prefix for $result failed: code $status" | tee -a $mail_content >&4
+        nerrs=$nerrs+1
+        rm -rf $UNPACK_PATH/$hostname/$resultname
         continue
     else
         # when unpack path is incoming
@@ -225,8 +283,9 @@ while read size result ;do
             ln -s $UNPACK_PATH/$hostname/$resultname $incoming
             status=$?
             if [[ $status -ne 0 ]] ;then
-                echo "$TS: code $status: ln -s $UNPACK_PATH/$hostname/$resultname $incoming" | tee -a $mail_content >&4
-                # Cleanup needed here but trap takes care of it.
+                echo "$TS: ln -s $UNPACK_PATH/$hostname/$resultname $incoming for $result failed: code $status" | tee -a $mail_content >&4
+                nerrs=$nerrs+1
+                rm -rf $UNPACK_PATH/$hostname/$resultname
                 continue
             fi
         fi
@@ -235,20 +294,24 @@ while read size result ;do
         ln -s $incoming $RESULTS/$hostname/$prefix$resultname
         status=$?
         if [[ $status -ne 0 ]] ;then
-            echo "$TS: code $status: ln -s $incoming $RESULTS/$hostname/$prefix$resultname" | tee -a $mail_content >&4
+            echo "$TS: ln -s $incoming $RESULTS/$hostname/$prefix$resultname for $result failed: code $status" | tee -a $mail_content >&4
+            nerrs=$nerrs+1
             rm -rf $incoming
+            rm -rf $UNPACK_PATH/$hostname/$resultname
             continue
         fi
 
         if [ ! -z ${user} ] ;then
             # make a link in users/ but first make sure the directory exists
-            mkdir -p $USERS/${user}/${hostname}/${prefix}
+            mkdir -p ${USERS}/${user}/${hostname}/${prefix}
             echo "ln -s ${incoming} $USERS/${user}/${hostname}/${prefix}${resultname}"
             ln -s ${incoming} $USERS/${user}/${hostname}/${prefix}${resultname}
             status=$?
             if [[ $status -ne 0 ]] ;then
-                echo "$TS: code $status: ln -s ${incoming} $USERS/${user}/$hostname/$prefix$resultname" | tee -a $mail_content >&4
+                echo "$TS: code $status: ln -s ${incoming} $USERS/${user}/${hostname}/${prefix}${resultname}" | tee -a $mail_content >&4
                 rm -rf ${incoming}
+                rm -rf ${UNPACK_PATH}/${hostname}/${resultname}
+                rm -rf ${RESULTS}/${hostname}/${prefix}${resultname}
                 continue
             fi
         fi
@@ -257,15 +320,16 @@ while read size result ;do
     mv $ARCHIVE/$hostname/$linksrc/$resultname.tar.xz $ARCHIVE/$hostname/$linkdest/$resultname.tar.xz
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot move $ARCHIVE/$hostname/$resultname from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4
+        echo "$TS: Cannot move symlink to $ARCHIVE/$hostname/$resultname.tar.xz from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4
         # Cleanup needed here but trap takes care of it.
         rm -rf $incoming
+        rm -rf ${UNPACK_PATH}/${hostname}/${resultname}
         rm $RESULTS/$hostname/$prefix$resultname
         nerrs=$nerrs+1
         continue
     fi
 
-    let end_time=$(date +%s)
+    let end_time=$(timestamp-seconds-since-epoch)
     let duration=end_time-start_time
     # log the success
     echo "$TS: $hostname/$resultname: success - elapsed time (secs): $duration - size (bytes): $size"
@@ -280,7 +344,7 @@ if [[ $nerrs -gt 0 ]]; then
     subj="$PROG.$TS($PBENCH_ENV) - w/ $nerrs errors"
     cat << EOF > $index_content
 $subj
-Processed $ntotal result tar balls, $ntb successfully, with $nerrs errors and $ndups duplicates
+Processed $ntotal result tar balls, $ntb successfully, $nwarn warnings, $nerrs errors, and $ndups duplicates
 
 EOF
     cat $mail_content >> $index_content
