Ensure PATH has the pbench server bin dir in it
We need to ensure that the PATH variable has the proper bin directory in
its list for the pbench server code.  We don't need to do this in the
unit test environment, though.

We also use $PROG instead of $(basename $0), fixing up places where exit
is called before log_finish, adding log_exit to assist.

diff --git a/server/pbench/bin/pbench-sync-satellite b/server/pbench/bin/pbench-sync-satellite
--- a/server/pbench/bin/pbench-sync-satellite
+++ b/server/pbench/bin/pbench-sync-satellite
@@ -44,6 +44,8 @@ shift 3
 # TOP, TMP, LOGSDIR, ARCHIVE, TS are all defined in pbench-base.sh
 . $dir/pbench-base.sh
 
+test -d $ARCHIVE || doexit "Bad ARCHIVE=$ARCHIVE"
+
 # check if we are running under the unit test regime
 if [ "${_PBENCH_SERVER_TEST}" = "1" ] ;then
     # make the names reproducible for unit tests
@@ -85,33 +87,28 @@ typeset -i nprocessed=0
 typeset -i nfailed_md5=0
 typeset -i nerrs=0
 
-unpack=$tmp/unpack.$prefix
-trap "rm -rf $tmp" EXIT QUIT INT
+# remove the tmp dir on exit; try to remove an empty $logdir
+# but suppress any complaints.
+trap "rm -rf $tmp; rmdir $logdir 2>/dev/null" EXIT QUIT INT
 
-mkdir -p $tmp
-mkdir -p $unpack
+unpack=$tmp/unpack.$prefix
+mkdir -p $unpack || doexit "Failed to create $unpack"
 
 # accumulate errors in a file for mailing at end
 mail_content=$tmp/mail.log
 index_content=$tmp/index_mail_contents
 
-log_init $(basename $0) $LOGSDIR/$(basename $0)
-logdir=$LOGSDIR/$(basename $0)/$prefix/$TS
-# remove the tmp dir on exit; try to remove an empty $logdir
-# but suppress any complaints.
-trap "rm -rf $tmp; rmdir $logdir 2>/dev/null" EXIT QUIT INT
-mkdir -p $logdir
-rc=$?
-if [[ $rc != 0 ]] ;then
-    echo Failed: mkdir -p $logdir >&4
-    exit 2
-fi
+logdir=$LOGSDIR/$PROG/$prefix/$TS
+mkdir -p $logdir || "Failed to create $logdir"
+
+log_init $PROG
 
 # get the tarball from remote
 ssh $remotehost "/opt/pbench-server/bin/pbench-sync-package-tarballs" > $tmp/satellite.$prefix.tar
 rc=$?
 if [[ $rc != 0 ]] ;then
     echo "$PROG: ssh $remotehost /opt/pbench-server/bin/pbench-sync-package-tarballs: failed." >&4
+    log_finish
     exit 2
 fi
 
@@ -133,12 +130,22 @@ for host in $hosts ;do
     typeset -i failed_md5=0
     localdir=$ARCHIVE/$prefix::$host
 
-    if [ ! -d $localdir ] ;then
-        mkdir -p $localdir || exit 1
+    pushd $localdir >/dev/null
+    rc=$?
+    if [ $rc -ne 0 ]; then
+        mkdir -p $localdir
+        rc=$?
+        if [ $rc -ne 0 ]; then
+            echo "$PROG: failed to create remote controller in archive, $localdir" >&4
+            continue
+        fi
     fi
-    pushd $localdir >/dev/null || exit 2
-    if [ ! -d $logdir/$host ] ;then
-        mkdir -p $logdir/$host
+
+    mkdir -p $logdir/$host
+    rc=$?
+    if [ $rc -ne 0 ]; then
+        echo "$PROG: failed to create $logdir/$host" >&4
+        continue
     fi
 
     # get the tarball list for this host
