Update the script to unpack tarballs and create symlinks for them
This is a new unpack script which will decide the unpacking directory
according to the path it gets as a parameter. If this is script is
running in any other server other than production, it will unpack in
the tmp directory (considering that the path given in parameter is tmp)
and create a symlink of the content in the incoming as well as in the
results directory.

diff --git a/server/pbench/bin/pbench-unpack-tarballs b/server/pbench/bin/pbench-unpack-tarballs
--- a/server/pbench/bin/pbench-unpack-tarballs
+++ b/server/pbench/bin/pbench-unpack-tarballs
@@ -51,6 +51,9 @@ case $opts in
         ;;
 esac
 
+UNPACK_PATH=$1
+#mkdir -p $UNPACK_PATH
+
 # TOP, ARCHIVE, INCOMING, RESULTS are all defined by the base file
 . $dir/pbench-base.sh
 ###########################################################################
@@ -68,16 +71,16 @@ test -d $RESULTS || doexit "Bad RESULTS=$RESULTS"
 # does not use any locking.
 
 # the link source and destination for this script
-linksrc=TODO
-linkdest=TO-COPY-SOS
-
+linksrc=TO-UNPACK
+linkdest=UNPACKED
 echo $TS
 
 # get the list of files we'll be operating on - sort them by size
-list=$TMP/pbench-unpack-tarballs.$$
-find -L $ARCHIVE/*/$linksrc -name '*.tar.xz' -printf "%s\t%p\n" 2>/dev/null | grep -v DUPLICATE | sort -n > $list
+list=$UNPACK_PATH/pbench-unpack-tarballs.$$
+mail_content=$UNPACK_PATH/mail_content.log
+find $ARCHIVE/*/$linksrc -name '*.tar.xz' -printf "%s\t%p\n" 2>/dev/null | grep -v DUPLICATE | sed 's/\/'$linksrc'//' | sort -n > $list
 
-trap 'rm -f $list' EXIT INT QUIT
+trap 'rm -f $list $mail_content' EXIT INT QUIT
 
 typeset -i ntb=0
 typeset -i ntotal=0
@@ -89,39 +92,38 @@ while read size result ;do
 
     link=$(readlink -e $result)
     if [ ! -f "$link" ] ;then
-        echo "$TS: $link does not exist" >&4
+        echo "$TS: $link does not exist" >&4 | tee -a $mail_content
         nerrs=$nerrs+1
         continue
     fi
-
     resultname=$(basename $result)
     resultname=${resultname%.tar.xz}
     hostname=$(basename $(dirname $link))
 
-    # echo $link
-    # echo $resultname
-    # echo $hostname
+    # echo "Link=$link"
+    # echo "Resultname=$resultname"
+    # echo "Hostname=$hostname"
     # continue
 
     # make sure that all the relevant state directories exist
     mk_dirs $hostname
     # ... and a couple of other necessities.
     if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $hostname processing directories failed: code $status" >&4
+        echo "$TS: Creation of $hostname processing directories failed: code $status" >&4 | tee -a $mail_content
         nerrs=$nerrs+1
         continue
     fi
     mkdir -p $INCOMING/$hostname
     if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $INCOMING/$hostname failed: code $status" >&4
+        echo "$TS: Creation of $INCOMING/$hostname failed: code $status" >&4 | tee -a $mail_content
         nerrs=$nerrs+1
         continue
     fi
     
-    mkdir -p $TMP/$PROG/$hostname
+    mkdir -p $UNPACK_PATH/$hostname
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: mkdir -p $TMP/$PROG/$hostname failed: code $status" >&4
+        echo "$TS: mkdir -p $UNPACK_PATH/$hostname failed: code $status" >&4 | tee -a $mail_content
         nerrs=$nerrs+1
         continue
     fi
@@ -132,131 +134,141 @@ while read size result ;do
         ndups=$ndups+1
         continue
     fi
-
-    # create a "Please wait" message in .../incoming.
-    incoming=$INCOMING/$hostname/$resultname
-    mkdir -p $incoming
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: mkdir -p $incoming failed: code $status" >&4
-        nerrs=$nerrs+1
-        continue
-    fi
-    echo "Processing - please wait..." > $incoming/index.html
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: Creation of $incoming/index.html failed: code $status" >&4
-        nerrs=$nerrs+1
-        continue
-    fi
-
-    # check the md5 sum
-    md5=$(cat $link.md5 2> /dev/null | cut -d' ' -f1)
-    md5tar=$(md5sum $link 2> /dev/null | cut -d' ' -f1)
-    if [ "$md5" != "$md5tar" ] ;then
-        echo "$TS: MD5 check failed on $link" >&4
-        # move the link so that the script does not report the error continuously
-        mv $result $(echo $result | sed 's/TODO/BAD-MD5/')
-        nerrs=$nerrs+1
-        continue
-    fi
-
+    
     let start_time=$(date +%s)
-    # unpack the tarball into a temp area
-    pushd $TMP/$PROG/$hostname > /dev/null 2>&1
-    tar --extract --no-same-owner --no-overwrite-dir --touch --file="$result"
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: 'tar -xf $result' failed: code $status" >&4
-        nerrs=$nerrs+1
-        popd > /dev/null 2>&1
-        continue
-    fi
-    # chmod directories to at least 555
-    find . -type d -print0 | xargs -0 chmod ugo+rx
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: 'chmod ugo+rx' of subdirs failed: code $status" >&4
-        nerrs=$nerrs+1
-        popd > /dev/null 2>&1
-        continue
-    fi
-    # chmod files to at least 444
-    chmod -R ugo+r .
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: 'chmod -R ugo+r .' failed: code $status" >&4
-        nerrs=$nerrs+1
-        popd > /dev/null 2>&1
-        continue
-    fi
-    popd > /dev/null 2>&1
-
-    # move the tarball contents to INCOMING
-    rm $incoming/index.html
-    rmdir $incoming
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot remove $incoming: dir not empty? name collision? code $status" >&4
-        nerrs=$nerrs+1
-        continue
-    fi
-
-    # create the link from results to incoming *before* moving the directory from TMP.
-    # That avoids a race with pbench-create-results-links which might create a recursive link
-
-    # if there is a prefix file, create a link as specified by the prefix
-    # even if no prefix is specified, we still want to link from the results/ hierarchy to incoming/.
-    # user access will eventually be through results/ only.
-    basedir=$(dirname $link)
-    prefixfile=$basedir/prefix.$resultname
-    if [ -f $prefixfile ] ;then
-        # add the slash to make both cases uniform in what follows
-        prefix=$(cat $prefixfile)/
-        mkdir -p $basedir/.prefix
-        mv $prefixfile $basedir/.prefix
-    else
-        prefix=""
-    fi
-
-    mkdir -p $RESULTS/$hostname/$prefix
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: prefix failure - code $status:         mkdir -p $RESULTS/$hostname/$prefix" >&4
-    else
-        echo "ln -s $incoming $RESULTS/$hostname/$prefix$resultname"
-        ln -s $incoming $RESULTS/$hostname/$prefix$resultname
+    if [[ $UNPACK_PATH -ef $INCOMING ]] ;then
+        # unpack the tarballs in incoming
+        pushd $INCOMING/$hostname > /dev/null 2>&1
+        tar --extract --no-same-owner --no-overwrite-dir --touch --file="$result"
         status=$?
         if [[ $status -ne 0 ]] ;then
-            echo "$TS: prefix failure - code $status: ln -s $incoming $RESULTS/$hostname/$prefix$resultname" >&4
+            echo "$TS: 'tar -xf $result' failed: code $status" >&4 | tee -a $mail_content
+            nerrs=$nerrs+1
+            popd > /dev/null 2>&1
+            continue
         fi
-    fi
+        popd > /dev/null 2>&1
 
-    # now move the directory - remove the link on failure
-    # -Z needed for proper selinux labeling, but it works when selinux is disabled as well.
-    mv -Z $TMP/$PROG/$hostname/$resultname $incoming
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot move $TMP/$PROG/$hostname/$resultname to $incoming: code $status" >&4
-        rm $RESULTS/$hostname/$prefix$resultname
-        nerrs=$nerrs+1
-        continue
-    fi
+	basedir=$(dirname $link)
+        prefixfile=$basedir/prefix.$resultname
+        if [ -f $prefixfile ] ;then
+            # add the slash to make both cases uniform in what follows
+            prefix=$(cat $prefixfile)/
+            mkdir -p $basedir/.prefix
+            mv $prefixfile $basedir/.prefix
+        else
+            prefix=""
+        fi
 
-    # move the link to $linkdest directory
-    mv $result $(echo $result | sed "s/$linksrc/$linkdest/")
-    status=$?
-    if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot move $result link from $linksrc to $linkdest: code $status" >&4
-        rm $RESULTS/$hostname/$prefix$resultname
-        nerrs=$nerrs+1
-        continue
+	incoming=$INCOMING/$hostname/$resultname
+	mkdir -p $RESULTS/$hostname/$prefix
+        status=$?
+        if [[ $status -ne 0 ]] ;then
+            echo "$TS: code $status: mkdir -p $RESULTS/$hostname/$prefix" >&4 | tee -a $mail_content
+        else
+            echo "ln -s $incoming $RESULTS/$hostname/$prefix$resultname"
+            ln -s $incoming $RESULTS/$hostname/$prefix$resultname
+            status=$?
+            if [[ $status -ne 0 ]] ;then
+                echo "$TS: code $status: ln -s $incoming $RESULTS/$hostname/$prefix$resultname" >&4 | tee -a $mail_content
+            fi
+        fi
+
+        # move the link to $linkdest directory
+        mv $ARCHIVE/$hostname/$linksrc/$resultname.tar.xz $ARCHIVE/$hostname/$linkdest/$resultname.tar.xz
+        status=$?
+        if [[ $status -ne 0 ]] ;then
+            echo "$TS: Cannot move $ARCHIVE/$hostname/$resultname from $linksrc to $linkdest: code $status" >&4 | tee -a $mail_content
+            rm $RESULTS/$hostname/$prefix$resultname
+            nerrs=$nerrs+1
+            continue
+        fi
+    else
+        # unpack the tarballs into a temp area
+        pushd $UNPACK_PATH/$hostname > /dev/null 2>&1
+        tar --extract --no-same-owner --no-overwrite-dir --touch --file="$result"
+        status=$?
+        if [[ $status -ne 0 ]] ;then
+            echo "$TS: 'tar -xf $result' failed: code $status" >&4 | tee -a $mail_content
+            nerrs=$nerrs+1
+            popd > /dev/null 2>&1
+            continue
+        fi
+	
+        # chmod directories to at least 555
+        find . -type d -print0 | xargs -0 chmod ugo+rx
+        status=$?
+        if [[ $status -ne 0 ]] ;then
+            echo "$TS: 'chmod ugo+rx' of subdirs failed: code $status" >&4 | tee -a $mail_content
+            nerrs=$nerrs+1
+            popd > /dev/null 2>&1
+            continue
+        fi
+
+    	# chmod files to at least 444
+    	chmod -R ugo+r .
+    	status=$?
+    	if [[ $status -ne 0 ]] ;then
+        	echo "$TS: 'chmod -R ugo+r .' failed: code $status" >&4 | tee -a $mail_content
+        	nerrs=$nerrs+1
+        	popd > /dev/null 2>&1
+        	continue
+    	fi
+    	popd > /dev/null 2>&1
+
+    	# create the link from results to incoming *before* moving the directory from UNPACK_PATH.
+    	
+    	# if there is a prefix file, create a link as specified by the prefix
+    	# even if no prefix is specified, we still want to link from the results/ hierarchy to incoming/.
+    	# user access will eventually be through results/ only.
+    
+    	basedir=$(dirname $link)
+    	prefixfile=$basedir/prefix.$resultname
+    	if [ -f $prefixfile ] ;then
+            # add the slash to make both cases uniform in what follows
+            prefix=$(cat $prefixfile)/
+            mkdir -p $basedir/.prefix
+            mv $prefixfile $basedir/.prefix
+        else
+            prefix=""
+        fi
+
+	incoming=$INCOMING/$hostname/$resultname
+
+    	mkdir -p $RESULTS/$hostname/$prefix
+    	status=$?
+    	if [[ $status -ne 0 ]] ;then
+            echo "$TS: code $status: mkdir -p $RESULTS/$hostname/$prefix" >&4 | tee -a $mail_content
+    	else
+	    echo "ln -s $UNPACK_PATH/$hostname/$resultname $incoming"
+            ln -s $UNPACK_PATH/$hostname/$resultname $incoming
+            status=$?
+            if [[ $status -ne 0 ]] ;then
+                echo "$TS: code $status: ln -s $UNPACK_PATH/$hostname/$resultname $incoming" >&4 | tee -a $mail_content
+            fi
+            echo "ln -s $incoming $RESULTS/$hostname/$prefix$resultname"
+            ln -s $incoming $RESULTS/$hostname/$prefix$resultname
+            status=$?
+            if [[ $status -ne 0 ]] ;then
+                echo "$TS: code $status: ln -s $incoming $RESULTS/$hostname/$prefix$resultname" >&4 | tee -a $mail_content
+            fi
+        fi
+
+    	# move the link to $linkdest directory
+    	mv $ARCHIVE/$hostname/$linksrc/$resultname.tar.xz $ARCHIVE/$hostname/$linkdest/$resultname.tar.xz
+    	status=$?
+    	if [[ $status -ne 0 ]] ;then
+            echo "$TS: Cannot move $ARCHIVE/$hostname/$resultname from $linksrc to $linkdest: code $status" >&4 | tee -a $mail_content
+            rm $RESULTS/$hostname/$prefix$resultname
+            nerrs=$nerrs+1
+            continue
+    	fi
     fi
-    let end_time=$(date +%s)
-    let duration=end_time-start_time
-    # log the success
-    echo "$TS: $hostname/$resultname: success - elapsed time (secs): $duration - size (bytes): $size"
-    ntb=$ntb+1
+    	let end_time=$(date +%s)
+    	let duration=end_time-start_time
+    	# log the success
+    	echo "$TS: $hostname/$resultname: success - elapsed time (secs): $duration - size (bytes): $size"
+    	ntb=$ntb+1
 done < $list
 
 echo "$TS: Processed $ntb tarballs"
@@ -267,7 +279,7 @@ if [[ $nerrs -gt 0 ]]; then
     subj="$PROG.$TS($PBENCH_ENV) - w/ $nerrs errors"
     # don't send mail when running unittests
     if [[ "$_PBENCH_SERVER_TEST" != 1 ]] ;then
-        echo "Processed $ntotal result tar balls, $ntb successfully, with $nerrs errors and $ndups duplicates" | mailx -s "$subj" $mail_recipients
+        echo "Processed $ntotal result tar balls, $ntb successfully, with $nerrs errors and $ndups duplicates" | mailx -s "$subj" $mail_recipients < $mail_content
     fi
 fi
 
