Add a proper log environment for verify-backup-tarballs

diff --git a/server/pbench/bin/pbench-verify-backup-tarballs b/server/pbench/bin/pbench-verify-backup-tarballs
--- a/server/pbench/bin/pbench-verify-backup-tarballs
+++ b/server/pbench/bin/pbench-verify-backup-tarballs
@@ -43,6 +43,9 @@ primary=$ARCHIVE
 backup=$BDIR
 
 # work files
+controllers=$TMP/$PROG/controllers.$$
+files=$TMP/$PROG/files.$$
+allmd5s=$TMP/$PROG/allmd5s.$$
 listp=$TMP/$PROG/primary.$$
 listb=$TMP/$PROG/backup.$$
 tmp=$TMP/$PROG/tmp.$$
@@ -54,42 +57,53 @@ index_content=$TMP/$PROG/index_mail_contents
 # make sure the directory exists
 mkdir -p $TMP/$PROG
 
-controllers=$TMP/$PROG/controllers.$$
-trap "rm -f $controllers $listp $listp.failed $listb $listb.failed $tmp $ponly $bonly $report $index_content; rmdir $TMP/$PROG" EXIT INT QUIT
+trap "rm -f $controllers $files $allmd5s $listp $listp.failed $listb $listb.failed $tmp $ponly $bonly $report $index_content; rmdir $TMP/$PROG" EXIT INT QUIT
+
+# First argument is the exit code to use when a directory does not exist.
+function checkmd5 {
+    find . -maxdepth 1 -type d | grep -v '^\.$' > $controllers
+    while read d ;do
+        pushd $d > /dev/null || exit $1
+        ls | grep md5 | grep -v DUPLICATE__NAME > $files
+        > $allmd5s
+        while read f ;do
+            if [ -s $f ]; then
+                cat $f >> $allmd5s
+            else
+                echo "FAIL: Empty .md5 file: $d/$f"
+            fi
+        done < $files
+        if [ -s $allmd5s ] ;then
+            md5sum --check --warn $allmd5s | sed 's;^;'$d/';'
+        fi 
+        popd >/dev/null
+    done < $controllers
+}
+
+log_init $(basename $0) $LOGSDIR/$(basename $0)
+
+echo "start-$(timestamp)"
 
 # Initialize index mail content
 > $index_content
 
+# primary archive
 > $listp
 if cd $primary ;then
-    find . -maxdepth 1 -type d | grep -v '^\.$' > $controllers
-    while read d ;do
-        pushd $d > /dev/null || exit 5
-        files=$(ls | grep md5 | grep -v DUPLICATE__NAME)
-        if [ ! -z "${files}" ] ;then
-            md5sum -c ${files} | sed 's;^;'$d/';'
-        fi 
-        popd >/dev/null
-    done < $controllers | sort > $listp
+    checkmd5 5 | sort > $listp
 fi
 
 # backup location
 > $listb
 if cd $backup ;then
-    find . -maxdepth 1 -type d | grep -v '^\.$' > $controllers
-    while read d ;do
-        pushd $d > /dev/null || exit 6
-        files=$(ls | grep md5 | grep -v DUPLICATE__NAME)
-        if [ ! -z "${files}" ] ;then
-            md5sum -c ${files} | sed 's;^;'$d/';'
-        fi 
-        popd >/dev/null
-    done < $controllers | sort > $listb
+    checkmd5 6 | sort > $listb
 fi
 
-# construct the report
-> $report
 let ret=0
+
+# Construct the report file
+> $report
+
 grep FAIL $listp > $listp.failed
 if [ -s $listp.failed ] ;then
     (echo "* In $primary: The calculated MD5 of the following entries failed to match the stored MD5"
@@ -133,6 +147,10 @@ if [[ $ret == 0 ]] ;then
     fi
 fi
 
+echo "end-$(timestamp)"
+
+log_finish
+
 # send it
 subj="$PROG.$TS($PBENCH_ENV)"
 cat << EOF > $index_content
@@ -143,4 +161,3 @@ cat $report >> $index_content
 pbench-report-status --name $PROG --timestamp $TS --type status $index_content
 
 exit $ret
-
