fs-version-002: New Versioning Mechanism with inotify
This PR will do the following changes:

1. pbench-move-results will create a new versioning
mechanism on the server side to deal with the
incompatibility: old clients will remain unchanged
and the data will be processed exactly as they are
processed today; new clients will use the new
mechanism.

2. pbench-server-prep-version-001 is a new script:
it will scour the reception directory for xxx.tar.xz.md5
files. For each file, it will check the md5 sum and, if
successful, it will copy the tarball and its md5 to the
archive directory and create the link in the watch state
directories. That will get the ball rolling on the rest
of the processing. Errors like missing tarball, missing
md5, duplicate names, are detected and handled
appropriately (mostly by quarantining the tarball).

3. This PR will change the archive directory structure
to make it deeper and not as wide, by using the MD5
string of the tarball to implement an (on-disk) trie
(like git, or gluster): e.g. the MD5 sum
7341243af6d9af1025cbec71023dbff7 will generate a pathname
of 73/41/7341243af6d9af1025cbec71023dbff7 to a directory
that will hold the unpacked "container" tarball.

diff --git a/server/pbench/bin/pbench-move-unpacked b/server/pbench/bin/pbench-move-unpacked
--- a/server/pbench/bin/pbench-move-unpacked
+++ b/server/pbench/bin/pbench-move-unpacked
@@ -1,7 +1,7 @@
 #! /bin/bash
 # -*- mode: shell-script -*-
 
-# This script will run only on production environment as unpacking to incoming 
+# This script will run only on production environment as unpacking to incoming
 # is relatively slower than unpacking tarballs in a tmp directory and then
 # move it to incoming.
 
@@ -48,10 +48,12 @@ index_content=$tmp/index_mail_contents
 
 trap 'rm -rf $tmp' EXIT INT QUIT
 
-# find command will not generate any result if the linksrc is empty, and because of that du will not get any result 
-# to calculate the size. In that scenario du generates the size of the current directory as output, to handle
+# find command will not generate any result if the linksrc
+# is empty, and because of that du will not get any result
+# to calculate the size. In that scenario du generates the
+# size of the current # directory as output, to handle
 # that exclude the current directory.
-find $ARCHIVE/*/$linksrc -type l -name '*.tar.xz' -printf "%l\n" 2>/dev/null | grep -v DUPLICATE | xargs du -b --exclude "." 2>/dev/null | sort -n > $list
+find $ARCHIVE/inotify_state/$linksrc -type l -printf "%p\n" 2>/dev/null | grep -v DUPLICATE | xargs du -b --exclude "." 2>/dev/null | sort -n > $list
 
 typeset -i ntb=0
 
@@ -65,12 +67,12 @@ function process_tarball {
 
     link=$(readlink -e $result)
     if [ ! -f "$link" ] ;then
-        echo "$TS: $link does not exist" | tee -a $mail_content >&4 
+        echo "$TS: $link does not exist" | tee -a $mail_content >&4
         return 1
     fi
-    resultname=$(basename $result)
+    resultname=$(basename $link)
     resultname=${resultname%.tar.xz}
-    hostname=$(basename $(dirname $link))
+    hostname=$(cat $link.hostname)
 
     basedir=$(dirname $link)
 
@@ -97,17 +99,16 @@ function process_tarball {
     if [ ! -z $prefix -a ${prefix%/} = ${prefix} ] ;then
         prefix=${prefix}/
     fi
-
     # make sure that all the relevant state directories exist
-    mk_dirs $hostname
+    #mk_dirs inotify_state
     # ... and a couple of other necessities.
-    if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $hostname processing directories failed: code $status" | tee -a $mail_content >&4
-        return 1
-    fi
+    #if [[ $? -ne 0 ]] ;then
+    #    echo "$TS: Creation of $hostname processing directories failed: code $status" | tee -a $mail_content >&4
+    #    return 1
+    #fi
     mkdir -p $INCOMING/$hostname
     if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $INCOMING/$hostname failed: code $status" | tee -a $mail_content >&4 
+        echo "$TS: Creation of $INCOMING/$hostname failed: code $status" | tee -a $mail_content >&4
         return 1
     fi
 
@@ -116,19 +117,17 @@ function process_tarball {
     if [ ${resultname%%.*} == "DUPLICATE__NAME" ] ;then
         return 2
     fi
-
     incoming=$INCOMING/$hostname/$resultname
 
     let start_time=$(date +%s)
 
     # log the beginning process of tarball
     echo "Starting: $TS: $hostname/$resultname: size (bytes): $size"
-
     # copy the tarball contents to INCOMING - remove the link on failure
     cp -R $UNPACK_PATH/$hostname/$resultname $incoming.copy
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot copy $UNPACK_PATH/$hostname/$resultname to $incoming.copy: code $status" | tee -a $mail_content >&4 
+        echo "$TS: Cannot copy $UNPACK_PATH/$hostname/$resultname to $incoming.copy: code $status" | tee -a $mail_content >&4
         return 1
     fi
 
@@ -149,7 +148,7 @@ function process_tarball {
 	status=$?
     elif [ -e "$incoming" ] ;then
 	# impossible!
-	echo "$TS: Cannot happen - $incoming is neither a dir nor a symlink!" | tee -a $mail_content >&4 
+	echo "$TS: Cannot happen - $incoming is neither a dir nor a symlink!" | tee -a $mail_content >&4
 	return 1
     fi
     if [[ $status -ne 0 ]] ;then
@@ -172,31 +171,30 @@ function process_tarball {
         # move failed, $incoming.copy still exists
         rm -f $RESULTS/$hostname/$prefix$resultname
         ln -sf $incoming.copy $RESULTS/$hostname/$prefix$resultname
-        echo "$TS: Cannot rename $incoming.copy to $incoming: code $status" | tee -a $mail_content >&4 
+        echo "$TS: Cannot rename $incoming.copy to $incoming: code $status" | tee -a $mail_content >&4
         return 1
     else
-	# fix up the results link: this is usually not necessary
-	# but if $incoming was a dir (see above), then the link
-	# would point to $incoming.copy.
+        # fix up the results link: this is usually not necessary
+        # but if $incoming was a dir (see above), then the link
+        # would point to $incoming.copy.
         # Remove the link first (issue #771).
         rm -f $RESULTS/$hostname/$prefix$resultname
         ln -sf $incoming $RESULTS/$hostname/$prefix$resultname
     fi
-        
 
     # remove the unpacked tarballs from UNPACK_PATH directory
     rm -R $UNPACK_PATH/$hostname/$resultname
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot remove $UNPACK_PATH/$hostname/$resultname: code $status" | tee -a $mail_content >&4 
+        echo "$TS: Cannot remove $UNPACK_PATH/$hostname/$resultname: code $status" | tee -a $mail_content >&4
 	return 1
     fi
 
     # move the link to $linkdest directory
-    mv $ARCHIVE/$hostname/$linksrc/$resultname.tar.xz $ARCHIVE/$hostname/$linkdest/$resultname.tar.xz
+    mv $ARCHIVE/inotify_state/$linksrc/${result##*/} $ARCHIVE/inotify_state/$linkdest/$resultname.tar.xz
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot move $ARCHIVE/$hostname/$resultname from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4 
+        echo "$TS: Cannot move $ARCHIVE/inotify_state/$resultname from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4
         rm $RESULTS/$hostname/$prefix$resultname
         return 1
     fi
diff --git a/server/pbench/bin/pbench-satellite-cleanup b/server/pbench/bin/pbench-satellite-cleanup
--- a/server/pbench/bin/pbench-satellite-cleanup
+++ b/server/pbench/bin/pbench-satellite-cleanup
@@ -41,9 +41,6 @@ log_init $(basename $0) $LOGSDIR/$(basename $0)
 
 echo $TS: $PROG starting
 
-hosts="$(for host in $files;do echo ${host%%/*};done | sort -u )"
-tarballs=$(for tarball in $files; do echo ${tarball##*/}; done)
-
 typeset -i ntb=0
 typeset -i nerrs=0
 typeset -i ntberrs=0
@@ -52,6 +49,7 @@ typeset -i nstateerrs=0
 typeset -i nincomingerrs=0
 typeset -i nresultserrs=0
 typeset -i nprefixerrs=0
+typeset -i nhosterrs=0
 
 mail_content=$tmp/mail.log
 index_content=$tmp/index_mail_contents
@@ -60,83 +58,105 @@ index_content=$tmp/index_mail_contents
 > $mail_content
 > $index_content
 
-for host in $hosts; do
-    pushd $remotearchive/$host >/dev/null || exit 2
-    for x in $tarballs; do
-        ntb=$ntb+1
-        # remove tar file
-        if [ -s $x ]; then
-            rm $x
-        fi
+for link in $files; do
+    tar=$(readlink -e $remotearchive/$link)
+    pushd "${tar%/*}" >/dev/null || exit 2
+    ntb=$ntb+1
+
+    # remove tar file
+    if [ -s $tar ]; then
+        rm $tar
+    fi
+    rc=$?
+    if [ $rc != 0 ]; then
+        echo $TS: Failed to remove: $tar | tee -a $mail_content >&4
+        ntberrs=$ntberrs+1
+        # if we fail to remove the tarball, we'll just continue the loop
+        # but we'll send mail with the failure. Hopefully, the next time
+        # around we'll succeed (presumabley because the admins will have
+        # taken some action).
+        # OTOH, if we fail to remove any of the other related
+        # files/directories, we'll go on and try to delete the rest of them.
+        # If we manage to change the state, there might be remnants to clean
+        # up manually. The error mail will identify those.
+        # Note that if we do remove the tarball but fail to change the state,
+        # this error will persist until the state is changed manually.
+        continue
+    fi
+
+    # remove its md5
+    if [ -s $tar.md5 ]; then
+        rm $tar.md5
         rc=$?
         if [ $rc != 0 ]; then
-            echo $TS: Failed to remove: $remotearchive/$host/$x | tee -a $mail_content >&4 
-            ntberrs=$ntberrs+1
-            # if we fail to remove the tarball, we'll just continue the loop
-            # but we'll send mail with the failure. Hopefully, the next time around
-            # we'll succeed (presumabley because the admins will have taken some action).
-            # OTOH, if we fail to remove any of the other related files/directories, we'll
-            # go on and try to delete the rest of them. If we manage to change the state,
-            # there might be remnants to clean up manually. The error mail will identify those.
-            #
-            # Note that if we do remove the tarball but fail to change the state, this error
-            # will persist until the state is changed manually.
-            continue
-        fi
-        # remove its md5
-        if [ -s $x.md5 ]; then
-            rm $x.md5
-        fi
-        rc=$?
-        if [ $rc != 0 ]; then
-            echo $TS: Failed to remove: $remotearchive/$host/$x.md5 | tee -a $mail_content >&4 
+            echo $TS: Failed to remove: $tar.md5 | tee -a $mail_content >&4
             nmd5errs=$nmd5errs+1
         fi
-        # change the state to SATELLITE-DONE
-        if [ -L TO-DELETE/$x ]; then
-            mv TO-DELETE/$x SATELLITE-DONE
-        fi
+    fi
+
+    # change the state to SATELLITE-DONE
+    if [ -L $remotearchive/$link ]; then
+        mv $remotearchive/$link $(echo $remotearchive/$link | sed 's/TO-DELETE/SATELLITE-DONE/')
         if [ $rc != 0 ]; then
-            echo $TS: Failed to move: $remotearchive/$host/TO-DELETE/$x to SATELLITE-DONE | tee -a $mail_content >&4 
+            echo $TS: Failed to move: $remotearchive/$link to SATELLITE-DONE | tee -a $mail_content >&4
             nstateerrs=$nstateerrs+1
         fi
-        # remove from incoming
-        if [ -s $INCOMING/$host/${x%%.tar.xz} ]; then
-            rm -rf $INCOMING/$host/${x%%.tar.xz}
-        fi
+    fi
+
+    host=$(cat "$tar.hostname")
+    tar_name=${tar##*/}
+
+    # remove from incoming
+    if [ -s $INCOMING/hostnames/$host/${tar_name%%.tar.xz} ]; then
+        rm -rf $INCOMING/hostnames/$host/${tar_name%%.tar.xz}
         rc=$?
         if [ $rc != 0 ]; then
-            echo $TS: Failed to remove the tarball from Incoming directory: $INCOMING/$host/${x%%.tar.xz} | tee -a $mail_content >&4 
+            echo $TS: Failed to remove the tarball from Incoming directory: $INCOMING/hostnames/$host/${tar_name%%.tar.xz} | tee -a $mail_content >&4
             nincomingerrs=$nincomingerrs+1
         fi
-        #remove the results
-        if [ -s .prefix/prefix.${x%%.tar.xz} ]; then
-            prefix_value=$(cat ".prefix/prefix.${x%%.tar.xz}")
-        fi
-        if [ -z $prefix_value ]; then
-            sym_link=$RESULTS/$host/${x%%.tar.xz}
-        else
-            sym_link=$RESULTS/$host/$prefix_value/${x%%.tar.xz}
-        fi
-        if [ -L $sym_link ]; then
-            rm $sym_link
-            rc=$?
-            if [ $rc != 0 ]; then
-                echo $TS: Failed to remove: $sym_link | tee -a $mail_content >&4 
-                nresultserrs=$nresultserrs+1
-            fi
-        fi
-        # remove prefix if present
-        prefix=".prefix/prefix.${x%%.tar.xz}"
-        if [ -s $prefix ]; then
-            rm $prefix
-        fi
+    fi
+
+    #remove the results
+    if [ -s .prefix/prefix.${tar_name%%.tar.xz} ]; then
+        prefix_value=$(cat ".prefix/prefix.${tar_name%%.tar.xz}")
+    else
+        prefix_value=""
+    fi
+
+    if [ -z $prefix_value ]; then
+        sym_link=$RESULTS/hostnames/$host/${tar_name%%.tar.xz}
+    else
+        sym_link=$RESULTS/hostnames/$host/$prefix_value/${tar_name%%.tar.xz}
+    fi
+    if [ -L $sym_link ]; then
+        rm $sym_link
         rc=$?
         if [ $rc != 0 ]; then
-            echo $TS: Failed to remove: $prefix | tee -a $mail_content >&4 
+            echo $TS: Failed to remove: $sym_link | tee -a $mail_content >&4
+            nresultserrs=$nresultserrs+1
+        fi
+    fi
+
+    # remove prefix if present
+    prefix=".prefix/prefix.${tar_name%%.tar.xz}"
+    if [ -s $prefix ]; then
+        rm $prefix
+        rc=$?
+        if [ $rc != 0 ]; then
+            echo $TS: Failed to remove: $prefix | tee -a $mail_content >&4
             nprefixerrs=$nprefixerrs+1
         fi
-    done
+    fi
+
+    #remove the hostname file
+    if [ -s "$tar.hostname" ]; then
+        rm "$tar.hostname"
+        rc=$?
+        if [ $rc != 0 ]; then
+            echo $TS: Failed to remove: "$tar.hostname" | tee -a $mail_content >&4
+            nhosterrs=$nhosterrs+1
+        fi
+    fi
     popd > /dev/null
 done
 
diff --git a/server/pbench/bin/pbench-server-prep-shim-002 b/server/pbench/bin/pbench-server-prep-shim-002
--- a/server/pbench/bin/pbench-server-prep-shim-002
+++ b/server/pbench/bin/pbench-server-prep-shim-002
@@ -4,7 +4,7 @@
 # This shim is used to prepare the tarballs that a version 002 client
 # submits for further processing. It copies the tarballs and their MD5
 # sums to the archive (after checking) and sets the state links, so
-# that the dispatch script will pick them up and get the ball
+# that the associates scripts will pick them up and get the ball
 # rolling. IOW, it does impedance matching between version 002 clients
 # and the server scripts.
 
@@ -94,9 +94,12 @@ if [ $sts != 0 ]; then
     exit 4
 fi
 
+linkdestlist=$(getconf.py -l dispatch-states pbench-server)
 list=$tmp/list.check
-status=$tmp/status
-> $status
+index_content=$tmp/index_mail_contents
+
+# Initialize index mail content
+> $index_content
 
 echo $TS
 # Check for results that are ready for processing: version 002 agents
@@ -116,10 +119,10 @@ typeset -i nerrs=0
 typeset -i nquarantined=0
 typeset -i ndups=0
 
-while read ck ;do
+while read result ;do
     ntotal=$ntotal+1
     # full pathname of tarball
-    tb=${ck%.md5}
+    tb=${result%.md5}
 
     # directory
     tbdir=$(dirname ${tb})
@@ -128,10 +131,22 @@ while read ck ;do
     resultname=$(basename ${tb})
     resultname=${resultname%.tar.xz}
 
-    # the controller hostname is the last component of the directory part of the full path
+    # the controller hostname is the last component of the directory part
+    # of the full path
     controller=$(basename ${tbdir})
 
-    dest=${archive}/${controller}
+    dest=${archive}
+
+#    # Make sure the inotify state directories are present
+#    for state in $linkdestlist ;do
+#        if [ ! -d "${INOTIFY_STATE_DIR}/$state" ]; then
+#            mkdir -p ${INOTIFY_STATE_DIR}/$state
+#            sts=$?
+#            if [ $sts -ne 0 ] ;then
+#                echo "$TS: Failed: \"mkdir -p ${INOTIFY_STATE_DIR}/$state\", status $sts" | tee -a $index_content >&4
+#            fi
+#        fi
+#    done
 
     # sanity checks
     if [ ! -f ${tb} ] ;then
@@ -142,6 +157,7 @@ while read ck ;do
         fi
         continue
     fi
+    
     # Impossible: the md5 file disappeared between the find and this check!
     if [ ! -f ${tb}.md5 ] ;then
         echo "$TS: Quarantined: ${tb}.md5 file does not exist" >&4
@@ -150,6 +166,7 @@ while read ck ;do
         continue
     fi
 
+    # check the md5sum
     pushd ${tbdir} >/dev/null 2>&4
     md5sum --check ${resultname}.tar.xz.md5
     sts=$?
@@ -164,50 +181,123 @@ while read ck ;do
 
     if [ -f ${dest}/${resultname}.tar.xz -o -f ${dest}/${resultname}.tar.xz.md5 ] ;then
         echo "$TS: Duplicate: ${tb} duplicate name" >&4
-        quarantine ${duplicates}/${controller}  ${tb} ${tb}.md5
+        quarantine ${duplicates}/${controller} ${tb} ${tb}.md5
         ndups=$ndups+1
     fi
 
-    mkdir -p ${dest}/TODO
-    sts=$?
-    if [ $sts -ne 0 ] ;then
-        echo "$TS: Error: \"mkdir -p ${dest}\", status $sts" |
-            tee -a $status >&4
+    # Create the trie structure using md5sum
+    hash=$(md5sum "${tb}" | awk '{ print $1 }')
+    if [ -z $hash ]; then
         quarantine ${errors}/${controller} ${tb} ${tb}.md5
+        echo "$TS: Failed: md5sum ${tb}" | tee -a $index_content >&4
         nerrs=$nerrs+1
         continue
     fi
 
-    mv ${tb} ${tb}.md5 $dest
-    sts=$?
-    if [ $sts -ne 0 ] ;then
-        echo "$TS: Error: \"mv ${tb} ${tb}.md5 $dest\", status $sts" |
-            tee -a $status >&4
+    hash_path=$(echo $hash | cut -b 1-2)/$(echo $hash | cut -b 3-4)/$(echo $hash | cut -b 5-)
+    if [ -z $hash_path ]; then
         quarantine ${errors}/${controller} ${tb} ${tb}.md5
+        echo "$TS: Failed to evaluate the trie structure path" | tee -a $index_content >&4
         nerrs=$nerrs+1
+        continue
     fi
 
-    pushd $dest/TODO > /dev/null >/dev/null 2>&1
-    ln -s $dest/$(basename $tb) .
+    # Create the trie structure path if not present
+    result_full_path="${dest}/$hash_path"
+    if [ ! -d "$result_full_path" ]; then
+        mkdir -p $result_full_path
+        sts=$?
+        if [ $sts -ne 0 ] ;then
+            quarantine ${errors}/${controller} ${tb} ${tb}.md5
+            echo "$TS: Failed: \"mkdir -p $result_full_path\", status $sts" | tee -a $index_content >&4
+            nerrs=$nerrs+1
+            continue
+        fi
+    fi
+
+#    # Make an entry in the hostnames directory if not present
+#    hostnames_full_path="${dest}/hostnames/${controller}"
+#    if [ ! -d "${hostnames_full_path}" ]; then
+#        mkdir -p ${hostnames_full_path}
+#        sts=$?
+#        if [ $sts -ne 0 ] ;then
+#            quarantine ${errors}/${controller} ${tb} ${tb}.md5
+#            echo "$TS: Failed: \"mkdir -p ${hostnames_full_path}\", status $sts" | tee -a $index_content >&4
+#            nerrs=$nerrs+1
+#            continue
+#        fi
+#    fi
+
+    # make sure that all the relevant state directories exist
+    mk_dirs inotify_state
+    status=$?
+    if [[ $status -ne 0 ]] ;then
+        quarantine ${errors}/${controller} ${tb} ${tb}.md5
+        echo "$TS: Creation of $controller processing directories failed: code $status" | tee -a $index_content >&4
+        nerrs=$nerrs+1
+        continue
+    fi
+
+    # move the tarball and its md5
+    mv ${tb} ${tb}.md5 ${result_full_path}
     sts=$?
     if [ $sts -ne 0 ] ;then
-        echo "$TS: Error: \"ln -s $dest/$(basename $tb) .\", status $sts" |
-            tee -a $status >&4
-        quarantine ${errors}/${controller} ${dest}/${tb} ${dest}/${tb}.md5 ${prefix}
+        quarantine ${errors}/${controller} ${tb} ${tb}.md5
+        echo "$TS: Failed: \"mv ${tb} ${tb}.md5 $result_full_path\", status $sts" | tee -a $index_content >&4
         nerrs=$nerrs+1
-    else
-        echo "$TS: processed ${tb}" >> $status
-        ntbs=$ntbs+1
+        continue
     fi
-    popd > /dev/null 2>&1
+
+    # generate the hostname file
+    tb_name=${tb##*/}
+    echo ${controller} > ${result_full_path}/${tb_name}.hostname
+    sts=$?
+    if [ $sts -ne 0 ] ;then
+        quarantine ${errors}/${controller} ${result_full_path}/${tb_name} \
+        ${result_full_path}/${tb_name}.md5 \
+        ${result_full_path}/${tb_name}.hostname
+        echo "$TS: Failed: \"echo ${controller} > ${result_full_path}/${tb_name}.hostname\", status $sts" | tee -a $index_content >&4
+        nerrs=$nerrs+1
+        continue
+    fi
+
+    # create a link in each state dir - if any fail, we should delete them all?# No, that would be racy.
+    for state in $linkdestlist ;do
+#        ln -s $result_full_path/${tb_name} $hostnames_full_path/$state
+#        status=$?
+#        if [[ $status -ne 0 ]] ;then
+#            quarantine ${errors}/${controller} ${result_full_path}/${tb_name} \
+#            ${result_full_path}/${tb_name}.md5 \
+#            ${result_full_path}/${tb_name}.hostname
+#            echo "$TS: Cannot create $result_full_path/${tb_name} link from $linksrc to $state: code $status" | tee -a $index_content >&4
+#            nerrs=$nerrs+1
+#            continue
+#	fi
+        watched_dir=${INOTIFY_STATE_DIR}/$state
+        ln -s $result_full_path/${tb_name} ${watched_dir}/$hash
+        sts=$?
+        if [ $sts -ne 0 ] ;then
+            quarantine ${errors}/${controller} ${result_full_path}/${tb_name} \
+            ${result_full_path}/${tb_name}.md5 \
+            ${result_full_path}/${tb_name}.hostname
+            rm $hostnames_full_path/$state/${tb_name}
+            echo "$TS: Failed: \"ln -s $result_full_path/${tb_name} ${watched_dir}/$md5\", status $sts" | tee -a $index_content >&4
+            nerrs=$nerrs+1
+            continue
+        fi
+    done
+
+    # log the success
+    echo "$TS: processed ${tb}" >> $index_content
+    ntbs=$ntbs+1
 done < $list
 
-echo "$TS: Processed $ntotal entries, $ntbs tarballs successful,"\
-     "$nquarantined quarantined tarballs, $ndups duplicately-named tarballs,"\
-     "$nerrs errors." | tee -a $status
+echo "$TS: Processed $ntotal entries, $ntbs tarballs successful,\
+   # $nquarantined quarantined tarballs, $ndups duplicately-named tarballs,\
+    $nerrs errors." | tee -a $index_content
 
 log_finish
 
-pbench-report-status --name $PROG --timestamp $TS --type status $status
+pbench-report-status --name $PROG --timestamp $TS --type status $index_content
 
 exit $nerrs
diff --git a/server/pbench/bin/pbench-sync-satellite b/server/pbench/bin/pbench-sync-satellite
--- a/server/pbench/bin/pbench-sync-satellite
+++ b/server/pbench/bin/pbench-sync-satellite
@@ -90,6 +90,8 @@ typeset -i nprocessed=0
 typeset -i nfailed_md5=0
 typeset -i nerrs=0
 
+linkdestlist=$(getconf.py -l dispatch-states pbench-server)
+
 unpack=$tmp/unpack.$prefix
 trap "rm -rf $tmp" EXIT QUIT INT
 
@@ -102,9 +104,11 @@ index_content=$tmp/index_mail_contents
 
 log_init $(basename $0) $LOGSDIR/$(basename $0)
 logdir=$LOGSDIR/$(basename $0)/$prefix/$TS
+
 # remove the tmp dir on exit; try to remove an empty $logdir
 # but suppress any complaints.
 trap "rm -rf $tmp; rmdir $logdir 2>/dev/null" EXIT QUIT INT
+
 mkdir -p $logdir
 rc=$?
 if [[ $rc != 0 ]] ;then
@@ -116,14 +120,12 @@ fi
 ssh $remotehost "/opt/pbench-server/bin/pbench-sync-package-tarballs" > $tmp/satellite.$prefix.tar
 rc=$?
 if [[ $rc != 0 ]] ;then
-    echo "$PROG: ssh $remotehost /opt/pbench-server/bin/pbench-sync-package-tarballs: failed." >&4
+    echo "$PROG: ssh $remotehost /opt/pbench-server/bin/pbench-sync-package-tarballs-inotify: failed." >&4
     exit 2
 fi
 
 # unpack the tarball into tmp directory
 tar -xf $tmp/satellite.$prefix.tar -C $unpack
-files=$(find $unpack -path '*.tar.xz' -printf '%P\n')
-hosts="$(for host in $files;do echo ${host%%/*};done | sort -u )"
 
 # initialize change state log and mail content
 > $LOGSDIR/change-state.$prefix.log
@@ -133,46 +135,96 @@ hosts="$(for host in $files;do echo ${host%%/*};done | sort -u )"
 let start_time=$(timestamp-seconds-since-epoch)
 echo "$TS: start - $(timestamp)"
 
-for host in $hosts ;do
+files=$(find $unpack -path '*.tar.xz' -printf '%P\n')
+
+pushd $unpack > /dev/null
+for tarball in $files ;do
     typeset -i processed=0
     typeset -i failed_md5=0
-    localdir=$ARCHIVE/$prefix::$host
 
-    if [ ! -d $localdir ] ;then
-        mkdir -p $localdir || exit 1
-    fi
-    pushd $localdir >/dev/null || exit 2
-    if [ ! -d $logdir/$host ] ;then
-        mkdir -p $logdir/$host
+    # Get the hostname from hostname file
+    controller=$(cat $tarball.hostname)
+    if [ -z $controller ]; then
+        echo "$TS: Unable to get the hostname" >&4
+        nerrs=$nerrs+1
+        continue
     fi
 
+    if [ ! -d $logdir/$prefix::$controller ] ;then
+        mkdir -p $logdir/$prefix::$controller
+    fi
+
+    # Create the trie structure using md5sum
+    hash=$(md5sum "$tarball" | awk '{ print $1 }')
+    if [ -z $hash ]; then
+        echo "$TS: Failed: md5sum $tarball" >&4
+        nerrs=$nerrs+1
+        continue
+    fi
+
+    hash_path=$(echo $hash | cut -b 1-2)/$(echo $hash | cut -b 3-4)/$(echo $hash | cut -b 5-)
+    if [ -z $hash_path ]; then
+        echo "$TS: Failed to calculate the trie structure path" >&4
+        nerrs=$nerrs+1
+        continue
+    fi
+
+    # Create the trie structure path if not present
+    result_full_path="$ARCHIVE/$hash_path"
+    if [ ! -d "$result_full_path" ]; then
+        mkdir -p $result_full_path
+        sts=$?
+        if [ $sts -ne 0 ] ;then
+            echo "$TS: Failed: \"mkdir -p $result_full_path\", status $sts" >> $status
+        fi
+    fi
+
+#    # Make an entry in the hostnames directory if not present
+#    hostnames_full_path="$ARCHIVE/hostnames/$prefix::$controller"
+#    if [ ! -d "$hostnames_full_path" ]; then
+#        mkdir -p $hostnames_full_path
+#        sts=$?
+#        if [ $sts -ne 0 ] ;then
+#            echo "$TS: Failed: \"mkdir -p $hostnames_full_path\", status $sts" >> $status
+#        fi
+#    fi
+
+    # make sure that all the relevant state directories exist
+    mk_dirs inotify_state
+    status=$?
+    if [[ $status -ne 0 ]] ;then
+        echo "$TS: Creation of $controller processing directories failed: code $status" >&4
+        nerrs=$nerrs+1
+        continue
+    fi
+
+    # tarball name
+    tb_name=${tarball##*/}
+
+    # move the tarball, its md5 and hostname file
+    mv $tarball $tarball.md5 $tarball.hostname $result_full_path
+    sts=$?
+    if [ $sts -ne 0 ] ;then
+        echo "$TS: Failed: \"mv $tarball $tarball.md5 $result_full_path\", status $sts" >> $index_content
+        nerrs=$nerrs+1
+    fi
+
+    pushd $result_full_path > /dev/null || exit 2
     # get the tarball list for this host
-    flist=$(find $unpack/$host -type f -name '*.tar.xz.md5' | sed 's;'$unpack/$host/';;')
-
+    flist=$(find . -type f -name '*.tar.xz.md5')
     echo $flist
-
-    # move the unpacked files from tmp directory to archive
-    mv $unpack/$host/* .
-
-    # move prefix files if present
-    if [[ -d $unpack/$host/.prefix ]] ;then
-        mkdir -p ./.prefix
-        mv $unpack/$host/.prefix/* ./.prefix
-    fi
-
-    # make the state dirs: TODO, TO-INDEX, TO-COPY-SOS etc.
-    mk_dirs $prefix::$host
 
     # check md5s and move md5s to its appropriate state directories according to pass or fail
     md5_list="$flist"
-    md5sum -c $md5_list > $logdir/$host/md5-checks.log
-    processed=$(wc -l < $logdir/$host/md5-checks.log)
+    md5sum -c $md5_list > $logdir/$controller/md5-checks.log
+    processed=$(wc -l < $logdir/$controller/md5-checks.log)
     nprocessed=$((nprocessed + processed))
-    grep 'OK' $logdir/$host/md5-checks.log > $logdir/$host/ok-checks.log
-    if [ -s $logdir/$host/ok-checks.log ] ;then
-        md5_pass=$(cat $logdir/$host/ok-checks.log | sed -n 's/: OK//p')
+
+    grep 'OK' $logdir/$controller/md5-checks.log > $logdir/$controller/ok-checks.log
+    if [ -s $logdir/$controller/ok-checks.log ] ;then
+        md5_pass=$(cat $logdir/$controller/ok-checks.log | sed -n 's/: OK//p')
         for x in $md5_pass; do
-            ln -sf $PWD/$x SATELLITE-MD5-PASSED/$x
+            ln -sf $PWD/$x $ARCHIVE/inotify_state/SATELLITE-MD5-PASSED/$x
             status=$?
             if [[ $status != 0 ]] ;then
                 nerrs=$nerrs+1
@@ -182,14 +234,15 @@ for host in $hosts ;do
             fi
         done
     fi
-    grep 'FAIL' $logdir/$host/md5-checks.log > $logdir/$host/fail-checks.log
-    cat $logdir/$host/fail-checks.log >> $mail_content
-    failed_md5=$(wc -l < $logdir/$host/fail-checks.log)
+
+    grep 'FAIL' $logdir/$controller/md5-checks.log > $logdir/$controller/fail-checks.log
+    cat $logdir/$controller/fail-checks.log >> $mail_content
+    failed_md5=$(wc -l < $logdir/$controller/fail-checks.log)
     nfailed_md5=$((nfailed_md5 + failed_md5))
-    if [ -s $logdir/$host/fail-checks.log ] ;then
-        md5_fail=$(cat $logdir/$host/fail-checks.log | sed -n 's/: FAIL//p')
+    if [ -s $logdir/$controller/fail-checks.log ] ;then
+        md5_fail=$(cat $logdir/$controller/fail-checks.log | sed -n 's/: FAIL//p')
         for x in $md5_fail; do
-            ln -sf $PWD/$x SATELLITE-MD5-FAILED/$x
+            ln -sf $PWD/$x $ARCHIVE/inotify_state/SATELLITE-MD5-FAILED/$x
             status=$?
             if [[ $status != 0 ]] ;then
                 nerrs=$nerrs+1
@@ -199,28 +252,44 @@ for host in $hosts ;do
             fi
         done
     fi
-    # create symlinks for the synced tarballs in TODO
-    if [ -s $logdir/$host/ok-checks.log ] ;then
-        for x in $md5_pass; do
-            ln -sf $PWD/$x TODO/$x
-            status=$?
-            if [[ $status != 0 ]] ;then
-                nerrs=$nerrs+1
-                echo "Failed to create the symlink for TODO state directory: ln -sf \
-                $PWD/$x TODO/$x" | tee -a $mail_content >&4
-                continue
-            fi
-        done
-    fi
+
+    # create a link in each state dir - if any fail, we should delete them all?# No, that would be racy.
+    for state in $linkdestlist ;do
+        ln -s $result_full_path/$tb_name $INOTIFY_STATE_DIR/$state
+        status=$?
+        if [[ $status -ne 0 ]] ;then
+            echo "$TS: Cannot create $result_full_path/$tb_name link from $linksrc to $state: code $status" >&4
+            nerrs=$nerrs+1
+            continue
+#        else
+#            if [ ! -d "$INOTIFY_STATE_DIR/$state" ]; then
+#                mkdir -p $INOTIFY_STATE_DIR/$state
+#            fi
+#            sts=$?
+#            if [ $sts -ne 0 ] ;then
+#                echo "$TS: Failed: \"mkdir -p $INOTIFY_STATE_DIR/$state-DIR\", status $sts" >> $index_content
+#                nerrs=$nerrs+1
+#            fi
+#            watched_dir=$INOTIFY_STATE_DIR/$state
+#	    ln -s $result_full_path/$tb_name $watched_dir
+#            sts=$?
+#            if [ $sts -ne 0 ] ;then
+#                echo "$TS: Failed: \"ln -s $result_full_path/$tb_name $watched_dir\", status $sts" >> $index_content
+#                nerrs=$nerrs+1
+#           fi
+        fi
+    done
+
     # save the contents of ok checks to further use it for state change
-    if [ -s $logdir/$host/ok-checks.log ] ;then
-        state_list=$(cat $logdir/$host/ok-checks.log | sed -n 's/: OK//p')
+    if [ -s $logdir/$controller/ok-checks.log ] ;then
+        state_list=$(cat $logdir/$controller/ok-checks.log | sed -n 's/: OK//p')
         for x in $state_list; do
-            echo "$host/TO-SYNC/$x" >> $LOGSDIR/change_state.$prefix.log
+            echo "inotify_state/TO-SYNC/$x" >> $LOGSDIR/change_state.$prefix.log
         done
     fi
     popd > /dev/null
 done
+popd > /dev/null
 
 # change the state of the tarballs on remote
 if [ -s $LOGSDIR/change_state.$prefix.log ] ;then
diff --git a/server/pbench/bin/pbench-unpack-tarballs b/server/pbench/bin/pbench-unpack-tarballs
--- a/server/pbench/bin/pbench-unpack-tarballs
+++ b/server/pbench/bin/pbench-unpack-tarballs
@@ -52,7 +52,6 @@ case $opts in
 esac
 
 UNPACK_PATH=$1
-#mkdir -p $UNPACK_PATH
 
 # TOP, ARCHIVE, INCOMING, RESULTS, USERS are all defined by the base file
 . $dir/pbench-base.sh
@@ -73,11 +72,13 @@ test -d $RESULTS || doexit "Bad RESULTS=$RESULTS"
 # the link source and destination for this script
 linksrc=TO-UNPACK
 linkdest=UNPACKED
+#linksrc_inotify=TO-UNPACK-DIR
+#linkdest_inotify=TO-UNPACK-DONE-DIR
 echo $TS
 
 tmp=$TMP/$PROG.$$
 
-trap 'rm -rf $tmp' EXIT INT QUIT
+trap "rm -rf $tmp $TMP/$(basename $0).$$" EXIT INT QUIT
 
 mkdir -p $tmp
 
@@ -88,12 +89,6 @@ index_content=$tmp/index_mail_contents
 # get the list of files we'll be operating on - sort them by size
 list=$tmp/$PROG.list
 
-# find command will not generate any result if the linksrc is empty,
-# and because of that, du will not get any result to calculate the
-# size. In that scenario, du generates the size of the current
-# directory as output; to handle that exclude the current directory.
-find $ARCHIVE/*/$linksrc -type l -name '*.tar.xz' -printf "%l\n" 2>/dev/null | grep -v DUPLICATE | xargs du -b --exclude "." 2>/dev/null | sort -n > $list
-
 typeset -i ntb=0
 typeset -i ntotal=0
 typeset -i nerrs=0
@@ -103,9 +98,19 @@ typeset -i ndups=0
 > $mail_content
 > $index_content
 
+shift
+
+# move the files to tmp for multiple concurrent executions
+flock -x $ARCHIVE/inotify_state/$linksrc mv $ARCHIVE/inotify_state/$linksrc/* $tmp
+# find all the symlinks in tmp directory to be processed. find command will not
+# generate any result if the linksrc is empty, and because of that du will not
+# get any result to calculate the size. In that scenario du generates the size
+# of the current directory as output, to handle that exclude the current
+# directory.
+find $tmp -type l -printf "%p\n" 2>/dev/null |
+	grep -v DUPLICATE | xargs du -b --exclude "." 2>/dev/null | sort -n > $list
 while read size result ;do
     ntotal=$ntotal+1
-
     link=$(readlink -e $result)
     if [ ! -f "$link" ] ;then
         echo "$TS: $link does not exist" | tee -a $mail_content >&4
@@ -114,21 +119,13 @@ while read size result ;do
     fi
     resultname=$(basename $result)
     resultname=${resultname%.tar.xz}
-    hostname=$(basename $(dirname $link))
+    hostname=$(cat $link.hostname)
 
     # echo "Link=$link"
     # echo "Resultname=$resultname"
     # echo "Hostname=$hostname"
     # continue
 
-    # make sure that all the relevant state directories exist
-    mk_dirs $hostname
-    # ... and a couple of other necessities.
-    if [[ $? -ne 0 ]] ;then
-        echo "$TS: Creation of $hostname processing directories failed: code $status" | tee -a $mail_content >&4
-        nerrs=$nerrs+1
-        continue
-    fi
     mkdir -p $INCOMING/$hostname
     if [[ $? -ne 0 ]] ;then
         echo "$TS: Creation of $INCOMING/$hostname failed: code $status" | tee -a $mail_content >&4
@@ -253,11 +250,10 @@ while read size result ;do
             fi
         fi
     fi
-
-    mv $ARCHIVE/$hostname/$linksrc/$resultname.tar.xz $ARCHIVE/$hostname/$linkdest/$resultname.tar.xz
+    mv $tmp/${result##*/} $ARCHIVE/inotify_state/$linkdest
     status=$?
     if [[ $status -ne 0 ]] ;then
-        echo "$TS: Cannot move $ARCHIVE/$hostname/$resultname from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4
+        echo "$TS: Cannot move $result from $linksrc to $linkdest: code $status" | tee -a $mail_content >&4
         # Cleanup needed here but trap takes care of it.
         rm -rf $incoming
         rm $RESULTS/$hostname/$prefix$resultname
@@ -265,10 +261,19 @@ while read size result ;do
         continue
     fi
 
+#    mv $INOTIFY_STATE_DIR/$linksrc_inotify/$resultname.tar.xz $INOTIFY_STATE_DIR/$linkdest_inotify/$resultname.tar.xz
+#    status=$?
+#    if [[ $status -ne 0 ]] ;then
+#        echo "$TS: Cannot move $INOTIFY_STATE_DIR/$linksrc_inotify/$resultname.tar.xz to $linkdest_inotify: code $status" | tee -a $mail_content >&4
+#        nerrs=$nerrs+1
+#        continue
+#    fi
+
     let end_time=$(date +%s)
     let duration=end_time-start_time
     # log the success
-    echo "$TS: $hostname/$resultname: success - elapsed time (secs): $duration - size (bytes): $size"
+    echo "$TS: $hostname/$resultname: success - elapsed time (secs): $duration
+        - size (bytes): $size"
     ntb=$ntb+1
 done < $list
 
