Use tail for all unit tests

diff --git a/run-unittests b/run-unittests
--- a/run-unittests
+++ b/run-unittests
@@ -3,80 +3,63 @@
 dir=$(dirname $0)
 let sts=0
 
+> /var/tmp/agent.bench-scripts.out
 $dir/agent/bench-scripts/unittests > /var/tmp/agent.bench-scripts.out 2>&1 < /dev/null &
 bpid=$!
+
+> /var/tmp/agent.tool-scripts.pp.out
 $dir/agent/tool-scripts/postprocess/unittests > /var/tmp/agent.tool-scripts.pp.out 2>&1 < /dev/null &
 tpid=$!
+
+> /var/tmp/agent.util-scripts.out
 $dir/agent/util-scripts/unittests > /var/tmp/agent.util-scripts.out 2>&1 < /dev/null &
 upid=$!
+
+> /var/tmp/server.out
 $dir/server/bin/unittests > /var/tmp/server.out 2>&1 < /dev/null &
 spid=$!
 
-echo "+++ Agent bench-scripts Unit Tests +++"
-echo ""
-wait $bpid
-let bs_sts=$?
-let sts=sts+bs_sts
-cat /var/tmp/agent.bench-scripts.out && rm /var/tmp/agent.bench-scripts.out
-echo ""
-if [[ $bs_sts -ne 0 ]]; then
-    status="FAILED"
-else
-    status="SUCCEEDED"
-fi
-echo "--- Agent bench-scripts Unit Tests ($status) ---"
-echo ""
-echo ""
-echo ""
-echo "+++ Agent tool-scripts/postprocess Unit Tests +++"
-echo ""
-wait $tpid
-let pp_sts=$?
-let sts=sts+pp_sts
-cat /var/tmp/agent.tool-scripts.pp.out && rm /var/tmp/agent.tool-scripts.pp.out
-echo ""
-if [[ $pp_sts -ne 0 ]]; then
-    status="FAILED"
-else
-    status="SUCCEEDED"
-fi
-echo "--- Agent tool-scripts/postprocess Unit Tests ($status) ---"
-echo ""
-echo ""
-echo ""
-echo "+++ Agent util-scripts Unit Tests +++"
-echo ""
-wait $upid
-let us_sts=$?
-let sts=sts+us_sts
-cat /var/tmp/agent.util-scripts.out && rm /var/tmp/agent.util-scripts.out
-echo ""
-if [[ $us_sts -ne 0 ]]; then
-    status="FAILED"
-else
-    status="SUCCEEDED"
-fi
-echo "--- Agent util-scripts Unit Tests ($status) ---"
-echo ""
-echo ""
-echo ""
-echo "+++ Server Unit Tests +++"
-echo ""
-# We tail the server test output in the background
-tail -n 9999999 -f /var/tmp/server.out --pid $spid &
-tail_pid=$!
-wait $spid
-let sr_sts=$?
-let sts=sts+sr_sts
-wait $tail_pid > /dev/null 2>&1
-rm -f /var/tmp/server.out
-echo ""
-if [[ $sr_sts -ne 0 ]]; then
-    status="FAILED"
-else
-    status="SUCCEEDED"
-fi
-echo "--- Server Unit Tests ($status) ---"
+function tail_and_wait {
+    pid=$1
+    name=$2
+    file=$3
+    printf -- "+++ ${name} Unit Tests +++\n\n"
+
+    tail -n 9999999 -f ${file} --pid ${pid}
+    if [[ $? -ne 0 ]]; then
+        printf -- "tail -f ${file} --pid ${pid} failed\n" >&2
+        return 1
+    fi
+    wait ${pid}
+    let tw_sts=$?
+    if [[ $tw_sts -ne 0 ]]; then
+	status="FAILED"
+    else
+	status="SUCCEEDED"
+    fi
+    rm -f ${file}
+
+    printf -- "\n--- ${name} Unit Tests ($status) ---\n"
+    return $tw_sts
+}
+
+tail_and_wait $bpid 'Agent bench-scripts' /var/tmp/agent.bench-scripts.out
+let sts=sts+$?
+
+printf -- "\n\n\n"
+
+tail_and_wait $tpid 'Agent tool-scripts/postprocess' /var/tmp/agent.tool-scripts.pp.out
+let sts=sts+$?
+
+printf -- "\n\n\n"
+
+tail_and_wait $upid 'Agent util-scripts' /var/tmp/agent.util-scripts.out
+let sts=sts+$?
+
+printf -- "\n\n\n"
+
+tail_and_wait $spid 'Server' /var/tmp/server.out
+let sts=sts+$?
 
 if [ $sts -gt 0 ]; then
     echo "Unit tests FAILED"
