Backport container build enhancements
There have been a number of enhancements to how we build containers
that need to be available for building the `b0.69` branch.  We were
successful using these changes to build the `v0.69.4-agent` release
using them.

We had to remove the `atomic-openshift-clients` RPM dependency from
the "tool" image since that repo is really per OpenShift version.

diff --git a/agent/containers/images/gen-tags-from-rpm b/agent/containers/images/gen-tags-from-rpm
--- a/agent/containers/images/gen-tags-from-rpm
+++ b/agent/containers/images/gen-tags-from-rpm
@@ -1,8 +1,30 @@
 #!/bin/bash
 
+# Generate 3 lines of output to stdout containing strings which can be used as
+# image tags.
+#
+# The first line emitted contains one tag representing the Git SHA1 short hash
+# label taken from the RPM's commit ID suffix.
+#
+# The second line contains the full version string without the Git commit ID
+# suffix.
+#
+# The third line contains two separate labels separated by white space, the
+# first being the "latest" label using only the "major" ID from the version
+# string, the second being the "latest" label using the "major" and "minor" ID.
+#
+# For example:
+#
+#   RPM Version String:  0.69.3-1g13ab89fe3
+#
+#   Line 1: 13ab89fe3
+#   Line 2: v0.69.3-1
+#   Line 3: v0-latest v0.69-latest
+
 url_prefix="${1}"
 dist="${2}"
 arch="${3}"
+test="${4}"
 
 if [[ "${dist}" == "centos-8" ]]; then
     dist="epel-8"
@@ -12,13 +34,20 @@ fi
 
 # Ensure we only consider the pbench-agent RPM's version string from the
 # target repo.
-version_string="$(yum list -q --repofrompath pbench,"${url_prefix}/pbench/${dist}-${arch}" pbench-agent.noarch 2>/dev/null | awk 'FNR==2{print $2}')"
+url="${url_prefix}/pbench${test}/${dist}-${arch}"
+version_string="$(yum list -q --repofrompath pbench,"${url}" pbench-agent.noarch 2>/dev/null | awk 'FNR==2{print $2}')"
 if [[ -z "${version_string}" ]]; then
-    printf -- "Failed to fetch pbench-agent.noarch version string from '%s/pbench/%s-%s'\n" "${url_prefix}" "${dist}" "${arch}" >&2
+    printf -- "Failed to fetch pbench-agent.noarch version string from '%s'\n" "${url}" >&2
     exit 1
 fi
 
-# 0.69.3-1
+# Expected tag format (example):
+# version_string = "0.69.3-1g13ab89fe3"
+# ver =            "0.69.3-1"
+# major =          "0"
+# major_minor =    "0.69"
+# commit_id =      "13ab89fe3"
+
 ver="${version_string%g*}"
 major="${ver%%.*}"
 major_minor="${ver%.*}"
