Ensure succ/fail exit status on unittests

diff --git a/agent/tool-scripts/postprocess/unittests b/agent/tool-scripts/postprocess/unittests
--- a/agent/tool-scripts/postprocess/unittests
+++ b/agent/tool-scripts/postprocess/unittests
@@ -32,11 +32,7 @@ function testit {
     rm /tmp/GenData/$1/$2.txt
 
     diff -cr gold/$1/ /tmp/GenData/$1
-    if [[ $? -eq 0 ]]; then
-        echo "PASS - $1"
-    else
-        echo "FAIL - $1"
-    fi
+    return $?
 }
 
 # Remove any file that is in the sample directory that
@@ -78,11 +74,7 @@ function testuperf {
     remove_sample_data $1
 
     diff -cr gold/$1/ /tmp/GenData/$1
-    if [[ $? -eq 0 ]]; then
-        echo "PASS - $1"
-    else
-        echo "FAIL - $1"
-    fi
+    return $?
 }
 
 # Test fio benchmark post-processing
@@ -98,11 +90,7 @@ function testfio {
     remove_sample_data $1
 
     diff -cr gold/$1/ /tmp/GenData/$1
-    if [[ $? -eq 0 ]]; then
-        echo "PASS - $1"
-    else
-        echo "FAIL - $1"
-    fi
+    return $?
 }
 
 function testcmpr {
@@ -119,13 +107,10 @@ function testcmpr {
     remove_sample_data $1
 
     diff -cr gold/$1/ /tmp/GenData/$1
-    if [[ $? -eq 0 ]]; then
-        echo "PASS - $1"
-    else
-        echo "FAIL - $1"
-    fi
+    return $?
 }
 
+res=0
 for i in $(ls -1 samples/) ; do
     if [[ ! -z "$testname" ]]; then
         if [[ "$testname" != "$i" ]]; then
@@ -134,15 +119,27 @@ for i in $(ls -1 samples/) ; do
     fi
     if [[ $i == uperf-? ]]; then
         testuperf $i
+        sts=$?
     else
         if [[ $i == fio-? ]]; then
             testfio $i
+            sts=$?
         else
             if [[ $i == compare-bench-results-* ]]; then
                 testcmpr $i
+                sts=$?
             else
                 testit $i ${i%-[0-9]}
+                sts=$?
             fi
         fi
     fi
+    if [[ $sts -eq 0 ]]; then
+        echo "PASS - $i"
+    else
+        echo "FAIL - $i"
+    fi
+    let res=$res+$sts
 done
+
+exit $res
