pbench-trafficgen: add trex support and other options updates
-new prereq checks
-device setup
-install lua-trafficgen
-install trex
-start trex server

diff --git a/agent/bench-scripts/pbench-trafficgen b/agent/bench-scripts/pbench-trafficgen
--- a/agent/bench-scripts/pbench-trafficgen
+++ b/agent/bench-scripts/pbench-trafficgen
@@ -24,19 +24,10 @@ pbench_cmd="$@"
 script_path=`dirname $0`
 script_name=`basename $0`
 pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+benchmark_name="trafficgen"
 
 # source the base script
 . "$pbench_bin"/base
-
-benchmark_name="trafficgen"
-if [ -z "$trafficgen_dir" ]; then
-	trafficgen_dir="/root/lua-trafficgen/MoonGen"
-fi
-if [ ! -d "$trafficgen_dir" ]; then
-	error_log "The MoonGen directory, $trafficgen_dir, does not exist as a directory"
-	exit 1
-fi
-benchmark_bin=/usr/local/bin/$benchmark_name
 
 # Every bench-script follows a similar sequence:
 # 1) process bench script arguments
@@ -49,10 +40,14 @@ benchmark_bin=/usr/local/bin/$benchmark_name
 
 # Defaults
 traffic_engine="trex-txrx" # can be either trex-txrx or moongen-txrx
+trex_ver="v2.23"
+trex_url=http://trex-tgn.cisco.com/trex/release/${trex_ver}.tar.gz
 benchmark_run_dir=""
 test_types="throughput-latency"
 traffic_directions="bidirec"
-max_drop_pcts="0"
+max_drop_pcts="0.002"
+nr_flows="1024"
+nr_samples=1
 rates=""
 devices="" # the network devices as PCI location IDs, like "0000:04:00.0,0000:04:00.1"
 dst_ips=""
@@ -65,8 +60,6 @@ encap_dst_macs=""
 encap_src_macs=""
 frame_sizes="64" # size in bytes of the Ethernet frame inccluding CRC
 config=""
-nr_flows="1024"
-nr_samples=5
 maxstddevpct=5 # maximum allowable standard deviation in percent
 max_failures=6 # after N failed attempts to hit below $maxstddevpct, move on to the nest test
 search_runtime=60
@@ -490,6 +483,103 @@ while true; do
 		;;
 	esac
 done
+
+# Before running any tests, the following must be satisfied:
+# -IOMMU must be enabled
+if cat /proc/cmdline | grep -q iommu; then
+	echo "found IOMMU option, continuing"
+else
+	warn_log "could not find IOMMU option in /proc/cmdline, exiting"
+	exit 1
+fi
+# -dpdk-tools package must be installed
+if check_install_rpm dpdk-tools; then
+	echo "found dpdk-tools, continuing"
+else
+	warn_log "could not find dpdk-tools, exiting"
+	exit 1
+fi
+# -PCI devices bound to vfio-pci
+if [ -z "$devices" ]; then
+	warn_log "no devices were provided (--devices), exiting"
+	exit 1
+fi
+for dev in `echo $devices | sed -e s/,/" "/g`; do
+	echo "configuring device $dev"
+	if /bin/ls /sys/module/vfio_pci/drivers/pci\:vfio-pci/ | grep -q "$dev"; then
+		echo "device $dev already bound to vfio-pci"
+	else
+		if dpdk-devbind -u $dev; then
+			dpdk-devbind -b vfio-pci $dev
+		else
+			log_warn "could not unbind device"
+			exit 1
+		fi
+	fi
+done
+# -trafficgen-engine installed/ready
+if [ -d /opt/lua-trafficgen ]; then
+	if pushd /opt/lua-trafficgen && git pull && git checkout master; then
+		echo "lua-trafficgen is up to date"
+		popd
+	else
+		warn_log "could not get latest lua-trafficgen"
+		exit 1
+	fi
+else
+	if pushd /opt && git clone https://github.com/atheurer/lua-trafficgen.git; then
+		echo "lua-trafficgen is up to date"
+		popd
+	else
+		warn_log "could not get latest lua-trafficgen"
+		exit 1
+	fi
+fi
+	
+if [ $traffic_engine == "trex-txrx" ]; then
+	# kill any existing trex server process
+	trex_pids=`netstat -tlnp | grep -E :4500\|:4501 | awk '{print $7}' | awk -F/ '{print $1}' | sort | uniq`
+	if [ ! -z "$trex_pids" ]; then
+		echo "killing existing trex server"
+		kill $trex_pids
+		sleep 5
+	fi
+	if [ -d /opt/trex/$trex_ver ]; then
+		echo "TRex $trex_ver already installed"
+	else
+		mkdir -p /opt/trex
+		pushd /opt/trex
+		tarfile="/tmp/${trex_ver}.tar.gz"
+		/bin/rm -f $tarfile
+		if wget -O $tarfile $trex_url &&\
+		   tar zxf $tarfile; then
+			popd
+			/bin/rm $tarfile
+			echo "installed TRex from $trex_url"
+		else
+			warn_log "could not install TRex $trex_ver, exiting"
+			exit 1
+		fi
+	fi
+	# start the trex server
+	pushd /opt/trex/$trex_ver
+	screen -dmS trex-server ./t-rex-64 -i -c 12 --checksum-offload
+	popd
+	# wait for trex server to be ready
+	count=30
+	num_ports=0
+	while [ $count -gt 0 -a $num_ports -lt 2 ]; do
+		sleep 1
+		num_ports=`netstat -tln | grep -E :4500\|:4501 | wc -l`
+		((count--))
+	done
+	if [ $num_ports -eq 2 ]; then
+		echo "trex-server is ready"
+	else
+		warn_log "trex-server could not start properly.  check \'screen -x trex-server\'"
+	fi
+fi
+
 if [[ -z "$benchmark_run_dir" ]]; then
 	# We don't have an explicit run directory, construct one
 	benchmark_fullname="${benchmark_name}_${config}_${date}"
@@ -509,7 +599,7 @@ echo "$script_name $pbench_cmd" >$benchmark_run_dir/$script_name.cmd
 chmod +x $benchmark_run_dir/$script_name.cmd
 
 total_iterations=0
-for traffic_direction in `echo $traffic | sed -e s/,/" "/g`; do
+for traffic_direction in `echo $traffic_directions | sed -e s/,/" "/g`; do
 	for max_drop_pct in `echo $max_drop_pcts | sed -e s/,/" "/g`; do
 		for frame_size in `echo $frame_sizes | sed -e s/,/" "/g`; do
 			for nr_flow in `echo $nr_flows | sed -e s/,/" "/g`; do
@@ -523,14 +613,14 @@ count=1
 mkdir -p $benchmark_run_dir/.running
 export benchmark_name config
 pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
-# start the server processes
+
 if [ -z "$rates" ]; then
 	# a rate of "none" is valid if this is a throuhgput test.  The opnfv-vsperf.lua
 	# script will start with line-rate for the binary search
 	rates="none"
 fi
 for rate in `echo $rates | sed -e s/,/" "/g`; do
-	for traffic_direction in `echo $traffic | sed -e s/,/" "/g`; do
+	for traffic_direction in `echo $traffic_directions | sed -e s/,/" "/g`; do
 		for max_drop_pct in `echo $max_drop_pcts | sed -e s/,/" "/g`; do
 			for frame_size in `echo $frame_sizes | sed -e s/,/" "/g`; do
 				for nr_flow in `echo $nr_flows | sed -e s/,/" "/g`; do
@@ -552,50 +642,9 @@ for rate in `echo $rates | sed -e s/,/" "/g`; do
 								log "Restarting iteration[$iteration] ($count of $total_iterations)"
 							fi
 							mkdir -p $iteration_dir
-							if [ "$postprocess_only" != "y" ]; then
-								if [ $traffic_direction == "unidirec" ]; then
-									bidirec_opt=false
-								else
-									bidirec_opt=true
-								fi
-								cfg_file="$iteration_dir/opnfv-vsperf-cfg.lua"
-								echo "VSPERF {" >$cfg_file
-								if [ "$rate" != "none" ]; then
-        								echo "startRate = $rate," >>$cfg_file
-								fi
-        							echo "nrFlows = $nr_flow," >>$cfg_file
-        							echo "testType = \"$test_type\"," >>$cfg_file
-        							echo "runBidirec = $bidirec_opt," >>$cfg_file
-								if [ "$test_type" == "latency" ]; then
-									echo "latencyRunTime = $latency_runtime,">>$cfg_file
-								else
-        								echo "searchRunTime = $search_runtime,">>$cfg_file
-        								echo "validationRunTime = $validation_runtime,">> $cfg_file
-        								echo "acceptableLossPct = $max_drop_pct," >>$cfg_file
-									if [ "$one_shot" == "y" ]; then
-										echo "oneShot = true," >>$cfg_file
-									fi
-								fi
-								if [ "$accept_negative_loss" == "y" ]; then
-									echo "negativeLossRetry = false," >>$cfg_file
-								fi
-        							echo "frameSize = $frame_size,">>$cfg_file
-								echo "mppsPerQueue = $mpps_per_queue," >>$cfg_file
-								echo "queuesPerTask = $queues_per_task," >>$cfg_file
-								if [ -n "$dst_maclist" ]; then
-									echo -n "dstMacs = {">>$cfg_file
-									for mac in `echo $dst_maclist | sed -e s/,/" "/g`; do
-										echo -n "\"$mac\",">>$cfg_file
-									done
-									echo "},">>$cfg_file
-								fi
-        							echo "ports = {$portlist}" >>$cfg_file
-								echo "}">>$cfg_file
-								cp $cfg_file $trafficgen_dir/
-								if [ "$test_type" == "throughput" ]; then
-									rm $cfg_file
-								fi
-							fi
+							#if [ "$postprocess_only" != "y" ]; then
+							# construct the command for binary-search.py program
+							#
 							# each attempt at a test config requires multiple samples to get stddev
 							for sample in `seq 1 $nr_samples`; do
 								benchmark_results_dir="$iteration_dir/sample$sample"
@@ -607,20 +656,15 @@ for rate in `echo $rates | sed -e s/,/" "/g`; do
 									result_file=$benchmark_results_dir/trafficgen-result.txt
 									# save benchmark command in file for debugging or running manually
 
-									echo "pushd >/dev/null $trafficgen_dir" >$benchmark_client_cmd_file
-									echo "./build/MoonGen /root/lua-trafficgen/trafficgen.lua" >>$benchmark_client_cmd_file
-									echo "popd >/dev/null" >>$benchmark_client_cmd_file
+									#echo "pushd >/dev/null $trafficgen_dir" >$benchmark_client_cmd_file
+									#echo "./build/MoonGen /root/lua-trafficgen/trafficgen.lua" >>$benchmark_client_cmd_file
+									#echo "popd >/dev/null" >>$benchmark_client_cmd_file
 									chmod +x $benchmark_client_cmd_file
 
-									rm -f $trafficgen_dir/latency*.csv 2> /dev/null
-									pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-									$benchmark_client_cmd_file 2>&1 | tee $result_file
-									pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-									pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-									if [ "$test_type" == "latency" -o "$test_type" == "throughput-latency" ]; then
-									    cp $trafficgen_dir/latency*.csv $benchmark_results_dir
-									    xz $benchmark_results_dir/latency:samples*.csv
-									fi
+									#pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									#$benchmark_client_cmd_file 2>&1 | tee $result_file
+									#pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									#pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
 								else
 									if [[ ! -d $benchmark_results_dir ]]; then
 										error_log "Results directory $benchmark_results_dir does not exist, skipping post-processing"
@@ -629,14 +673,15 @@ for rate in `echo $rates | sed -e s/,/" "/g`; do
 									echo "Not going to run $benchmark_name.  Only postprocesing existing data"
 									log "Not going to run $benchmnark_name.  Only postprocesing existing data"
 								fi
-								echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $test_type $tool_label_pattern $tool_group" >"$benchmark_results_dir/$benchmark_name-postprocess.cmd"
-								chmod +x "$benchmark_results_dir/$benchmark_name-postprocess.cmd"
-								$benchmark_results_dir/$benchmark_name-postprocess.cmd
+								#echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $test_type $tool_label_pattern $tool_group" >"$benchmark_results_dir/$benchmark_name-postprocess.cmd"
+								#chmod +x "$benchmark_results_dir/$benchmark_name-postprocess.cmd"
+								#$benchmark_results_dir/$benchmark_name-postprocess.cmd
 							done
 							echo "$script_path/postprocess/process-iteration-samples $iteration_dir Mframes_sec $maxstddevpct $failures $max_failures $tar_nonref_data $keep_failed_tool_data" >"$iteration_dir/process-iteration-samples.cmd"
-							chmod +x "$iteration_dir/process-iteration-samples.cmd"
-							$iteration_dir/process-iteration-samples.cmd
-							fail=$?
+							#chmod +x "$iteration_dir/process-iteration-samples.cmd"
+							#$iteration_dir/process-iteration-samples.cmd
+							#fail=$?
+							fail=0
 							if [ $fail -eq 1 ]; then
 								error_log "This test iteration failed"
 								((failures++))
