Add support to moongen to collect the info requested
- By default collect-sysinfo collects kernel_config, block, libvirt, sos
  , block and ara if installed and configured. This commit will allow
  users to choose whether to collect sysinfo or not. This also adds
  ability to pass the info to be collected as comma separated values
  when starting a benchmark run.
- Wrap moongen usage info in a function, add help option.

diff --git a/agent/bench-scripts/pbench-moongen b/agent/bench-scripts/pbench-moongen
--- a/agent/bench-scripts/pbench-moongen
+++ b/agent/bench-scripts/pbench-moongen
@@ -72,55 +72,62 @@ tool_label_pattern="$benchmark_name-"
 install_only="n"
 one_shot="n"
 accept_negative_loss="n"
+sysinfo=default
+
+function moongen_usage {
+	  printf "\tThe following options are available:\n\n"
+        #              1   2         3         4         5         6         7         8         9         0         1         2         3
+        #              678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012
+        printf -- "\t\t-c str       --config=str               name of the test config (i.e. jumbo_frames_and_network_throughput)\n"
+        printf -- "\t\t-r float     --rate[s]                  list of rates in millions of packets/sec (multiple rates can be used for latency tests)\n"
+        printf -- "\t\t             --portlist=int,int[,int,int]  list of DPDK ports to use (multiples of 2)\n"
+        printf -- "\t\t-t str[,str] --test-type=str            throughput, latency, or throughput-latency (default $test_type)\n"
+        printf -- "\t\t                                        throuhgput: find max throuhgput with a binary search\n"
+        printf -- "\t\t                                        latency: find latency (histogram) at a specified packet rate\n"
+        printf -- "\t\t                                        throughput-latency: first find max throuhgput with a binary search, then\n"
+        printf -- "\t\t                                                            find latency (histogram) at the max throughput\n"
+        printf -- "\t\t-o           --one-shot                 only run one test for throughput and then quit (no binary search)\n"
+        printf -- "\t\t             --accept-negative-loss     allow attempts with negative packet loss to pass\n"
+        printf -- "\t\t-t str[,str] --traffic=str[,str]        list of one or more: unidirec or bidirec (default $traffic)\n"
+        printf -- "\t\t-r int       --latency-runtime=int      test measurement period in seconds when running a latency test (default is $latency_runtime)\n"
+        printf -- "\t\t-r int       --search-runtime=int       test measurement period in seconds when searching for max throughput (default is $search_runtime)\n"
+        printf -- "\t\t-r int       --validation-runtime=int   test measurement period in seconds when running final validation (default is $validation_runtime)\n"
+        printf -- "\t\t             --max-drop-pct[s]=fl,[fl]  list of maximum allowed percentage of dropped frames (default is $max_drop_pcts)\n"
+        printf -- "\t\t-m int[,int] --frame-sizes=str[,str]    list of frame sizes in bytes (default is $frame_sizes)\n"
+        printf -- "\t\t-i int[,int] --nr-flows=int[,int]       list of number of packet flows to run (default is $nr_flows)\n"
+        printf -- "\t\t             --samples=int              the number of times each different test is run (to compute average &\n"
+        printf    "\t\t                                        standard deviations)\n"
+        printf -- "\t\t             --max-failures=int         the maximm number of failures to get below stddev\n"
+        printf -- "\t\t             --max-stddev=int           the maximm percent stddev allowed to pass\n"
+        printf -- "\t\t             --postprocess-only=y|n     don't run the benchmark, but postprocess data from previous test\n"
+        printf -- "\t\t             --run-dir=str              optionally specify what directory should be used (usually only used\n"
+        printf    "\t\t                                        if postprocess-only=y)\n"
+        printf -- "\t\t             --start-iteration-num=int  optionally skip the first (n-1) tests\n"
+        printf -- "\t\t             --tool-label-pattern=str   $benchmark_name will provide CPU and efficiency information for any tool directory\n"
+        printf    "\t\t                                        with a \"^<pattern>\" in the name, provided \"sar\" is one of the\n"
+        printf    "\t\t                                        registered tools.\n"
+        printf    "\t\t                                        a default pattern, \"$bechmark_name-\" is used if none is provided.\n"
+        printf    "\t\t                                        simply register your tools with \"--label=$benchmark_name-\$X\", and this script\n"
+        printf    "\t\t                                        will genrate CPU_$benchmark_name-\$X and Gbps/CPU_$benchmark_name-\$X or\n"
+        printf    "\t\t                                        trans_sec/CPU-$benchmark_name-\$X for all tools which have that pattern as a\n"
+        printf    "\t\t                                        prefix.  if you don't want to register your tools with \"$benchmark_name-\" as\n"
+        printf    "\t\t                                        part of the label, just use --tool-label-pattern= to tell this script\n"
+        printf    "\t\t                                        the prefix pattern to use for CPU information.\n"
+        printf -- "\t\t             --tool-group=str\n"
+        printf -- "\t\t             --mpps-per-queue=int       how many millions of packets to process per queue (default $mpps_per_queue)\n"
+        printf -- "\t\t             --queues-per-task=int      how many tasks queues to bind to each task (default $queues_per_task)\n"
+        printf -- "\t\t             --dst-macs=mac[,mac]       list of destination mac addresses, each mac in the list corresponds to a port from the port list\n"
+	printf -- "\t\t             --sysinfo=str,             str= comma separated values of system information to be collected\n"
+	printf -- "\t\t                                              available: $(pbench-collect-sysinfo --options)\n"
+}
 
 # Process options and arguments
-opts=$(getopt -q -o i:c:t:r:m:p:M:S:C:o --longoptions "portlist:,rate:,rates:,max-drop-pct:,max-drop-pcts:,client-label:,server-label:,tool-label-pattern:,install,start-iteration-num:,config:,nr-flows:,test-type:,traffic:,latency-runtime:,search-runtime:,validation-runtime:,frame-sizes:,samples:,client:,clients:,servers:,server:,max-stddev:,max-failures:,log-response-times:,postprocess-only:,run-dir:,tool-group:,one-shot,accept-negative-loss,mpps-per-queue:,queues-per-task:,dst-macs:" -n "getopt.sh" -- "$@")
+opts=$(getopt -q -o i:c:t:r:m:p:M:S:C:o --longoptions "help,portlist:,rate:,rates:,max-drop-pct:,max-drop-pcts:,client-label:,server-label:,tool-label-pattern:,install,start-iteration-num:,config:,nr-flows:,test-type:,traffic:,latency-runtime:,search-runtime:,validation-runtime:,frame-sizes:,samples:,client:,clients:,servers:,server:,max-stddev:,max-failures:,log-response-times:,postprocess-only:,run-dir:,tool-group:,one-shot,accept-negative-loss,mpps-per-queue:,queues-per-task:,dst-macs:,sysinfo:" -n "getopt.sh" -- "$@")
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
 	printf "\n"
 	printf "\t${benchmark_name}: you specified an invalid option\n\n"
-	printf "\tThe following options are available:\n\n"
-	#              1   2         3         4         5         6         7         8         9         0         1         2         3
-	#              678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012
-	printf -- "\t\t-c str       --config=str               name of the test config (i.e. jumbo_frames_and_network_throughput)\n"
-	printf -- "\t\t-r float     --rate[s]	               list of rates in millions of packets/sec (multiple rates can be used for latency tests)\n"
-	printf -- "\t\t             --portlist=int,int[,int,int]  list of DPDK ports to use (multiples of 2)\n"
-	printf -- "\t\t-t str[,str] --test-type=str            throughput, latency, or throughput-latency (default $test_type)\n"
-	printf -- "\t\t					       throuhgput: find max throuhgput with a binary search\n"
-	printf -- "\t\t					       latency: find latency (histogram) at a specified packet rate\n"
-	printf -- "\t\t					       throughput-latency: first find max throuhgput with a binary search, then\n"
-	printf -- "\t\t								   find latency (histogram) at the max throughput\n"
-	printf -- "\t\t-o	    --one-shot		       only run one test for throughput and then quit (no binary search)\n"
-	printf -- "\t\t             --accept-negative-loss     allow attempts with negative packet loss to pass\n"
-	printf -- "\t\t-t str[,str] --traffic=str[,str]        list of one or more: unidirec or bidirec (default $traffic)\n"
-	printf -- "\t\t-r int       --latency-runtime=int      test measurement period in seconds when running a latency test (default is $latency_runtime)\n"
-	printf -- "\t\t-r int       --search-runtime=int       test measurement period in seconds when searching for max throughput (default is $search_runtime)\n"
-	printf -- "\t\t-r int       --validation-runtime=int   test measurement period in seconds when running final validation (default is $validation_runtime)\n"
-	printf -- "\t\t             --max-drop-pct[s]=fl,[fl]  list of maximum allowed percentage of dropped frames (default is $max_drop_pcts)\n"
-	printf -- "\t\t-m int[,int] --frame-sizes=str[,str]    list of frame sizes in bytes (default is $frame_sizes)\n"
-	printf -- "\t\t-i int[,int] --nr-flows=int[,int]       list of number of packet flows to run (default is $nr_flows)\n"
-	printf -- "\t\t             --samples=int              the number of times each different test is run (to compute average &\n"
-	printf    "\t\t                                        standard deviations)\n"
-	printf -- "\t\t             --max-failures=int         the maximm number of failures to get below stddev\n"
-	printf -- "\t\t             --max-stddev=int           the maximm percent stddev allowed to pass\n"
-	printf -- "\t\t             --postprocess-only=y|n     don't run the benchmark, but postprocess data from previous test\n"
-	printf -- "\t\t             --run-dir=str              optionally specify what directory should be used (usually only used\n"
-	printf    "\t\t                                        if postprocess-only=y)\n"
-	printf -- "\t\t             --start-iteration-num=int  optionally skip the first (n-1) tests\n"
-	printf -- "\t\t             --tool-label-pattern=str   $benchmark_name will provide CPU and efficiency information for any tool directory\n"
-	printf    "\t\t                                        with a \"^<pattern>\" in the name, provided \"sar\" is one of the\n"
-	printf    "\t\t                                        registered tools.\n"
-	printf    "\t\t                                        a default pattern, \"$bechmark_name-\" is used if none is provided.\n"
-	printf    "\t\t                                        simply register your tools with \"--label=$benchmark_name-\$X\", and this script\n"
-	printf    "\t\t                                        will genrate CPU_$benchmark_name-\$X and Gbps/CPU_$benchmark_name-\$X or\n"
-	printf    "\t\t                                        trans_sec/CPU-$benchmark_name-\$X for all tools which have that pattern as a\n"
-	printf    "\t\t                                        prefix.  if you don't want to register your tools with \"$benchmark_name-\" as\n"
-	printf    "\t\t                                        part of the label, just use --tool-label-pattern= to tell this script\n"
-	printf    "\t\t                                        the prefix pattern to use for CPU information.\n"
-	printf -- "\t\t             --tool-group=str\n"
-	printf -- "\t\t             --mpps-per-queue=int       how many millions of packets to process per queue (default $mpps_per_queue)\n"
-	printf -- "\t\t             --queues-per-task=int      how many tasks queues to bind to each task (default $queues_per_task)\n"
-	printf -- "\t\t             --dst-macs=mac[,mac]       list of destination mac addresses, each mac in the list corresponds to a port from the port list\n"
+	moongen_usage
 	exit 1
 fi
 eval set -- "$opts"
@@ -130,6 +137,10 @@ while true; do
 		--install)
 		shift
 		install_only="y"
+		exit
+		;;
+		--help)
+		moongen_usage
 		exit
 		;;
 		--tool-label-pattern)
@@ -298,12 +309,26 @@ while true; do
 		    shift
 		fi
 		;;
+		 --sysinfo)
+		shift
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift
+		fi
+		;;
 		*)
 		error_log "[$script_name] bad option, \"$1 $2\""
 		break
 		;;
 	esac
 done
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+	moongen_usage
+	exit 1
+fi
 if [[ -z "$benchmark_run_dir" ]]; then
 	# We don't have an explicit run directory, construct one
 	benchmark_fullname="${benchmark_name}_${config}_${date_suffix}"
@@ -336,7 +361,7 @@ echo "Total number of benchmark iterations: $total_iterations"
 count=1
 mkdir -p $benchmark_run_dir/.running
 export benchmark_name config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 # start the server processes
 if [ -z "$rates" ]; then
@@ -482,5 +507,5 @@ done
 echo "$script_path/postprocess/generate-benchmark-summary $benchmark_name $orig_cmd $benchmark_run_dir" >"$benchmark_run_dir/generate-benchmark-summary.cmd"
 $script_path/postprocess/generate-benchmark-summary "$benchmark_name" "$orig_cmd" "$benchmark_run_dir"
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 rmdir $benchmark_run_dir/.running
