Fix pbench-tool-trigger to work as expected
We also fix pbench-specjbb2005 to use its new behavior, while enhancing
that benchmark to work in a non-destructive way by copying necessary
files into the benchmark run directory in /var/lib/pbench-agent.

We also enhance pbench-user-benchmark to accept a --use-tool-triggers
parameter that directs the script to properly invoke tool triggers
instead of traditional start/stop tools.

diff --git a/agent/bench-scripts/pbench-specjbb2005 b/agent/bench-scripts/pbench-specjbb2005
--- a/agent/bench-scripts/pbench-specjbb2005
+++ b/agent/bench-scripts/pbench-specjbb2005
@@ -33,39 +33,41 @@ benchmark="specjbb2005"
 
 # Defaults
 
-baseconfig="`uname -r`"
 runtime=30
 nr_jvms=1
 start_warehouses=1
 stop_warehouses="default"
 inc_warehouses=1
 peak_warehouses=2
-heap_size=4096 #in MB
+heap_size="4096m"
 nr_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
-classpath=/usr/local/share/specjbb2005
-tool_group=default
+specjbb2005_dir=/usr/local/share/specjbb2005
+tool_group="default"
 config=""
 sysinfo="default"
+java_opts=""
+dir=""
 
 # Process options and arguments
-opts=$(getopt -q -o C:c:r:d: --longoptions "dir:,nr-jvms:,heap-size:,java-opts:,start-warehouses:,inc-warehouses:,stop-warehouses:,runtime:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o C:c:r:d: --longoptions "dir:,nr-jvms:,heap-size:,java-opts:,start-warehouses:,inc-warehouses:,stop-warehouses:,runtime:,tool-group:,sysinfo:,specjbb2005-dir:" -n "getopt.sh" -- "$@");
 
 function usage {
 	printf "\tThe following options are available:\n\n"
-        printf -- "\t\t--kvm-host=str\n"
-        printf -- "\t\t-C str --config=str                         name of the test config\n"
-        printf -- "\t\t-j str --java_opts=str                      options passed directly to the JVM\n"
-        printf -- "\t\t       --nr-jvms=int|node                      number of JVMs. if = node, number of JVMs = number of NUMA nodes\n"
-        printf -- "\t\t       --node-pinning=y/n                   if y, this script will use numactl to pin JVM to a node (1 per node round-robin)\n"
-        printf -- "\t\t       --start-warehouses                   number of warehouses to start with (default is $start_warehouses)\n"
-        printf -- "\t\t       --inc-warehouses                     number of warehouses to increment by (default is $inc_warehouses)\n"
-        printf -- "\t\t       --stop-warehouses                    number of warehouses to stop with (default is nr_cpus * 2 / nr_jvms)\n"
-        printf -- "\t\t       --heap-size                          size of the heap in MB (default is $heap_size)\n"
-        printf -- "\t\t       --runtime=int                        measurement period in seconds (default is $runtime)\n"
-        printf -- "\t\t-d str --dir=str                            directory to run the test\n"
-        printf -- "\t\t       --tool-group=str\n"
-        printf -- "\t\t       --sysinfo=str,                       str= comma seperated values of sysinfo to be collected\n"
-        printf -- "\t\t                                                 available: $(pbench-collect-sysinfo --options)\n"
+	printf -- "\t\t-C str --config=<str>                       name of the test config\n"
+	printf -- "\t\t-j str --java_opts=<str>                    options passed directly to the JVM\n"
+	printf -- "\t\t       --nr-jvms=<int>|node                 number of JVMs. if = node, number of JVMs = number of NUMA nodes\n"
+	printf -- "\t\t       --node-pinning=y/n                   if y, this script will use numactl to pin JVM to a node (1 per node round-robin)\n"
+	printf -- "\t\t       --start-warehouses=<int>             number of warehouses to start with (default is $start_warehouses)\n"
+	printf -- "\t\t       --inc-warehouses=<int>               number of warehouses to increment by (default is $inc_warehouses)\n"
+	printf -- "\t\t       --stop-warehouses=<int>              number of warehouses to stop with (default is nr_cpus * 2 / nr_jvms)\n"
+	printf -- "\t\t       --heap-size=<str>                    size of the heap, java size spec (default is $heap_size)\n"
+	printf -- "\t\t       --runtime=<int>                      measurement period in seconds (default is $runtime)\n"
+	printf -- "\t\t-d str --dir=<str>                          directory to run the test\n"
+	printf -- "\t\t       --tool-group=<str>                   tool group to use during test\n"
+	printf -- "\t\t       --sysinfo=<str,>                     comma seperated values of sysinfo to be collected\n"
+	printf -- "\t\t                                                 available: $(pbench-collect-sysinfo --options)\n"
+	printf -- "\t\t       --specjbb2005-dir=<str>              the location of the install directory for SPECjbb2005\n"
+	printf -- "\t\t                                                 (default is $specjbb2005_dir)\n"
 }
 
 if [ $? -ne 0 ]; then
@@ -156,6 +158,13 @@ while true; do
 			shift;
 		fi
 		;;
+		--specjbb2005-dir)
+		shift;
+		if [ -n "$1" ]; then
+			specjbb2005_dir="$1"
+			shift;
+		fi
+		;;
 		h|--help)
 		usage
 		exit 0
@@ -170,87 +179,212 @@ while true; do
 		;;
 	esac
 done
+if [ ! -d "${specjbb2005_dir}" ]; then
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --specjbb2005-dir option (\"$specjbb2005_dir\")\n\n"
+	usage
+	exit 1
+fi
 verify_tool_group $tool_group
-
 pbench-collect-sysinfo --sysinfo=$sysinfo --check
 if [ $? != 0 ]; then
-        printf -- "$*\n\n"
-        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
-        usage
-        exit 1
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+	usage
+	exit 1
 fi
 
-if [ "$stop_warehouses" == "default" ]; then
-	stop_warehouses=`echo "$nr_cpus *2 /$nr_jvms" | bc`
+if [ "${nr_jvms}" == "node" ]; then
+	# Find out number of numa nodes
+	nr_jvms=$(ls -1d /sys/devices/system/node/node* | wc -l)
 fi
-## Ensure the right version of the benchmark is installed
+if [ "${nr_jvms}" -eq "${nr_jvms}" ] 2>/dev/null ; then
+	# Verify the value is an int
+	: 
+else
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --nr-jvms option (\"${nr_jvms}\")\n\n"
+	usage
+	exit 1
+fi
+if [ "${stop_warehouses}" == "default" ]; then
+	stop_warehouses=`echo "${nr_cpus} *2 /${nr_jvms}" | bc`
+fi
+if [ "${stop_warehouses}" -eq "${stop_warehouses}" ] 2>/dev/null ; then
+	# Verify the value is an int
+	:
+else
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --stop-warehouses option (\"${stop_warehouses}\")\n\n"
+	usage
+	exit 1
+fi
+if [ "${start_warehouses}" -eq "${start_warehouses}" ] 2>/dev/null ; then
+	# Verify the value is an int
+	:
+else
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --start-warehouses option (\"${start_warehouses}\")\n\n"
+	usage
+	exit 1
+fi
+if [ "${inc_warehouses}" -eq "${inc_warehouses}" ] 2>/dev/null ; then
+	# Verify the value is an int
+	:
+else
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --inc-warehouses option (\"${inc_warehouses}\")\n\n"
+	usage
+	exit 1
+fi
+if [ "${runtime}" -eq "${runtime}" ] 2>/dev/null ; then
+	# Verify the value is an int
+	:
+else
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --runtime option (\"${runtime}\")\n\n"
+	usage
+	exit 1
+fi
+if [ -d "${dir}" ]; then
+	if [ -d "${dir}/results" ]; then
+		printf -- "$*\n\n"
+		printf "\t${benchmark}: the --dir option has an unexpected results directory (\"${dir}/results\")\n\n"
+		usage
+		exit 1
+        fi
+	benchmark_run_dir="${dir}"
+elif [ -n "${dir}" ]; then
+	printf -- "$*\n\n"
+	printf "\t${benchmark}: you specified an invalid --dir option (\"${dir}\")\n\n"
+	usage
+	exit 1
+fi
 
 benchmark_fullname="${benchmark}_${config}_${date_suffix}"
 export benchmark_run_dir="$pbench_run/${benchmark_fullname}"
-benchmark_iterations="$pbench_tmp/${benchmark_fullname}.iterations"
-benchmark_summary_txt_file="$benchmark_run_dir/$benchmark-summary.txt"
-benchmark_summary_html_file="$benchmark_run_dir/$benchmark-summary.html"
-benchmark_results_dir="$benchmark_run_dir"
+benchmark_iterations="${benchmark_run_dir}/iterations.txt"
+export benchmark config
 
 mkdir -p $benchmark_run_dir/.running
+if [ $? -ne 0 ]; then
+	printf "\t${benchmark}: unable to setup run directory (\"${benchmark_run_dir}\")\n\n"
+	exit 1
+fi
 
 pbench-register-tool-trigger --group=$tool_group --start-trigger="Timing Measurement began" --stop-trigger="Timing Measurement ended"
 
-# run in the directory which has the jar and spec files
-pushd $classpath
-rm -rf ./results/*
-
-# edit the jbb properties file to match user's options
-sed -i -e s/"input.jvm_instances=.*"/"input.jvm_instances=$nr_jvms"/ SPECjbb.props
-sed -i -e s/"input.measurement_seconds=.*"/"input.measurement_seconds=$runtime"/ SPECjbb.props
-sed -i -e s/"input.starting_number_warehouses=.*"/"input.starting_number_warehouses=$start_warehouses"/ SPECjbb.props
-sed -i -e s/"input.increment_number_warehouses=.*"/"input.increment_number_warehouses=$inc_warehouses"/ SPECjbb.props
-sed -i -e s/"input.ending_number_warehouses=.*"/"input.ending_number_warehouses=$stop_warehouses"/ SPECjbb.props
-
-# start the controller
-java -cp jbb.jar:check.jar -Xms32m -Xmx32m spec.jbb.Controller -propfile SPECjbb.props & controller_pid=$!
-sleep 5
-
-iteration=1
-for i in `seq $nr_jvms -1 1`; do
-	if [ $i -eq 1 ]; then
-		# the last JVM gets output so we can trigger the tools
-		java -cp jbb.jar:check.jar -Xms4096m -Xmx4096m spec.jbb.JBBmain -propfile SPECjbb.props -id $i | tee $benchmark_results_dir/jvm-$i-worker.txt | tool-trigger "$iteration" "$benchmark_results_dir" "y"
-	else
-		java -cp jbb.jar:check.jar -Xms4096m -Xmx4096m spec.jbb.JBBmain -propfile SPECjbb.props -id $i > $benchmark_results_dir/jvm-$i-worker.txt &
-	fi
-done
-popd
-debug_log "worker JVMs have finished"
-debug_log "waiting for controller JVM to finish"
-kill $controller_pid
-debug_log "moving results to $benchmark_results_dir"
-if [ $nr_jvms -eq 1 ]; then
-	cp /usr/local/share/specjbb2005/results/SPECjbbSingleJVM/* $benchmark_results_dir
-else
-	cp /usr/local/share/specjbb2005/results/SPECjbbMultiJVM.001/* $benchmark_results_dir
-fi
-
-	
-pushd $benchmark_results_dir
-mv index.html SPECjbb.html
-
-# rename the iterations with warehouse count and then postprocess the tools
-iteration=1
-export benchmark config
+# Collect system information before we begin, and record the beginning.
 pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
+# on abnormal exit, make sure that the metadata log exists and is complete.
+trap "pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir int" INT QUIT
+
+# edit the jbb properties file to match user's options
+> ${benchmark_run_dir}/SPECjbb.props.sed
+printf "s/input.jvm_instances=.\*/input.jvm_instances=$nr_jvms/\n" >> ${benchmark_run_dir}/SPECjbb.props.sed
+printf "s/input.measurement_seconds=.\*/input.measurement_seconds=$runtime/\n" >> ${benchmark_run_dir}/SPECjbb.props.sed 
+printf "s/input.starting_number_warehouses=.\*/input.starting_number_warehouses=$start_warehouses/\n" >> ${benchmark_run_dir}/SPECjbb.props.sed 
+printf "s/input.increment_number_warehouses=.\*/input.increment_number_warehouses=$inc_warehouses/\n" >> ${benchmark_run_dir}/SPECjbb.props.sed 
+printf "s/input.ending_number_warehouses=.\*/input.ending_number_warehouses=$stop_warehouses/\n" >> ${benchmark_run_dir}/SPECjbb.props.sed 
+sed -f ${benchmark_run_dir}/SPECjbb.props.sed ${specjbb2005_dir}/SPECjbb.props > ${benchmark_run_dir}/SPECjbb.props
+if [ $? -ne 0 ]; then
+	printf "\t${benchmark}: unable to create the SPECjbb.props file (\"${benchmark_run_dir}/SPECjbb.props\")\n\n"
+	exit 1
+fi
+cp ${specjbb2005_dir}/SPECjbb_config.props ${benchmark_run_dir}/
+if [ $? -ne 0 ]; then
+	printf "\t${benchmark}: unable to copy SPECjbb_config.props file from \"${specjbb2005_dir}\"\n\n"
+	exit 1
+fi
+
+mkdir ${benchmark_run_dir}/results
+if [ $? -ne 0 ]; then
+	printf "\t${benchmark}: unable to create the results directory (\"${benchmark_run_dir}/results\")\n\n"
+	exit 1
+fi
+
+ln -s ${specjbb2005_dir}/xml ${benchmark_run_dir}/
+if [ $? -ne 0 ]; then
+	printf "\t${benchmark}: unable to create the xml directory link (\"ln -s ${specjbb2005_dir}/xml ${benchmark_run_dir}/\")\n\n"
+	exit 1
+fi
+
+# We execute from the benchmark run directory instead of the SPECjbb2005 directory.
+pushd ${benchmark_run_dir} > /dev/null 2>&1
+
+specjbb_cp="${specjbb2005_dir}/jbb.jar:${specjbb2005_dir}/check.jar"
+
+# start the controller
+java -cp ${specjbb_cp} -Xms32m -Xmx32m ${java_opts} spec.jbb.Controller -propfile ${benchmark_run_dir}/SPECjbb.props &
+controller_pid=$!
+if [ "x$controller_pid" = "x" ]; then
+	printf "\t${benchmark}: unable to start the java controller\n\n"
+	exit 1
+fi
+
+sleep 5
+
+specjbb_opts="-cp ${specjbb_cp} -Xms${heap_size} -Xmx${heap_size} ${java_opts} spec.jbb.JBBmain -propfile ${benchmark_run_dir}/SPECjbb.props"
+for i in `seq $nr_jvms -1 1`; do
+	if [ $i -eq 1 ]; then
+		# the last JVM gets output so we can trigger the tools starting at iteration 1
+		java ${specjbb_opts} -id $i | tee ./jvm-$i-worker.txt | pbench-tool-trigger 1 "${benchmark_run_dir}" "${tool_group}"
+	else
+		java ${specjbb_opts} -id $i >     ./jvm-$i-worker.txt &
+	fi
+done
+
+debug_log "worker JVMs have finished"
+debug_log "waiting for controller JVM to finish"
+kill $controller_pid > /dev/null 2>&1
+wait $controller_pid
+
+if [ $nr_jvms -eq 1 ]; then
+	specjbb_results="results/SPECjbbSingleJVM"
+else
+	specjbb_results="results/SPECjbbMultiJVM.001"
+fi
+
+# Function to add data to metadata.log
+function record_iteration {
+        local iteration=$1
+        local iteration_name=$2
+        local benchmark_bin=$3
+
+        echo ${iteration_name} >> ${benchmark_iterations}
+        echo ${iteration_name} | pbench-add-metalog-option ${mdlog} iterations/${iteration} iteration_name
+        echo ${benchmark_bin} | pbench-add-metalog-option ${mdlog} iterations/${iteration} user_script
+}
+
+# rename the iterations with warehouse count and then postprocess the tools
+> ${benchmark_iterations}
+iteration=1
 for i in `seq $start_warehouses $inc_warehouses $stop_warehouses`; do
-	# for each of the test iterations (each test with a specific number of warehouses), copy the raw result data for that iteration in iteraration directory
-	grep "test$i" SPECjbb.raw >$i/reference-result/SPECjbb.raw
-	new_iteration_name="$iteration-warehouses:$i"
-        echo $new_iteration_name >> $benchmark_iterations
-	mv $iteration $new_iteration_name
-	pbench-postprocess-tools --group=$tool_group --iteration=$new_iteration_name --dir=$benchmark_results_dir/$new_iteration_name/reference-result
+	if [ ! -d ${iteration}/reference-result ]; then
+		error_log "missing iteration directory ${benchmark_run_dir}/${iteration}/reference-result"
+		let iteration=$iteration+1
+		continue
+	fi
+	# for each of the test iterations (each test with a specific number of warehouses), copy the raw result data for that iteration in the iteration directory
+	grep "test${i}" ${specjbb_results}/SPECjbb.001.raw > ${iteration}/reference-result/SPECjbb.raw
+	if [ $? -ne 0 ]; then
+		error_log "missing test${i} raw results in ${specjbb_results}/SPECjbb.raw"
+	fi
+	new_iteration_name="${iteration}-warehouses:${i}"
+	mv ${iteration} ${new_iteration_name}
+	if [ $? -ne 0 ]; then
+		error_log "unable to move ${iteration} directory hierarchy to ${new_iteration_name}, skipping post-processing"
+	else
+		record_iteration ${iteration} ${new_iteration_name} ${benchmark}
+		pbench-postprocess-tools --group=${tool_group} --iteration=${new_iteration_name} --dir=${benchmark_run_dir}/${new_iteration_name}/reference-result
+	fi
 	let iteration=$iteration+1
 done
+
+popd > /dev/null 2>&1
+
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
 pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
-popd
 
 rmdir $benchmark_run_dir/.running
diff --git a/agent/util-scripts/pbench-register-tool-trigger b/agent/util-scripts/pbench-register-tool-trigger
--- a/agent/util-scripts/pbench-register-tool-trigger
+++ b/agent/util-scripts/pbench-register-tool-trigger
@@ -14,6 +14,8 @@ pbench_bin="`cd ${script_path}/..; /bin/pwd`"
 
 # Defaults
 group=default
+start_trigger=""
+stop_trigger=""
 
 function usage() {
 	printf "usage:\n"
@@ -27,8 +29,6 @@ if [ $? -ne 0 ]; then
 	printf "%s\n" $*
 	printf "$script_name: you specified an invalid option\n\n"
 	usage
-
-
 	exit 1
 fi
 eval set -- "$opts";
@@ -69,13 +69,21 @@ while true; do
 	esac
 done
 
+if [ "$start_trigger" != "${start_trigger%%:*}" ]; then
+	printf "$script_name: the start trigger cannot have a colon in it: \"${start_trigger}\"\n"
+	exit 1
+fi
+if [ "$stop_trigger" != "${stop_trigger%%:*}" ]; then
+	printf "$script_name: the stop trigger cannot have a colon in it: \"${stop_trigger}\"\n"
+	exit 1
+fi
+
 if [ ! -f "$pbench_run/tool-triggers" ]; then
 	mkdir -p "$pbench_run"
-	echo "#group:start-trigger:stop-trigger" >"$pbench_run/tool-triggers"
+	echo "#group:start-trigger:stop-trigger" > "$pbench_run/tool-triggers"
 fi
-# remove any previous trigger
+# remove any previous trigger for the given group
 sed -i /^$group.*/d "$pbench_run/tool-triggers"
-# remeber this trigger
-printf "%s:%s:%s\n" "$group" "$start_trigger" "$stop_trigger" >>"$pbench_run/tool-triggers"
+# remember this trigger
+printf "%s:%s:%s\n" "$group" "$start_trigger" "$stop_trigger" >> "$pbench_run/tool-triggers"
 printf "tool trigger strings for start: \"$start_trigger\" and for stop: \"$stop_trigger\" are now registered for tool group: $group\n"
-
