pbench-trafficgen: fix postprocess-only and add postprocess script

diff --git a/agent/bench-scripts/pbench-trafficgen b/agent/bench-scripts/pbench-trafficgen
--- a/agent/bench-scripts/pbench-trafficgen
+++ b/agent/bench-scripts/pbench-trafficgen
@@ -641,39 +641,37 @@ for rate in `echo $rates | sed -e s/,/" "/g`; do
 								echo "Restarting iteration[$iteration] ($count of $total_iterations)"
 								log "Restarting iteration[$iteration] ($count of $total_iterations)"
 							fi
-							if [ "$postprocess_only" != "y" ]; then
-								# each attempt at a test config requires multiple samples to get stddev
-								for sample in `seq 1 $num_samples`; do
-									benchmark_results_dir="$iteration_dir/sample$sample"
-									if [ "$postprocess_only" != "y" ]; then
-										mkdir -p $benchmark_results_dir
-										echo "test sample $sample of $num_samples"
-										log "test sample $sample of $num_samples "
-										result_file=$benchmark_results_dir/result.txt
-	
-	
-										pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-										$benchmark_cmd_file | tee $result_file
-										pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-										pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-									else
-										if [[ ! -d $benchmark_results_dir ]]; then
-											error_log "Results directory $benchmark_results_dir does not exist, skipping post-processing"
-											continue
-										fi
-										echo "Not going to run $benchmark_name.  Only postprocesing existing data"
-										log "Not going to run $benchmnark_name.  Only postprocesing existing data"
+							# each attempt at a test config requires multiple samples to get stddev
+							for sample in `seq 1 $num_samples`; do
+								benchmark_results_dir="$iteration_dir/sample$sample"
+								if [ "$postprocess_only" != "y" ]; then
+									mkdir -p $benchmark_results_dir
+									echo "test sample $sample of $num_samples"
+									log "test sample $sample of $num_samples "
+									result_file=$benchmark_results_dir/result.txt
+
+
+									pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									$benchmark_cmd_file | tee $result_file
+									pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+								else
+									if [[ ! -d $benchmark_results_dir ]]; then
+										error_log "Results directory $benchmark_results_dir does not exist, skipping post-processing"
+										continue
 									fi
-									#echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $test_type $tool_label_pattern $tool_group" >"$benchmark_results_dir/$benchmark_name-postprocess.cmd"
-									#chmod +x "$benchmark_results_dir/$benchmark_name-postprocess.cmd"
-									#$benchmark_results_dir/$benchmark_name-postprocess.cmd
-								done
-							fi 
+									echo "Not going to run $benchmark_name.  Only postprocesing existing data"
+									log "Not going to run $benchmnark_name.  Only postprocesing existing data"
+								fi
+								echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $max_loss_pct $tool_label_pattern $tool_group" >"$benchmark_results_dir/$benchmark_name-postprocess.cmd"
+								chmod +x "$benchmark_results_dir/$benchmark_name-postprocess.cmd"
+								$benchmark_results_dir/$benchmark_name-postprocess.cmd
+							done
 							echo "$script_path/postprocess/process-iteration-samples $iteration_dir Mframes_sec $maxstddevpct $failures $max_failures $tar_nonref_data $keep_failed_tool_data" >"$iteration_dir/process-iteration-samples.cmd"
-							#chmod +x "$iteration_dir/process-iteration-samples.cmd"
-							#$iteration_dir/process-iteration-samples.cmd
-							#fail=$?
-							fail=0
+							chmod +x "$iteration_dir/process-iteration-samples.cmd"
+							$iteration_dir/process-iteration-samples.cmd
+							fail=$?
+							#fail=0
 							if [ $fail -eq 1 ]; then
 								error_log "This test iteration failed"
 								((failures++))
