Moved vars checking before it is being referenced
Signed-off-by: T K Sourab <tsourab@redhat.com>

diff --git a/server/bin/pbench-remote-sync-package-tarballs b/server/bin/pbench-remote-sync-package-tarballs
--- a/server/bin/pbench-remote-sync-package-tarballs
+++ b/server/bin/pbench-remote-sync-package-tarballs
@@ -15,6 +15,12 @@ case $opts in
         PROG=$(basename $0)
         ;;
 esac
+
+if [[ -z "${dir}" || -z "${PROG}" ]]; then
+    echo "INTERNAL ERROR: bad environment encountered" >&2
+    exit 1
+fi
+
 case $# in
     2)
         :
@@ -25,10 +31,6 @@ case $# in
         ;;
 esac
 
-if [[ -z "${dir}" || -z "${PROG}" ]]; then
-    echo "INTERNAL ERROR: bad environment encountered" >&2
-    exit 1
-fi
 
 satellite_config=$1
 output_tar_ball=$2
diff --git a/server/bin/pbench-server-set-result-state b/server/bin/pbench-server-set-result-state
--- a/server/bin/pbench-server-set-result-state
+++ b/server/bin/pbench-server-set-result-state
@@ -13,6 +13,12 @@ case $opts in
         PROG=$(basename $0)
         ;;
 esac
+
+if [[ -z "${dir}" || -z "${PROG}" ]]; then
+    echo "INTERNAL ERROR: bad environment encountered" >&2
+    exit 1
+fi
+
 case $# in
     2)
         :
@@ -23,10 +29,6 @@ case $# in
         ;;
 esac
 
-if [[ -z "${dir}" || -z "${PROG}" ]]; then
-    echo "INTERNAL ERROR: bad environment encountered" >&2
-    exit 1
-fi
 
 export CONFIG=/opt/pbench-server/lib/config/pbench-server.cfg
 
