- Assert dir and PROG vars - Add usage case
Signed-off-by: T K Sourab <tsourab@redhat.com>

diff --git a/server/bin/pbench-server-set-result-state b/server/bin/pbench-server-set-result-state
--- a/server/bin/pbench-server-set-result-state
+++ b/server/bin/pbench-server-set-result-state
@@ -13,6 +13,20 @@ case $opts in
         PROG=$(basename $0)
         ;;
 esac
+case $# in
+    2)
+        :
+        ;;
+    *)
+        echo "Usage: $PROG <satellite-config> <output-tar-ball>" >&2
+        exit 1
+        ;;
+esac
+
+if [[ -z "${dir}" || -z "${PROG}" ]]; then
+    echo "INTERNAL ERROR: bad environment encountered" >&2
+    exit 1
+fi
 
 export CONFIG=/opt/pbench-server/lib/config/pbench-server.cfg
 
