Change `Logic bomb` to `Logic error` (#3039)
* Change `Logic bomb` to `Logic error`

* Add a few more noticed by an alert reviewer

diff --git a/server/bin/unittests b/server/bin/unittests
--- a/server/bin/unittests
+++ b/server/bin/unittests
@@ -334,7 +334,7 @@ let failures=0
 for testname in ${tests}; do
     cmd=${cmds[${testname}]}
     if [[ -z "${cmd}" ]]; then
-        printf -- "Unknown test - Logic bomb!: \"%s\"\n" "${testname}" >&2
+        printf -- "Unknown test - Logic error!: \"%s\"\n" "${testname}" >&2
         continue
     fi
     let count=count+1
