Backport improved ssh error handling (from PR #2427)

diff --git a/agent/util-scripts/pbench-move-results b/agent/util-scripts/pbench-move-results
--- a/agent/util-scripts/pbench-move-results
+++ b/agent/util-scripts/pbench-move-results
@@ -185,10 +185,14 @@ if [[ ! -z "${show_server}" ]] ;then
 fi
 
 # ssh probe test
-ssh -n -q -i ${pbench_bin}/id_rsa ${ssh_opts} ${results_repo} exit
-if [[ $? -ne 0 ]]; then
-    error_log "ERROR: results host unreachable: ${results_repo}"
-    debug_log "the following ssh command failed: \"ssh -n -q -i ${pbench_bin}/id_rsa ${ssh_opts} ${results_repo} exit\""
+ssh -n -i ${pbench_bin}/id_rsa ${ssh_opts} ${results_repo} exit
+sts=${?}
+if [[ ${sts} -eq 255 ]]; then
+    error_log "ERROR: ssh command, \"ssh -n -i ${pbench_bin}/id_rsa ${ssh_opts} ${results_repo} exit\", failed"
+    exit 1
+elif [[ ${sts} -ne 0 ]]; then
+    error_log "ERROR: 'exit' command unexpectedly failed on host ${results_repo} with '${sts}'"
+    debug_log "ssh command: \"ssh -n -i ${pbench_bin}/id_rsa ${ssh_opts} ${results_repo} exit\""
     exit 1
 fi
 
