Prometheus/Node_Exporter Full V1 Integration Commit
This work adds the notion of a "collector" to the Tool Data Sink, and
"tools" which run continuously without cycling through the "start", "stop",
and "send" phases.  The collector is responsible for continuously pulling
data from those tools which are now started during the new "init" phase,
and stopped during the new "end" phase.

The first actual implementation of this kind of collector is for the
prometheus data collection environment, where a `node-exporter` "tool" is
run providing a end-point for a prometheus server "collector" to pull data
from it and store it locally off the run directory (`${benchmark_run_dir}`,
e.g. `${benchmark_run_dir}/collector/prometheus`).

diff --git a/agent/util-scripts/pbench-postprocess-tools b/agent/util-scripts/pbench-postprocess-tools
--- a/agent/util-scripts/pbench-postprocess-tools
+++ b/agent/util-scripts/pbench-postprocess-tools
@@ -17,16 +17,20 @@ def_group="default"
 group="${def_group}"
 dir=""
 
-# Process options and arguments
-
-opts=$(getopt -q -o d:g: --longoptions "dir:,group:" -n "getopt.sh" -- "${@}")
-if [[ ${?} -ne 0 ]]; then
-	printf "\n%s: you specified an invalid option\n\n" "${script_name}"
+function usage {
 	printf "The following are required:\n\n"
 	printf -- "\t-g str --group=str, str = a tool group used in a benchmark\n"
 	printf -- "\t                          (the default group is '%s')\n\n" "${def_group}"
 	printf -- "\t-d str --dir=str, str = a directory where %s\n" "${script_name}"
 	printf -- "\t                        will store and process data\n"
+}
+
+# Process options and arguments
+
+opts=$(getopt -q -o d:g: --longoptions "dir:,group:" -n "getopt.sh" -- "${@}")
+if [[ ${?} -ne 0 ]]; then
+	printf "\n%s: you specified an invalid option\n\n" "${script_name}"
+	usage >&2
 	exit 1
 fi
 eval set -- "${opts}"
@@ -54,11 +58,13 @@ while true; do
 done
 
 if [[ -z "${group}" ]]; then
-	printf -- "ERROR: required tool group parameter missing.\n" >&2
+	printf -- "ERROR: required tool group parameter missing.\n\n" >&2
+	usage >&2
 	exit 1
 fi
 if [[ -z "${dir}" ]]; then
-	printf -- "ERROR: required directory argument missing.\n" >&2
+	printf -- "ERROR: required directory argument missing.\n\n" >&2
+	usage >&2
 	exit 1
 fi
 
