Replace tabs w spaces only

diff --git a/agent/util-scripts/pbench-move-results b/agent/util-scripts/pbench-move-results
--- a/agent/util-scripts/pbench-move-results
+++ b/agent/util-scripts/pbench-move-results
@@ -1,5 +1,5 @@
 #!/bin/bash
-# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 4; sh-indentation: 4; tab-width: 8 -*-
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; sh-indentation: 4; tab-width: 8 -*-
 script_path="$(dirname ${0})"
 script_name="$(basename ${0})"
 pbench_bin="$(realpath -e ${script_path}/..)"
@@ -36,55 +36,55 @@ while true; do
     opt="${1}"
     shift
     case "${opt}" in
-	-c|--controller)
-	    if [[ -n "${1}" ]]; then
-		controller="${1}"
-		shift;
-	    else
-		missing_arg "${opt}"
-	    fi
-	    ;;
-	-u|--user)
-	    if [[ -n "${1}" ]]; then
-		user="${1}"
-		shift;
-	    else
-		missing_arg "${opt}"
-	    fi
-	    ;;
-	-p|--prefix)
-	    if [[ -n "${1}" ]]; then
-		prefix="${1}"
-		shift;
-	    else
-		missing_arg "${opt}"
-	    fi
-	    ;;
-	-x|--xz-single-threaded)
-	    xz_single_threaded=1
-	    ;;
-	-S|--show-server)
-	    show_server="show"
-	    ;;
-	-h|--help)
-	    usage
+        -c|--controller)
+            if [[ -n "${1}" ]]; then
+        	controller="${1}"
+        	shift;
+            else
+        	missing_arg "${opt}"
+            fi
+            ;;
+        -u|--user)
+            if [[ -n "${1}" ]]; then
+        	user="${1}"
+        	shift;
+            else
+        	missing_arg "${opt}"
+            fi
+            ;;
+        -p|--prefix)
+            if [[ -n "${1}" ]]; then
+        	prefix="${1}"
+        	shift;
+            else
+        	missing_arg "${opt}"
+            fi
+            ;;
+        -x|--xz-single-threaded)
+            xz_single_threaded=1
+            ;;
+        -S|--show-server)
+            show_server="show"
+            ;;
+        -h|--help)
+            usage
    	    exit 0
-	    ;;
-	--)
-	    break;
-	    ;;
-	*)
-	    printf "\n${script_name}: you specified an invalid option or an unexpected argument\n\n" >&2
-	    usage >&2
-	    exit 1
+            ;;
+        --)
+            break;
+            ;;
+        *)
+            printf "\n${script_name}: you specified an invalid option or an unexpected argument\n\n" >&2
+            usage >&2
+            exit 1
     esac
 done
 
 if [[ -z "${controller}" ]]; then
     controller=${_pbench_full_hostname}
     if [[ -z "${controller}" ]]; then
-	error_log "Missing controller name (should be \"hostname -f\" value)"
-	exit 1
+        error_log "Missing controller name (should be \"hostname -f\" value)"
+        exit 1
     fi
 fi
 validate_hostname "${controller}" "controller"
@@ -213,48 +213,48 @@ while read -r dir; do
     # that information on to pbench-make-result-tb.
     result_dir=$(basename ${dir})
     if [[ -n "${user}" ]]; then
-	user_arg="--user ${user}"
+        user_arg="--user ${user}"
     else
-	user_arg=""
+        user_arg=""
     fi
     if [[ -n "${prefix}" ]]; then
-	prefix_arg="--prefix ${prefix}"
+        prefix_arg="--prefix ${prefix}"
     else
-	prefix_arg=""
+        prefix_arg=""
     fi
     result_tb_name=$(pbench-make-result-tb --result-dir "${result_dir}" --target-dir "${tmp}/${controller}" ${user_arg} ${prefix_arg} --xz-single-threaded "${xz_single_threaded}")
     if [[ ${?} -ne 0 ]]; then
-	# Messaging already handled by pbench-make-result-tb
-	continue
+        # Messaging already handled by pbench-make-result-tb
+        continue
     fi
     if [[ -z "${result_tb_name}" ]]; then
-	# Messaging already handled by pbench-make-result-tb
-	continue
+        # Messaging already handled by pbench-make-result-tb
+        continue
     fi
     pbench-copy-result-tb ${result_tb_name} ${results_repo} ${results_path_prefix}
     sts=${?}
     rm ${result_tb_name} ${result_tb_name}.md5.check
     if [[ ${?} -ne 0 ]]; then
-	error_log "UNEXPECTED ERROR: rm failed to remove ${result_tb_name} and its .md5.check file"
-	exit 1
+        error_log "UNEXPECTED ERROR: rm failed to remove ${result_tb_name} and its .md5.check file"
+        exit 1
     fi
     if [[ ${sts} -ne 0 ]]; then
-	let failures=failures+1
-	continue
+        let failures=failures+1
+        continue
     fi
 
     if [[ "$script_name" == "pbench-move-results" ]]; then
-	rm -r ${result_dir}
-	if [[ ${?} -ne 0 ]]; then
-	    error_log "UNEXPECTED ERROR: rm failed to remove the ${result_dir} directory hierarchy"
-	    exit 1
-	fi
+        rm -r ${result_dir}
+        if [[ ${?} -ne 0 ]]; then
+            error_log "UNEXPECTED ERROR: rm failed to remove the ${result_dir} directory hierarchy"
+            exit 1
+        fi
     else
-	touch ${result_dir}.copied
-	if [[ ${?} -ne 0 ]]; then
-	    error_log "UNEXPECTED ERROR: touch failed to ${result_dir}.copied"
-	    exit 1
-	fi
+        touch ${result_dir}.copied
+        if [[ ${?} -ne 0 ]]; then
+            error_log "UNEXPECTED ERROR: touch failed to ${result_dir}.copied"
+            exit 1
+        fi
     fi
     let runs_copied=runs_copied+1
 done < ${tmp}/results.lis
@@ -262,9 +262,9 @@ done < ${tmp}/results.lis
 let anything=runs_copied+failures
 if [[ $anything -gt 0 ]]; then
     if [[ "$script_name" == "pbench-move-results" ]]; then
-	op="moved"
+        op="moved"
     else
-	op="copied"
+        op="copied"
     fi
     debug_log "successfully $op $runs_copied runs, encountered $failures failures"
 fi
