Fix pbench-register-tool-trigger
Fixes #2268

Fix pbench-register-tool-trigger to detect missing arguments: both
of --start-trigger and --stop-trigger are always required.

Add unit tests for the various cases.

diff --git a/agent/util-scripts/pbench-register-tool-trigger b/agent/util-scripts/pbench-register-tool-trigger
--- a/agent/util-scripts/pbench-register-tool-trigger
+++ b/agent/util-scripts/pbench-register-tool-trigger
@@ -1,4 +1,5 @@
 #!/bin/bash
+# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
 script_path=`dirname $0`
 script_name=`basename $0`
@@ -19,16 +20,19 @@ stop_trigger=""
 
 function usage() {
 	printf "usage:\n"
-	printf "$script_name --group=<tool group> --start-trigger=<string to match> --stop-trigger=<string to match>"
+	printf "$script_name [--group=<tool group>] --start-trigger=<string to match> --stop-trigger=<string to match>\n"
 }
+
+if [[ "${#}" == 0 ]] ;then
+        usage >&2
+        exit 1
+fi
 
 # Process options and arguments
 opts=$(getopt -q -o h --longoptions "help,group:,start-trigger:,stop-trigger:" -n "getopt.sh" -- "$@");
 if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "%s\n" $*
-	printf "$script_name: you specified an invalid option\n\n"
-	usage
+	printf "\n%s\n%s: you specified an invalid option\n\n" "${*}" "${script_name}" >&2
+	usage >&2
 	exit 1
 fi
 eval set -- "$opts";
@@ -69,12 +73,17 @@ while true; do
 	esac
 done
 
-if [ "$start_trigger" != "${start_trigger%%:*}" ]; then
-	printf "$script_name: the start trigger cannot have a colon in it: \"${start_trigger}\"\n"
+if [[ -z "$start_trigger" || -z "$stop_trigger" ]] ;then
+	printf "Both --start-trigger and --stop-trigger must be specified and must be non-empty.\n" >&2
+	usage >&2
+	exit 1
+fi
+if [[ "$start_trigger" != "${start_trigger%%:*}" ]]; then
+	printf "$script_name: the start trigger cannot have a colon in it: \"${start_trigger}\"\n" >&2
 	exit 1
 fi
 if [ "$stop_trigger" != "${stop_trigger%%:*}" ]; then
-	printf "$script_name: the stop trigger cannot have a colon in it: \"${stop_trigger}\"\n"
+	printf "$script_name: the stop trigger cannot have a colon in it: \"${stop_trigger}\"\n" >&2
 	exit 1
 fi
 
