Rename util scripts to avoid collisions.
All the util scripts now have a prefix of pbench-.

Move non-pbench scripts to contrib/ subdirectory.

contrib/ is not added to the PATH so there will be no
collision. If users want to use one or more of these,
they will need to call them by full pathname or add
contrib/ to their PATH.

Add a backward-compatibility wrapper temporarily.

We maintain compatibility with the old util-scripts names
*for one release only*. The old names will be symlinked to
this wrapper in a postinstall action when the RPM is installed.
The wrapper does some minimal checking, issues a big fat warning
and then executes the script under its new name.

diff --git a/agent/util-scripts/pbench-remote-sysinfo-dump b/agent/util-scripts/pbench-remote-sysinfo-dump
--- a/agent/util-scripts/pbench-remote-sysinfo-dump
+++ b/agent/util-scripts/pbench-remote-sysinfo-dump
@@ -20,14 +20,14 @@ if [ ! -d $sysinfo_path ]; then
 	exit 1
 fi
 
-sysinfo-dump $sysinfo_path $label
+pbench-sysinfo-dump $sysinfo_path $label
 if [ $? -ne 0 ]; then
-	echo "\"sysinfo-dump $sysinfo_path $label\" failed!" >&2
+	echo "\"pbench-sysinfo-dump $sysinfo_path $label\" failed!" >&2
 	exit 1
 fi
 
 cd $sysinfo_path >&2
-echo "sysinfo-dump data size: $(du -sm $sysinfo_path | awk '{print $1}') MB" >&2
+echo "pbench-sysinfo-dump data size: $(du -sm $sysinfo_path | awk '{print $1}') MB" >&2
 tar cf - *
 exit_status=$?
 rm -rf $sysinfo_path >&2
