Fix all bash CLIs to catch missing option args
The `getopt` does not detect when an option that expects a parameter
is missing when followed by another valid option.  For example, if
we have `getopt -o a:b:c`, then a command line of `prog -a -b -c` will
give `-b` as the option value for `-a`, and -b will not be considered
at all.

This has consequences for all bash based CLI processing that uses
`getopt` in the various pbench-agent modules.

Rather than fixing each one individually, we have written a drop-in
replacement for `getopt`, called `pbench-argparse`, which is a simple
Python 3 program to mimic the behavior of `getopt` while adding the
ability to check for options as arguments.

diff --git a/agent/util-scripts/pbench-clear-tools b/agent/util-scripts/pbench-clear-tools
--- a/agent/util-scripts/pbench-clear-tools
+++ b/agent/util-scripts/pbench-clear-tools
@@ -13,54 +13,62 @@ pbench_bin="`cd ${script_path}/..; /bin/pwd`"
 # Specifying a tool name and/or group will limit the scope of the
 # removal.
 
-# Defaults
-name=""
-group="default"
-
-# Process options and arguments
-
-opts=$(getopt -q -o g:n: --longoptions "group:,name:,remote:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
+function usage() {
+    printf "usage:\n"
+    printf "${script_name} [--help] <full path to tar ball> <results host> <results path prefix>\n"
 	printf "The following are required:\n\n"
 	printf -- "\t-g str --group=str, str = the group from which tools should be removed\n"
 	printf -- "\t                          (the default group is 'default')\n"
 	printf -- "\t-n str --name=str, str = a specific tool to be removed.  If no tool is specified, all tools in the group are removed\n"
-        printf -- "\t-n str --remote=str, str = a specific remote on which tools needs to be cleared.  If no remote is specified, all the tools are removed\n"
-	printf "\n"
+	printf -- "\t-n str --remote=str, str = a specific remote on which tools needs to be cleared.  If no remote is specified, all the tools are removed\n\n"
+}
 
-	exit 1
+# Process options and arguments
+opts=$(pbench-argparse -q -o g:n:r:h --longoptions "group:,name:,remote:,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+	exit ${sts}
 fi
-eval set -- "$opts";
+
+# Defaults
+name=""
+group="default"
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		-n|--name)
-		shift;
-		if [ -n "$1" ]; then
-			name="$1"
-			shift;
-		fi
-		;;
-		-g|--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="$1"
-			shift;
-		fi
-		;;
-		-r|--remote)
-                shift;
-                if [ -n "$1" ]; then
-                        remote="$1"
-                        shift;
-                fi
-                ;;
-		--)
-		shift;
-		break;
-		;;
-	esac
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-n|--name)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    name="${1}"
+	    shift
+	    ;;
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="${1}"
+	    shift
+	    ;;
+	-r|--remote)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+            remote="${1}"
+            shift
+            ;;
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
 
 pushd $pbench_run >/dev/null
diff --git a/agent/util-scripts/pbench-collect-sysinfo b/agent/util-scripts/pbench-collect-sysinfo
--- a/agent/util-scripts/pbench-collect-sysinfo
+++ b/agent/util-scripts/pbench-collect-sysinfo
@@ -49,54 +49,54 @@ function usage {
 	printf -- "\t       --check,       checks if sysinfo is set to one of the accepted values\n"
 }
 
-opts=$(getopt -q -o d:g:h --longoptions "dir:,group:,help,options,sysinfo:,check" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
-	usage
-	exit 1
+opts=$(pbench-argparse -q -o d:g:h --longoptions "dir:,group:,help,options,sysinfo:,check" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
 fi
-eval set -- "$opts";
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		-g|--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="$1"
-			shift;
-		fi
-		;;
-		-d|--dir)
-		shift;
-		if [ -n "$1" ]; then
-			dir="$1"
-			shift;
-		fi
-		;;
-		--options)
-		display_sysinfo_opts
-		exit 0
-		;;
-		--sysinfo)
-		shift;
-		if [ -n "$1" ]; then
-			sysinfo="$1"
-			shift;
-		fi
-		;;
-		--check)
-		check=true
-		shift;
-		;;
-		-h|--help)
-		usage
-		exit 0
-		;;
-		--)
-		shift;
-		break;
-		;;
-	esac
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="${1}"
+	    shift
+	    ;;
+	-d|--dir)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    dir="${1}"
+	    shift
+	    ;;
+	--options)
+	    display_sysinfo_opts
+	    exit 0
+	    ;;
+	--sysinfo)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    sysinfo="${1}"
+	    shift
+	    ;;
+	--check)
+	    check=true
+	    ;;
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
 
 # if unspecified, collect the default sysinfo
diff --git a/agent/util-scripts/pbench-copy-result-tb b/agent/util-scripts/pbench-copy-result-tb
--- a/agent/util-scripts/pbench-copy-result-tb
+++ b/agent/util-scripts/pbench-copy-result-tb
@@ -14,23 +14,30 @@ function usage() {
 }
 
 # Process options and arguments
-opts=$(getopt -q -o h --longoptions "help" -- "${@}")
-if [[ ${?} -ne 0 ]]; then
-    printf "\n${script_name}: you specified an invalid option\n\n" >&2
+opts=$(pbench-argparse -q -o h --longoptions "help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
     usage >&2
-    exit 1
+    exit ${sts}
 fi
 
 eval set -- "${opts}"
 while true; do
-    case "${1}" in
+    opt="${1}"
+    shift
+    case "${opt}" in
 	-h|--help)
 	    usage
 	    exit 0
 	    ;;
 	--)
-	    shift;
-	    break;
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
 	    ;;
     esac
 done
diff --git a/agent/util-scripts/pbench-list-tools b/agent/util-scripts/pbench-list-tools
--- a/agent/util-scripts/pbench-list-tools
+++ b/agent/util-scripts/pbench-list-tools
@@ -1,75 +1,86 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+script_path="$(dirname ${0})"
+script_name="$(basename ${0})"
+pbench_bin="$(realpath -e ${script_path}/..)"
 
 # source the base script
-. "$pbench_bin"/base
+. "${pbench_bin}"/base
 
-# This script can list all tools from all groups,
-# list tools from a specific group, or list which
-# groups contain a specific tool
+# This script can list all tools from all groups, list tools from a specific
+# group, or list which groups contain a specific tool
+
+function usage() {
+    printf -- "usage:\n"
+    printf -- "${script_name} [--help] [--name=<tool name>] [--group=<tool group>] [--with-options]\n"
+    printf -- "The following options are available (use neither, one, or the other, but not both):\n\n"
+    printf -- "\t-n str --name=str, list the perftool groups which str is used\n\n"
+    printf -- "\t-g str --group=str, list the tools used in this str\n\n"
+    printf -- "\t-o --with-options, list the options with each tool\n"
+}
+
+# Process options and arguments
+opts=$(pbench-argparse -q -o g:n:oh --longoptions "group:,name:,with-options,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
+fi
 
 # Defaults
 name=""
 group=""
 with_options=0
+with_options_opt=""
 
-# Process options and arguments
-
-opts=$(getopt -q -o tn:og: --longoptions "with-options,name:,group:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
-	printf "The following options are available (use neither, one, or the other, but not both):\n\n"
-	printf -- "\t-n str --name=str, list the perftool groups which str is used\n"
-	printf "\n"
-	printf -- "\t-g str --group=str, list the tools used in this str\n"
-	printf "\n"
-	printf -- "\t-o --with-options, list the options with each tool\n"
-
-
-	exit 1
-fi
-eval set -- "$opts";
+eval set -- "$opts"
 while true; do
-	case "$1" in
-		-n|--name)
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-n|--name)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    if [[ "${group}" = "" ]]; then
+		name="${1}"
+		shift
+	    else
+		printf "You cannot specify both a group and a name\n\n" >&2
+		usage >&2
+		exit 1
+	    fi
+	    ;;
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    if [[ "${name}" = "" ]]; then
+		group="${1}"
 		shift;
-		if [ -n "$1" -a "$group" = "" ]; then
-			name="$1"
-			shift;
-		else
-			printf "You cannot specify both group and a name\n"
-			exit 1
-		fi
-		;;
-		-g|--group)
-		shift;
-		if [ -n "$1" -a "$name" = "" ]; then
-			group="$1"
-			shift;
-		else
-			printf "You cannot specify both group and a name\n"
-			exit 1
-		fi
-		;;
-		-o|--with-options)
-		shift;
-		with_options=1
-		with_options_opt="--with-options" # used if we ssh for remote list
-		;;
-		--)
-		shift;
-		break;
-		;;
-                *)
-                    break
-                    ;;
-	esac
+	    else
+		printf "You cannot specify both a name and a group\n\n" >&2
+		usage >&2
+		exit 1
+	    fi
+	    ;;
+	-o|--with-options)
+	    with_options=1
+	    with_options_opt="--with-options" # used if we ssh for remote list
+	    ;;
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
+
 if [ -d "$pbench_run" ]; then
 	pushd "$pbench_run" >/dev/null
 	if [ -z $name ]; then
@@ -112,7 +123,7 @@ if [ -d "$pbench_run" ]; then
 				printf "%s: %s\n" "$group" "$tools"
 			fi
 		done
-	else 
+	else
 		# list the groups which include this tool
 		for group in `/bin/ls tools-* 2>/dev/null | sed -e s/^tools-//g`; do
 			if /bin/ls tools-$group | grep -q "^$name"; then
diff --git a/agent/util-scripts/pbench-list-triggers b/agent/util-scripts/pbench-list-triggers
--- a/agent/util-scripts/pbench-list-triggers
+++ b/agent/util-scripts/pbench-list-triggers
@@ -7,50 +7,66 @@ pbench_bin="`cd ${script_path}/..; /bin/pwd`"
 # source the base script
 . "$pbench_bin"/base
 
-# This script can list all tools from all groups,
-# list tools from a specific group, or list which
-# groups contain a specific tool
+# This script can list triggers for a single tool group or for all tool
+# groups.
+
+function usage() {
+    printf -- "usage:\n"
+    printf -- "${script_name} [--help] [--group=<tool group name>]\n"
+    printf -- "The following option is available:\n\n"
+    printf -- "\t-g str --group=str, list the triggers used by this group\n"
+    printf -- "\t                    (defaults to all tool groups)\n"
+}
+
+# Process options and arguments
+opts=$(pbench-argparse -q -o g:h --longoptions "group:,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
+fi
 
 # Defaults
 name=""
 group=""
 with_options=0
 
-# Process options and arguments
-
-opts=$(getopt -q -o to:g: --longoptions "group:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
-	printf "The following option is available: \n\n"
-	printf -- "\t-g str --group=str, list the triggers used by this group\n"
-	exit 1
-fi
-eval set -- "$opts";
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		-g|--group)
-		shift;
-		group="$1"
-		shift;
-		;;
-		--)
-		shift;
-		break;
-		;;
-	esac
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="$1"
+	    shift
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
-if [ -d "$pbench_run" ]; then
-	pushd "$pbench_run" >/dev/null
-	# list tool triggers in one or all groups
-	if [ -z "$group" ]; then
-		groups=`/bin/cat tool-triggers 2>/dev/null | grep -v '^#' | sed -e s/:.*//`
-	else
-		groups="$group"
-	fi
 
-	for grp in $groups ;do
-		sed -n '/^'$grp'/p' tool-triggers
-	done
-	popd  >/dev/null
+if [[ ! -d "${pbench_run}" ]]; then
+    printf -- "Logic bomb! pbench_run directory, ${pbench_run}, does not exist or is not a directory\n" >&2; exit 200;
 fi
+pushd "${pbench_run}" >/dev/null
+
+# list tool triggers in one or all groups
+if [[ -z "${group}" ]]; then
+    groups=$(/bin/cat tool-triggers 2>/dev/null | grep -v '^#' | sed -e s/:.*//)
+else
+    groups="${group}"
+fi
+
+for grp in ${groups} ;do
+    sed -n '/^'${grp}'/p' tool-triggers
+done
+
+popd >/dev/null
diff --git a/agent/util-scripts/pbench-metadata-log b/agent/util-scripts/pbench-metadata-log
--- a/agent/util-scripts/pbench-metadata-log
+++ b/agent/util-scripts/pbench-metadata-log
@@ -5,12 +5,12 @@
 # needs to be invoked *after* the base script is sourced and *after*
 # the benchmark_run_dir is set.
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+script_path="$(dirname ${0})"
+script_name="$(basename ${0})"
+pbench_bin="$(realpath -e ${script_path}/..)"
 
 # source the base script
-. "$pbench_bin"/base
+. "${pbench_bin}"/base
 
 # This script will collect metadata about a pbench run.  This is
 # typically called at the beginning and end of a benchmark script to
@@ -29,34 +29,40 @@ function usage {
 }
 
 # Process options and arguments
-
-opts=$(getopt -q -o d:g: --longoptions "dir:,group:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-    printf "\n"
-    printf "$script_name: you specified an invalid option\n\n"
-    usage
-    exit 1
+opts=$(pbench-argparse -q -o d:g:h --longoptions "dir:,group:,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
 fi
-eval set -- "$opts";
+
+eval set -- "${opts}"
 while true; do
-    case "$1" in
+    opt="${1}"
+    shift
+    case "${opt}" in
 	-d|--dir)
-	    shift;
-	    if [ -n "$1" ]; then
-		    dir="$1"
-		shift;
-	    fi
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    dir="$1"
+	    shift
 	    ;;
 	-g|--group)
-	    shift;
-	    if [ -n "$1" ]; then
-		    group="$1"
-		    shift;
-	    fi
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="$1"
+	    shift
+	    ;;
+	-h|--help)
+	    usage
+   	    exit 0
 	    ;;
 	--)
-	    shift;
-	    break;
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
 	    ;;
     esac
 done
diff --git a/agent/util-scripts/pbench-move-results b/agent/util-scripts/pbench-move-results
--- a/agent/util-scripts/pbench-move-results
+++ b/agent/util-scripts/pbench-move-results
@@ -9,48 +9,39 @@ pbench_bin="$(realpath -e ${script_path}/..)"
 . "${pbench_bin}"/base
 
 function usage() {
-    printf "usage:\n"
-    printf "${script_name} [--help] [--user=<user>] [--prefix=<path>] [--xz-single-threaded] [--show-server]\n"
-}
-
-function missing_arg() {
-    printf "\n${script_name}: ${1} is missing its argument\n\n" >&2
-    usage >&2
-    exit 1
+    printf -- "usage:\n"
+    printf -- "${script_name} [--help] [--user=<user>] [--prefix=<path>] [--xz-single-threaded] [--show-server]\n"
 }
 
 # Process options and arguments
-opts=$(getopt -q -o u:p:xSh --longoptions "user:,prefix:,xz-single-threaded,show-server,help" -n "getopt.sh" -- "${@}")
-if [[ ${?} -ne 0 ]]; then
-    printf "\n${script_name}: you specified an invalid option or an unexpected argument\n\n" >&2
+opts=$(pbench-argparse -o u:p:xSh --longoptions "user:,prefix:,xz-single-threaded,show-server,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
     usage >&2
-    exit 1
+    exit ${sts}
 fi
 
+# Now process the arguments to get actual values from them.
 user="${PBENCH_USER}"
 prefix=""
 xz_single_threaded=0
 show_server=""
+
 eval set -- "${opts}"
 while true; do
     opt="${1}"
     shift
     case "${opt}" in
 	-u|--user)
-	    if [[ -n "${1}" ]]; then
-		user="${1}"
-		shift;
-	    else
-		missing_arg "${opt}"
-	    fi
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    user="${1}"
+	    shift
 	    ;;
 	-p|--prefix)
-	    if [[ -n "${1}" ]]; then
-		prefix="${1}"
-		shift;
-	    else
-		missing_arg "${opt}"
-	    fi
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    prefix="${1}"
+	    shift
 	    ;;
 	-x|--xz-single-threaded)
 	    xz_single_threaded=1
@@ -63,12 +54,13 @@ while true; do
    	    exit 0
 	    ;;
 	--)
-	    break;
+	    break
 	    ;;
 	*)
-	    printf "\n${script_name}: you specified an invalid option or an unexpected argument\n\n" >&2
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
 	    usage >&2
 	    exit 1
+	    ;;
     esac
 done
 
diff --git a/agent/util-scripts/pbench-postprocess-tools b/agent/util-scripts/pbench-postprocess-tools
--- a/agent/util-scripts/pbench-postprocess-tools
+++ b/agent/util-scripts/pbench-postprocess-tools
@@ -1,76 +1,80 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
-action=`echo ${script_name#pbench-} | awk -F- '{print $1}'`
+script_path="$(dirname ${0})"
+script_name="$(basename ${0})"
+pbench_bin="$(realpath -e ${script_path}/..)"
 
 # source the base script
 . "$pbench_bin"/base
 
-if [ "$action" != "start" -a "$action" != "stop" -a "$action" != "postprocess" -a "$action" != "kill" ]; then 
-	error_log "[$script_name] action "$action" is not supported"
-	exit 1
+_action="${script_name#pbench-}"
+action="${_action%-tools}"
+if [[ "$action" != "start" && "$action" != "stop" && "$action" != "postprocess" && "$action" != "kill" ]]; then
+    error_log "[${script_name}] action \"${action}\" is not supported"
+    exit 1
 fi
 
-# This script will $action all tools that belong
-# to a specific group.  This is typically called
-# by a benchmark script when some activity needs to
-# monitored.
+args="${@}"
+
+# This script will ${action} all tools that belong to a specific tool group.
+# This is typically called by a benchmark script when some activity needs to
+# be monitored.
 
 # Defaults
-group=default
+group="default"
 dir="/tmp"
 iteration=1
 
-debug_log "[$script_name]started: $@"
+function usage() {
+    printf -- "usage:\n"
+    printf -- "${script_name} [--help] [--dir=<work directory>] [--group=<tool group>] [--iteration=<number>]\n\n"
+    printf -- "The following are required:\n\n"
+    printf -- "\t-g str --group=str, str = a tool group used in a benchmark\n"
+    printf -- "\t                          (the default group is 'default')\n\n"
+    printf -- "\t-d str --dir=str, str = a directory where the $script_name\n"
+    printf -- "\t                        will store and process data\n\n"
+    printf -- "\t-i num --iteration=num, num = a number representing the\n"
+    printf -- "\t                              iteration data was collected for\n"
+}
 
 # Process options and arguments
-
-opts=$(getopt -q -o d:g:i: --longoptions "dir:,group:,iteration:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
-	printf "The following are required:\n\n"
-	printf -- "\t-g str --group=str, str = a tool group used in a benchmark\n"
-	printf -- "\t                          (the default group is 'default')\n"
-	printf "\n"
-	printf -- "\t-d str --dir=str, str = a directory where the $script_name\n"
-	printf -- "\t                        will store and process data\n"
-	printf "\n"
-	printf -- "\t-i num --iteration=num, num = a number representing the\n"
-	printf -- "\t                              iteration data was collected for\n"
-	exit 1
+opts=$(pbench-argparse -q -o d:g:i:h --longoptions "dir:,group:,iteration:,help" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
 fi
-eval set -- "$opts";
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		-g|--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="$1"
-			shift;
-		fi
-		;;
-		-d|--dir)
-		shift;
-		if [ -n "$1" ]; then
-			dir="$1"
-			shift;
-		fi
-		;;
-		-i|--iteration)
-		shift;
-		if [ -n "$1" ]; then
-			iteration="$1"
-			shift;
-		fi
-		;;
-		--)
-		shift;
-		break;
-		;;
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="${1}"
+	    shift
+	    ;;
+	-d|--dir)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    dir="${1}"
+	    shift
+	    ;;
+	-i|--iteration)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    iteration="${1}"
+	    shift
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
 	esac
 done
 
@@ -79,7 +83,7 @@ iteration_num=`echo $iteration | awk -F- '{print $1}'`
 # this tool group's directory which stores options, etc.
 tool_group_dir="$pbench_run/tools-$group"
 if [ ! -d "$tool_group_dir" ]; then
-	error_log "[$script_name] failed to find tools group directory, \"$tool_group_dir\""
+	error_log "[${script_name}] failed to find tools group directory, \"$tool_group_dir\""
 	exit 1
 fi
 
@@ -87,9 +91,11 @@ fi
 tool_output_dir="$dir/tools-$group"
 mkdir -p $tool_output_dir
 if [ $? -ne 0 ]; then
-	error_log "[$script_name] failed to create tool output directory, \"$tool_output_dir\""
+	error_log "[${script_name}] failed to create tool output directory, \"$tool_output_dir\""
 	exit 1
 fi
+
+debug_log "[${script_name}] started: ${args}"
 
 # Try to prevent a cascade of tools running.
 if [ "$action" == "start" ] ;then
@@ -104,11 +110,11 @@ function move_tool_data {
 	local remote_shost=`echo $remote_host | awk -F. '{print $1}'`
 	pushd $tool_output_dir >/dev/null
 	tool_data_size=`ssh $ssh_opts -n $remote_host du -sm $tool_output_dir | awk '{print $1}'`
-	debug_log "[$script_name]started: copying tool data ($tool_data_size MB) from $remote_host"
+	debug_log "[${script_name}] started: copying tool data ($tool_data_size MB) from $remote_host"
 	ssh $ssh_opts -n $remote_host "cd $tool_output_dir && tar cf - *" | tar mxf -
 	rc=$?
 	if [ $rc != 0 ] ;then
-		debug_log "[$script_name]copying tool data failed for remote $remote_host"
+		debug_log "[${script_name}] copying tool data failed for remote $remote_host"
 		popd > /dev/null
 		return $rc
 	fi
@@ -121,11 +127,11 @@ function move_tool_data {
 			mv $remote_shost $remote_host
 		fi
 	fi
-	debug_log "[$script_name]completed: copying of tool data on $remote_host"
-	debug_log "[$script_name]started: deleting tool data on $remote_host"
+	debug_log "[${script_name}] completed: copying of tool data on $remote_host"
+	debug_log "[${script_name}] started: deleting tool data on $remote_host"
 	ssh $ssh_opts -n $remote_host "cd $tool_output_dir && /bin/rm -rf *"
 	rc=$?
-	debug_log "[$script_name]completed: deleting tool data on $remote_host"
+	debug_log "[${script_name}] completed: deleting tool data on $remote_host"
 	popd >/dev/null
 	return $rc
 }
@@ -140,15 +146,15 @@ for this_tool_file in `/bin/ls $tool_group_dir`; do
 		remote_hostname=`echo $this_tool_file | cut -d\@ -f2`
 		name=`echo $this_tool_file | cut -d\@ -f1`
 		# tool options are stored on the remote host's tool file, so no need to pass it here
-		debug_log "[$script_name]running this tool on $remote_hostname: ssh $ssh_opts -n $remote_hostname pbench-$action-tools --iteration=$iteration --group=$group --dir=$dir"
+		debug_log "[${script_name}] running this tool on $remote_hostname: ssh $ssh_opts -n $remote_hostname pbench-$action-tools --iteration=$iteration --group=$group --dir=$dir"
 		ssh $ssh_opts -n $remote_hostname pbench-$action-tools --iteration=$iteration --group=$group --dir=$dir &
 		pids="$pids $!"
 	elif [ -d $tool_group_dir/$this_tool_file ] ;then
 		# skip spurious subdirectory of $tool_group_dir
-		warn_log "[$script_name]$this_tool_file is a directory in $tool_group_dir; that should not happen. Please consider deleting it."
+		warn_log "[${script_name}] $this_tool_file is a directory in $tool_group_dir; that should not happen. Please consider deleting it."
 	elif [ ! -e "$pbench_bin/tool-scripts/$this_tool_file" ] ;then
 		# skip spurious file - not a tool.
-		warn_log "[$script_name]$this_tool_file does not exist in $pbench_bin/tool-scripts; spurious file perhaps? Please consider deleting it."
+		warn_log "[${script_name}] $this_tool_file does not exist in $pbench_bin/tool-scripts; spurious file perhaps? Please consider deleting it."
 	else
 		# tool is local
 		# assemble the tool options in to an array
@@ -160,10 +166,10 @@ for this_tool_file in `/bin/ls $tool_group_dir`; do
 		done < "$tool_group_dir/$this_tool_file"
 		name="$this_tool_file"
 		screen_name="pbench-tool-$name-$group"
-		debug_log "[$script_name] $pbench_bin/tool-scripts/$name --$action --iteration=$iteration --group=$group --dir=$dir ${tool_opts[@]}"
-		if [ "$action" == "start" ]; then 
+		debug_log "[${script_name}] $pbench_bin/tool-scripts/$name --$action --iteration=$iteration --group=$group --dir=$dir ${tool_opts[@]}"
+		if [ "$action" == "start" ]; then
 			# using screen to avoid tty issues and guarantee tool is backgrounded
-			debug_log "[$script_name] screen -dmS $screen_name $pbench_bin/tool-scripts/$name --$action --iteration=$iteration --group=$group --dir=$dir ${tool_opts[@]}"
+			debug_log "[${script_name}] screen -dmS $screen_name $pbench_bin/tool-scripts/$name --$action --iteration=$iteration --group=$group --dir=$dir ${tool_opts[@]}"
 			screen -dmS $screen_name $pbench_bin/tool-scripts/$name --$action --iteration=$iteration --group=$group --dir=$dir "${tool_opts[@]}"
 			rc=$?
 			if [ $rc -ne 0 ]; then
@@ -202,15 +208,15 @@ if [ "$action" == "postprocess" ]; then
 		if echo $this_tool_file | grep -q -v "@"; then
 			if [ -d $tool_group_dir/$this_tool_file ] ;then
 				# skip spurious subdirectory of $tool_group_dir
-				warn_log "[$script_name]$this_tool_file is a directory in $tool_group_dir; that should not happen. Please consider deleting it."
+				warn_log "[${script_name}] $this_tool_file is a directory in $tool_group_dir; that should not happen. Please consider deleting it."
 				continue
 			fi
 			if [ "$this_tool_file" != "label" -a ! -e "$pbench_bin/tool-scripts/$this_tool_file" ] ;then
 				# skip spurious file - not a tool.
-				warn_log "[$script_name]$this_tool_file does not exist in $pbench_bin/tool-scripts; spurious file perhaps? Please consider deleting it."
+				warn_log "[${script_name}] $this_tool_file does not exist in $pbench_bin/tool-scripts; spurious file perhaps? Please consider deleting it."
 				continue
 			fi
-			
+
 			pushd $tool_output_dir >/dev/null
 			if [ -f "$tool_group_dir/label" ]; then
 				label="`cat "$tool_group_dir/label"`"
@@ -223,7 +229,7 @@ if [ "$action" == "postprocess" ]; then
 			popd >/dev/null
 		fi
 	done
-	
+
 	### phase 3: copy over data from remote hosts
 	# for the remote tools, copy over the postprocess data
 	pids=""
@@ -243,5 +249,5 @@ if [ "$action" == "postprocess" ]; then
 	done
 fi
 
-debug_log "[$script_name]completed: $@"
-exit $nerrs
+debug_log "[${script_name}] completed: ${args}"
+exit ${nerrs}
diff --git a/agent/util-scripts/pbench-register-tool b/agent/util-scripts/pbench-register-tool
--- a/agent/util-scripts/pbench-register-tool
+++ b/agent/util-scripts/pbench-register-tool
@@ -1,17 +1,16 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+script_path="$(dirname ${0})"
+script_name="$(basename ${0})"
+pbench_bin="$(realpath -e ${script_path}/..)"
 
 # source the base script
-. "$pbench_bin"/base
+. "${pbench_bin}"/base
 
-# The sole purpose of this script is to ensure a tool
-# of your choosing is used during the execution of a benchmark.
-# For a list of performance tools, look at the
-# $pbench_bin/tool-scripts directory.
+# The sole purpose of this script is to ensure a tool of your choosing is used
+# during the execution of a benchmark.  For a list of performance tools, look
+# at the ${pbench_bin}/tool-scripts directory.
 
 # Defaults
 remote=""
@@ -19,63 +18,61 @@ group=default
 options=""
 
 function usage() {
-	printf "usage:\n"
-	printf "$script_name --name=<tool-name> [--group=<group-name>] [--remote=<remote-host>] -- [all tool specific options here]\n"
-	printf "for a list of tool specific options, run $pbench_bin/tool-scripts/<tool-name> --help\n"
+    printf -- "usage:\n"
+    printf -- "$script_name --name=<tool-name> [--group=<group-name>] [--remote=<remote-host>] -- [all tool specific options here]\n"
+    printf -- "for a list of tool specific options, run $pbench_bin/tool-scripts/<tool-name> --help\n"
 }
 
 # Process options and arguments
-opts=$(getopt -q -o hn:r:l:g: --longoptions "help,name:,remote:,label:,group:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "%s\n" $*
-	printf "$script_name: you specified an invalid option\n\n"
-	usage
-	exit 1
+opts=$(pbench-argparse -q -o hn:r:l:g: --longoptions "help,name:,remote:,label:,group:" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
 fi
-# here we process only the arguments before the "--"
-# these are argument for pbench-register-tools
-# all agruments after "--" are for the tool itself
-eval set -- "$opts";
+
+# Here we process only the arguments before the "--" these are arguments for
+# pbench-register-tool, all agruments after "--" are for the tool itself.
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		-n|--name)
-		shift;
-		if [ -n "$1" ]; then
-			name="$1"
-			shift;
-		fi
-		;;
-		-r|--remote)
-		shift;
-		if [ -n "$1" ]; then
-			remote="$1"
-			shift;
-		fi
-		;;
-		-l|--label) # used for remote only
-		shift;
-		if [ -n "$1" ]; then
-			label="$1"
-			shift;
-		fi
-		;;
-		-g|--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="$1"
-			shift;
-		fi
-		;;
-		-h|--help)
-		usage;
-		exit 0
-		;;
-		--)
-		shift;
-		break;
-		;;
-	esac
+    opt="${1}"
+    shift
+    case "${opt}" in
+	-n|--name)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    name="${1}"
+	    shift
+	    ;;
+	-r|--remote)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    remote="${1}"
+	    shift
+	    ;;
+	-l|--label) # used for remote only
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    label="${1}"
+	    shift
+	    ;;
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="${1}"
+	    shift
+	    ;;
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
 
 
diff --git a/agent/util-scripts/pbench-register-tool-set b/agent/util-scripts/pbench-register-tool-set
--- a/agent/util-scripts/pbench-register-tool-set
+++ b/agent/util-scripts/pbench-register-tool-set
@@ -1,17 +1,16 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+script_path="$(dirname ${0})"
+script_name="$(basename ${0})"
+pbench_bin="$(realpath -e ${script_path}/..)"
 
 # source the base script
-. "$pbench_bin"/base
+. "${pbench_bin}"/base
 
-# The sole purpose of this script is to ensure a tool
-# of your choosing is used during the execution of a benchmark.
-# For a list of performance tools, look at the
-# $pbench_bin/tool-scripts directory.
+# The sole purpose of this script is to ensure a set of pre-defined tools of
+# your choosing are used during the execution of a benchmark.  For a list of
+# performance tools, look at the ${pbench_bin}/tool-scripts directory.
 
 # Defaults
 toolset="default"
@@ -20,70 +19,66 @@ label=""
 group=""
 default_interval=$(getconf.py interval pbench/tools)
 if [[ -z "${default_interval}" ]] ;then
-	default_interval=3
+    default_interval=3
 fi
 
 function usage() {
-	printf "usage:\n"
-	printf "$script_name --toolset=<tool-set> [--group=<group-name>] [--remote=<remote-host>] [--label=<label>] [--interval=<interval] -- [all tool specific options here]\n"
+    printf "usage:\n"
+    printf "$script_name --toolset=<tool-set> [--group=<group-name>] [--remote=<remote-host>] [--label=<label>] [--interval=<interval] -- [all tool specific options here]\n"
 }
 
 # Process options and arguments
-opts=$(getopt -q -o hr:l:g:i: --longoptions "help,toolset:,remote:,label:,group:,interval:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "%s\n" $*
-	printf "$script_name: you specified an invalid option or forgot a required option value\n\n"
-	usage
-	exit 1
+opts=$(pbench-argparse -q -o hr:l:g:i: --longoptions "help,toolset:,remote:,label:,group:,interval:" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+    printf -- "\n" >&2
+    usage >&2
+    exit ${sts}
 fi
-eval set -- "$opts";
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		--toolset)
-		shift;
-		if [ -n "$1" ]; then
-			toolset="$1"
-			shift;
-		fi
-		;;
-		-r|--remote)
-		shift;
-		if [ -n "$1" ]; then
-			remote="--remote=$1"
-			shift;
-		fi
-		;;
-		-l|--label)
-		shift;
-		if [ -n "$1" ]; then
-			label="--label=$1"
-			shift;
-		fi
-		;;
-		-g|--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="--group=$1"
-			shift;
-		fi
-		;;
-		-i|--interval)
-		shift;
-		if [ -n "$1" ]; then
-			default_interval="$1"
-			shift;
-		fi
-		;;
-		-h|--help)
-		usage;
-		exit 0
-		;;
-		--)
-		shift;
-		break;
-		;;
-	esac
+    opt="${1}"
+    shift
+    case "${opt}" in
+	--toolset)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    toolset="${1}"
+	    shift
+	    ;;
+	-r|--remote)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    remote="--remote=${1}"
+	    shift
+	    ;;
+	-l|--label)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    label="--label=${1}"
+	    shift
+	    ;;
+	-g|--group)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    group="--group=${1}"
+	    shift
+	    ;;
+	-i|--interval)
+	    if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for ${opt}\n" >&2; exit 100; fi
+	    default_interval="${1}"
+	    shift
+	    ;;
+	-h|--help)
+	    usage
+	    exit 0
+	    ;;
+	--)
+	    break
+	    ;;
+	*)
+	    printf "\n${script_name}: you specified an invalid option or provided an unexpected argument: \"${opt}\"\n\n" >&2
+	    usage >&2
+	    exit 1
+	    ;;
+    esac
 done
 
 typeset -i nerrs=0
diff --git a/agent/util-scripts/pbench-register-tool-trigger b/agent/util-scripts/pbench-register-tool-trigger
--- a/agent/util-scripts/pbench-register-tool-trigger
+++ b/agent/util-scripts/pbench-register-tool-trigger
@@ -19,52 +19,49 @@ stop_trigger=""
 
 function usage() {
 	printf "usage:\n"
-	printf "$script_name --group=<tool group> --start-trigger=<string to match> --stop-trigger=<string to match>"
+	printf "${script_name} --group=<tool group> --start-trigger=<string to match> --stop-trigger=<string to match>"
 }
 
 # Process options and arguments
-opts=$(getopt -q -o h --longoptions "help,group:,start-trigger:,stop-trigger:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
-	printf "\n"
-	printf "%s\n" $*
-	printf "$script_name: you specified an invalid option\n\n"
-	usage
-	exit 1
+opts=$(pbench-argparse -q -o h --longoptions "help,group:,start-trigger:,stop-trigger:" -n "${script_name}" -- "${@}")
+sts=${?}
+if [[ ${sts} -ne 0 ]]; then
+	printf -- "\n" >&2
+	usage >&2
+	exit ${sts}
 fi
-eval set -- "$opts";
+
+eval set -- "${opts}"
 while true; do
-	case "$1" in
-		--start-trigger)
-		shift;
-		if [ -n "$1" ]; then
-			start_trigger="$1"
-			shift;
-		fi
+	opt=${1}
+	shift
+	case "${opt}" in
+	--start-trigger)
+		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --start-trigger\n" >&2; exit 100; fi
+		start_trigger="$1"
+		shift
 		;;
-		--stop-trigger)
-		shift;
-		if [ -n "$1" ]; then
-			stop_trigger="$1"
-			shift;
-		fi
+	--stop-trigger)
+		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --stop-trigger\n" >&2; exit 100; fi
+		stop_trigger="$1"
+		shift
 		;;
-		--group)
-		shift;
-		if [ -n "$1" ]; then
-			group="$1"
-			shift;
-		fi
+	--group)
+		if [[ -z "${1}" ]]; then printf -- "Logic bomb! empty argument for --group\n" >&2; exit 100; fi
+		group="$1"
+		shift
 		;;
-                -h|--help)
-                usage;
+	-h|--help)
+                usage
                 exit 0
                 ;;
-		--)
-		shift;
-		break;
+	--)
+		break
 		;;
-		*)
-		shift;
+	*)
+		printf "\n${script_name}: you specified an invalid option or provided an unexpected argument\n\n" >&2
+		usage >&2
+		exit 1
 		;;
 	esac
 done
