Require `--user` for `pbench-move/copy-results`
Ahead of the work coming for the pbench server being endowed with the
notion of a user, we require results being moved to provide the `--user`
option for `pbench-move-results`.

diff --git a/agent/util-scripts/pbench-move-results b/agent/util-scripts/pbench-move-results
--- a/agent/util-scripts/pbench-move-results
+++ b/agent/util-scripts/pbench-move-results
@@ -7,9 +7,31 @@ pbench_bin="$(realpath -e ${script_path}/..)"
 # source the base script
 . "${pbench_bin}"/base
 
+_op=${script_name#pbench-}
+_op=${_op%-results}
+_op_pt="${_op}d"
+if [[ "${_op}" == "copy" ]]; then
+    _op_pt="copied"
+fi
+
 function usage() {
-    printf "usage:\n"
-    printf "${script_name} [--help] [--controller=<controller>] [--user=<user>] [--prefix=<path>] [--xz-single-threaded] [--show-server]\n"
+    printf -- "usage:\n%s [--help] --user=<user> [--controller=<controller>]" "${script_name}"
+    printf -- " [--prefix=<path>] [--xz-single-threaded] [--show-server]\n"
+    printf -- "\nThe '--user' option value is required if not provided by the\n"
+    printf -- "'PBENCH_USER' environment variable; otherwise, the value provided\n"
+    printf -- "on the command line will override any value provided by the\n"
+    printf -- "environment.\n"
+    printf -- "The '--controller' option may be used to override the value\n"
+    printf -- "provided by the 'PBENCH_CONTROLLER' environment variable; if\n"
+    printf -- "neither value is available, the result of 'hostname -f' is used.\n"
+    printf -- "(If no value is available, the command will exit with an error.)\n"
+    printf -- "\nThe '--prefix' option allows the user to specify an optional\n"
+    printf -- "directory path hierarchy to be used when displaying the result\n"
+    printf -- "tar balls on the pbench server.\n"
+    printf -- "\nThe '--show-server' will not ${_op} any results, but resolve and\n"
+    printf -- "then display the pbench server destination for results.\n"
+    printf -- "\nThe '--xz-single-threaded' will force the use of a single\n"
+    printf -- "thread for locally compressing the result tar balls.\n"
 }
 
 function missing_arg() {
@@ -38,26 +60,26 @@ while true; do
     case "${opt}" in
         -c|--controller)
             if [[ -n "${1}" ]]; then
-        	controller="${1}"
-        	shift;
+                controller="${1}"
+                shift
             else
-        	missing_arg "${opt}"
+                missing_arg "${opt}"
             fi
             ;;
         -u|--user)
             if [[ -n "${1}" ]]; then
-        	user="${1}"
-        	shift;
+                user="${1}"
+                shift
             else
-        	missing_arg "${opt}"
+                missing_arg "${opt}"
             fi
             ;;
         -p|--prefix)
             if [[ -n "${1}" ]]; then
-        	prefix="${1}"
-        	shift;
+                prefix="${1}"
+                shift
             else
-        	missing_arg "${opt}"
+                missing_arg "${opt}"
             fi
             ;;
         -x|--xz-single-threaded)
@@ -68,10 +90,10 @@ while true; do
             ;;
         -h|--help)
             usage
-   	    exit 0
+            exit 0
             ;;
         --)
-            break;
+            break
             ;;
         *)
             printf "\n${script_name}: you specified an invalid option or an unexpected argument\n\n" >&2
@@ -83,11 +105,16 @@ done
 if [[ -z "${controller}" ]]; then
     controller=${_pbench_full_hostname}
     if [[ -z "${controller}" ]]; then
-        error_log "Missing controller name (should be \"hostname -f\" value)"
+        error_log "'--controller' is required, because no 'hostname' is configured"
         exit 1
     fi
 fi
 validate_hostname "${controller}" "controller"
+
+if [[ -z "${user}" ]]; then
+    error_log "Missing required 'user' value (provided either by the '--user' option or the 'PBENCH_USER' environment variable)"
+    exit 1
+fi
 
 # Move into pbench run collection directory
 cd ${pbench_run} >/dev/null
@@ -120,7 +147,7 @@ fi
 # ask the server where to send the tarballs
 results_webserver=$(pbench-config webserver results)
 if [[ -z "${results_webserver}" ]]; then
-    error_log "ERROR: No web server host configured from which we can fetch the FQDN of the host to which we copy/move results"
+    error_log "ERROR: No web server host configured from which we can fetch the FQDN of the host to which we ${_op} results"
     debug_log "\"webserver\" variable in \"results\" section not set"
     exit 1
 fi
@@ -134,8 +161,8 @@ rel=$(printf -- "%s" "${_info}" | grep Release | awk '{ print $3 }')
 if [[ -z "${rel}" ]]; then
     rel="unknown"
 fi
-# User-Agent HTTP header: <pbench-agent-ver-rel>:<FQDN>:<$USER>:<full path of this script>""
-user_agent="pbench-agent-${ver}-${rel}:${_pbench_full_hostname}:${USER}:${script_name}"
+# User-Agent HTTP header: <pbench-agent-ver-rel>:<FQDN>:<${USER}>:${controller}:${user}:<name of this script>""
+user_agent="pbench-agent-${ver}-${rel}:${_pbench_full_hostname}:${USER}:${controller}:${user}:${script_name}"
 
 results_host_info_url=$(pbench-config host_info_url results)
 results_host_info=$(curl -s -A "${user_agent}" -L "${results_host_info_url}")
@@ -216,17 +243,12 @@ while read -r dir; do
     # contain the tarball and the md5 file (as ${tb}.tar.xz.md5.check); pass
     # that information on to pbench-make-result-tb.
     result_dir=$(basename ${dir})
-    if [[ -n "${user}" ]]; then
-        user_arg="--user ${user}"
-    else
-        user_arg=""
-    fi
     if [[ -n "${prefix}" ]]; then
-        prefix_arg="--prefix ${prefix}"
+        prefix_arg=" --prefix ${prefix}"
     else
         prefix_arg=""
     fi
-    result_tb_name=$(pbench-make-result-tb --result-dir "${result_dir}" --target-dir "${tmp}/${controller}" ${user_arg} ${prefix_arg} --xz-single-threaded "${xz_single_threaded}")
+    result_tb_name=$(pbench-make-result-tb --result-dir "${result_dir}" --target-dir "${tmp}/${controller}" --user ${user}${prefix_arg} --xz-single-threaded "${xz_single_threaded}")
     if [[ ${?} -ne 0 ]]; then
         # Messaging already handled by pbench-make-result-tb
         continue
@@ -247,7 +269,7 @@ while read -r dir; do
         continue
     fi
 
-    if [[ "$script_name" == "pbench-move-results" ]]; then
+    if [[ "${_op}" == "move" ]]; then
         rm -r ${result_dir}
         if [[ ${?} -ne 0 ]]; then
             error_log "UNEXPECTED ERROR: rm failed to remove the ${result_dir} directory hierarchy"
@@ -265,11 +287,6 @@ done < ${tmp}/results.lis
 
 let anything=runs_copied+failures
 if [[ $anything -gt 0 ]]; then
-    if [[ "$script_name" == "pbench-move-results" ]]; then
-        op="moved"
-    else
-        op="copied"
-    fi
-    debug_log "successfully $op $runs_copied runs, encountered $failures failures"
+    debug_log "successfully ${_op_pt} $runs_copied runs, encountered $failures failures"
 fi
 exit $failures
