Prometheus/Node_Exporter Full V1 Integration Commit
This work adds the notion of a "collector" to the Tool Data Sink, and
"tools" which run continuously without cycling through the "start", "stop",
and "send" phases.  The collector is responsible for continuously pulling
data from those tools which are now started during the new "init" phase,
and stopped during the new "end" phase.

The first actual implementation of this kind of collector is for the
prometheus data collection environment, where a `node-exporter` "tool" is
run providing a end-point for a prometheus server "collector" to pull data
from it and store it locally off the run directory (`${benchmark_run_dir}`,
e.g. `${benchmark_run_dir}/collector/prometheus`).

diff --git a/agent/util-scripts/pbench-start-tools b/agent/util-scripts/pbench-start-tools
--- a/agent/util-scripts/pbench-start-tools
+++ b/agent/util-scripts/pbench-start-tools
@@ -11,10 +11,14 @@ action=${_suffix%%-*}
 . "${pbench_bin}"/base
 
 <<<<<<< HEAD
+<<<<<<< HEAD
 if [[ "${action}" != "end" && "${action}" != "init" && "${action}" != "kill" && "${action}" != "send" && "${action}" != "start" && "${action}" != "stop" ]]; then
 =======
 if [[ "${action}" != "kill" && "${action}" != "send" && "${action}" != "start" && "${action}" != "stop" ]]; then
 >>>>>>> First pass implementation of the "Tool Meister"
+=======
+if [[ "${action}" != "end" && "${action}" != "init" && "${action}" != "kill" && "${action}" != "send" && "${action}" != "start" && "${action}" != "stop" ]]; then
+>>>>>>> Prometheus/Node_Exporter Full V1 Integration Commit
 	error_log "[${script_name}] action \"${action}\" is not supported"
 	exit 1
 fi
@@ -28,6 +32,7 @@ def_group="default"
 group="${def_group}"
 dir=""
 
+<<<<<<< HEAD
 <<<<<<< HEAD
 function usage {
 	printf "The following are required:\n\n"
@@ -47,12 +52,26 @@ if [[ ${?} -ne 0 ]]; then
 <<<<<<< HEAD
 	usage >&2
 =======
+=======
+function usage {
+>>>>>>> Prometheus/Node_Exporter Full V1 Integration Commit
 	printf "The following are required:\n\n"
 	printf -- "\t-g str --group=str, str = a tool group used in a benchmark\n"
 	printf -- "\t                          (the default group is '%s')\n\n" "${def_group}"
 	printf -- "\t-d str --dir=str, str = a directory where %s\n" "${script_name}"
 	printf -- "\t                        will store and process data\n"
+<<<<<<< HEAD
 >>>>>>> First pass implementation of the "Tool Meister"
+=======
+}
+
+# Process options and arguments
+
+opts=$(getopt -q -o d:g: --longoptions "dir:,group:" -n "getopt.sh" -- "${@}")
+if [[ ${?} -ne 0 ]]; then
+	printf "\n%s: you specified an invalid option\n\n" "${script_name}"
+	usage >&2
+>>>>>>> Prometheus/Node_Exporter Full V1 Integration Commit
 	exit 1
 fi
 eval set -- "${opts}"
@@ -82,17 +101,25 @@ done
 if [[ -z "${group}" ]]; then
 	printf -- "ERROR: required tool group parameter missing.\n" >&2
 <<<<<<< HEAD
+<<<<<<< HEAD
 	usage >&2
 =======
 >>>>>>> First pass implementation of the "Tool Meister"
+=======
+	usage >&2
+>>>>>>> Prometheus/Node_Exporter Full V1 Integration Commit
 	exit 1
 fi
 if [[ -z "${dir}" ]]; then
 	printf -- "ERROR: required directory argument missing.\n" >&2
 <<<<<<< HEAD
+<<<<<<< HEAD
 	usage >&2
 =======
 >>>>>>> First pass implementation of the "Tool Meister"
+=======
+	usage >&2
+>>>>>>> Prometheus/Node_Exporter Full V1 Integration Commit
 	exit 1
 fi
 
