Fix pbench-list-tools --name
Fixes #2269

Add -d option to the ls command to avoid listing contents of the
tools-default directory.

Clean up the --help option.

Add some basic unit tests for pbench-list-tools. Renumbered the
unit tests slightly to bring the clear-tools ones together (and
create a hole for the new pbench-list-tools ones).

diff --git a/agent/util-scripts/pbench-list-tools b/agent/util-scripts/pbench-list-tools
--- a/agent/util-scripts/pbench-list-tools
+++ b/agent/util-scripts/pbench-list-tools
@@ -19,24 +19,28 @@ with_options=0
 
 # Process options and arguments
 
-opts=$(getopt -q -o tn:og: --longoptions "with-options,name:,group:" -n "getopt.sh" -- "$@");
-if [ $? -ne 0 ]; then
+function usage() {
 	printf "\n"
-	printf "$script_name: you specified an invalid option\n\n"
 	printf "The following options are available (use neither, one, or the other, but not both):\n\n"
 	printf -- "\t-n str --name=str, list the perftool groups which str is used\n"
 	printf "\n"
 	printf -- "\t-g str --group=str, list the tools used in this str\n"
 	printf "\n"
 	printf -- "\t-o --with-options, list the options with each tool\n"
+}
 
-
+opts=$(getopt -q -o hon:g: --longoptions "help,with-options,name:,group:" -n "getopt.sh" -- "$@");
+if [ $? -ne 0 ]; then
+	printf -- "\n${*}\n" >&2
+	printf -- "${script_name}: you specified an invalid option\n\n" >&2
+	usage >&2
 	exit 1
 fi
+
 eval set -- "$opts";
 while true; do
 	case "$1" in
-		-n|--name)
+	-n|--name)
 		shift;
 		if [ -n "$1" -a "$group" = "" ]; then
 			name="$1"
@@ -46,7 +50,7 @@ while true; do
 			exit 1
 		fi
 		;;
-		-g|--group)
+	-g|--group)
 		shift;
 		if [ -n "$1" -a "$name" = "" ]; then
 			group="$1"
@@ -56,20 +60,22 @@ while true; do
 			exit 1
 		fi
 		;;
-		-o|--with-options)
+	-o|--with-options)
 		shift;
 		with_options=1
 		with_options_opt="--with-options" # used if we ssh for remote list
 		;;
-		--)
+	-h|--help)
+		usage
+		exit 0
+		;;
+	--)
 		shift;
 		break;
 		;;
-                *)
-                    break
-                    ;;
 	esac
 done
+
 if [ -d "$pbench_run" ]; then
 	pushd "$pbench_run" >/dev/null
 	if [ -z $name ]; then
@@ -114,7 +120,7 @@ if [ -d "$pbench_run" ]; then
 		done
 	else 
 		# list the groups which include this tool
-		for group in `/bin/ls tools-* 2>/dev/null | sed -e s/^tools-//g`; do
+		for group in `/bin/ls -d tools-* 2>/dev/null | sed -e s/^tools-//g`; do
 			if /bin/ls tools-$group | grep -q "^$name"; then
 				groups="$groups $group"
 			fi
