Properly set the benchmark_run_dir for all tests
We need to ensure that the environment all the util-scripts are tested
under closely matches the environment in which they are actually invoked
(via bench-scripts, etc.). We were being pretty loose with the directory
used, so this commit tightens that down a bit.

We also make sure we run all unit tests by changing the current working
directory to the test environment we setup.

We consistently use `[[` conditional form, and we also use `${}` variable
references everywhere.

diff --git a/agent/util-scripts/unittests b/agent/util-scripts/unittests
--- a/agent/util-scripts/unittests
+++ b/agent/util-scripts/unittests
@@ -1,67 +1,67 @@
 #!/bin/bash
 export LANG=C
 export LC_ALL=C
-_tdir=$(dirname $(readlink -f $0))
+_tdir=$(dirname $(readlink -f ${0}))
 
 _testroot=/var/tmp/pbench-test-utils
-mkdir -p $_testroot
-if [[ ! -d $_testroot ]]; then
-    echo "ERROR: failed to create test root directory, \"$_testroot\"" >&2
+mkdir -p ${_testroot}
+if [[ ! -d ${_testroot} ]]; then
+    echo "ERROR: failed to create test root directory, \"${_testroot}\"" >&2
     exit 1
 fi
-rm -rf $_testroot/*
-if [[ $? -gt 0 ]]; then
-    echo "ERROR: failed to empty test root directory, \"$_testroot\"" >&2
+rm -rf ${_testroot}/*
+if [[ ${?} -gt 0 ]]; then
+    echo "ERROR: failed to empty test root directory, \"${_testroot}\"" >&2
     exit 1
 fi
-export _testout=$_testroot/output.txt
-export _testlog=$_testroot/test-execution.log
-export _testdir=$_testroot/pbench
+export _testout=${_testroot}/output.txt
+export _testlog=${_testroot}/test-execution.log
+export _testdir=${_testroot}/pbench
 
 # Copy util-scripts execution environment to _testroot
-_testopt=$_testroot/opt/pbench-agent
+_testopt=${_testroot}/opt/pbench-agent
 res=0
-mkdir -p $_testopt/config $_testopt/util-scripts $_testopt/tool-scripts $_testopt/lib $_testopt/unittest-scripts
-let res=res+$?
-cp -L $_tdir/../base $_testopt/
-let res=res+$?
-cp -rL $_tdir/../config/* $_testopt/config/
-let res=res+$?
-scripts="$_tdir/pbench-*"
-for script in $scripts ; do
-    cp -L $script $_testopt/util-scripts/
-    let res=res+$?
+mkdir -p ${_testopt}/config ${_testopt}/util-scripts ${_testopt}/tool-scripts ${_testopt}/lib ${_testopt}/unittest-scripts
+let res=res+${?}
+cp -L ${_tdir}/../base ${_testopt}/
+let res=res+${?}
+cp -rL ${_tdir}/../config/* ${_testopt}/config/
+let res=res+${?}
+scripts="${_tdir}/pbench-*"
+for script in ${scripts}; do
+    cp -L ${script} ${_testopt}/util-scripts/
+    let res=res+${?}
 done
-cp -rL $_tdir/../tool-scripts/* $_testopt/tool-scripts/
-let res=res+$?
-cp -rL $_tdir/../lib/* $_testopt/lib/
-let res=res+$?
-cp -rL $_tdir/test-bin/* $_testopt/unittest-scripts/
-let res=res+$?
+cp -rL ${_tdir}/../tool-scripts/* ${_testopt}/tool-scripts/
+let res=res+${?}
+cp -rL ${_tdir}/../lib/* ${_testopt}/lib/
+let res=res+${?}
+cp -rL ${_tdir}/test-bin/* ${_testopt}/unittest-scripts/
+let res=res+${?}
 
 if [[ $res -ne 0 ]]; then
     echo "ERROR: failed to construct unittest execution directory hierarchy" \
-         "under, \"$_testroot\"" >&2
+         "under, \"${_testroot}\"" >&2
     exit 1
 fi
 
 function remove_path {
-    # PATH ($2) => /bin:/opt/a dir/bin:/sbin
-    WORK=:$2:
+    # PATH (${2}) => /bin:/opt/a dir/bin:/sbin
+    WORK=:${2}:
     # WORK => :/bin:/opt/a dir/bin:/sbin:
-    REMOVE=$1
-    WORK=${WORK/:$REMOVE:/:}
+    REMOVE=${1}
+    WORK=${WORK/:${REMOVE}:/:}
     # WORK => :/bin:/sbin:
     WORK=${WORK%:}
     WORK=${WORK#:}
-    #PATH=$WORK
+    #PATH=${WORK}
     # PATH => /bin:/sbin
-    echo $WORK
+    echo ${WORK}
 }
-PATH=$(remove_path /opt/pbench-agent/bench-scripts $PATH)
-PATH=$(remove_path /opt/pbench-agent/util-scripts $PATH)
+PATH=$(remove_path /opt/pbench-agent/bench-scripts ${PATH})
+PATH=$(remove_path /opt/pbench-agent/util-scripts ${PATH})
 # Allows us to intercept scp, ssh, rsync, etc.
-export PATH=$_testopt/unittest-scripts:$_testopt/util-scripts:$_testopt/tool-scripts:$PATH
+export PATH=${_testopt}/unittest-scripts:${_testopt}/util-scripts:${_testopt}/tool-scripts:${PATH}
 
 # Fixed timestamp output
 export _PBENCH_BENCH_TESTS=1
@@ -71,63 +71,71 @@ res=0
 function _run {
     local sts
 
-    tname=$1
+    tname=${1}
     shift
-    tscrpt=$1
+    tscrpt=${1}
     shift
 
-    echo "$tname $tscrpt $@"
-    echo "+++ Running $tname $tscrpt $@" >> $_testout
+    pushd ${_testdir} > /dev/null 2>&1
+    if [[ ${?} -ne 0 ]]; then
+        exit 1
+    fi
 
-    CONFIG=$_testopt/config/pbench-agent.cfg \
-            pbench_install_dir=$_testopt \
-            pbench_run=$_testdir \
-            pbench_log=$_testdir/pbench.log \
-            pbench_bspp_dir=$_testopt/bench-scripts/postprocess \
-            pbench_lib_dir=$_testopt/lib \
-            benchmark_bin=$_testopt/unittest-scripts/bm \
-            benchmark_run_dir=$_testdir \
-            $tscrpt $@ >> $_testout 2>&1
-    sts=$?
+    echo "${tname} ${tscrpt} ${@}"
+    echo "+++ Running ${tname} ${tscrpt} ${@}" >> ${_testout}
 
-    echo "--- Finished $tname $tscrpt (status=$sts)" >> $_testout
-    return $sts
+    ${tscrpt} ${@} >> ${_testout} 2>&1
+    sts=${?}
+
+    popd > /dev/null 2>&1
+    if [[ ${?} -ne 0 ]]; then
+        exit 1
+    fi
+
+    echo "--- Finished $tname ${tscrpt} (status=${sts})" >> ${_testout}
+    return ${sts}
 }
 
 function _save_tree {
     # Save state of the tree
-    echo "+++ pbench tree state" >> $_testout
-    find $_testdir | sort >> $_testout
-    if [ -d $_testdir/tools-default ] ;then
-        pushd $_testdir/tools-default >/dev/null
-        for x in $(ls) ;do
-            echo $_testdir/tools-default/$x:
-            cat $x
+    echo "+++ pbench tree state" >> ${_testout}
+    find ${_testdir} | sort >> ${_testout}
+    if [[ -d "${_testdir}/tools-default" ]]; then
+        pushd "${_testdir}/tools-default" >/dev/null
+        for x in $(ls); do
+            echo "${_testdir}/tools-default/${x}:"
+            cat ${x}
         done
         popd >/dev/null
-    fi >> $_testout
-    for x in $(find $_testdir/tmp -type f) ;do
-        echo $x:
-        sed '/start_run/d' $x
-    done >> $_testout
-    echo "--- pbench tree state" >> $_testout
+    fi >> ${_testout}
+    for x in $(find ${_testdir}/tmp -type f); do
+        echo ${x}:
+        sed '/start_run/d' ${x}
+    done >> ${_testout}
+    echo "--- pbench tree state" >> ${_testout}
 }
 
 function _dump_logs {
     # Dump the state of any generated script logs
-    if [[ -f ${_testdir}/metadata.log ]]; then
-        echo "+++ metadata.log file contents" >> ${_testout}
-        grep -HvF "\-\-should-n0t-ex1st--" ${_testdir}/metadata.log >> ${_testout} 2>&1
-        echo "--- metadata.log file contents" >> ${_testout}
-    fi
     if [[ -f ${_testdir}/pbench.log ]]; then
         echo "+++ pbench.log file contents" >> ${_testout}
-        grep -HvF "\-\-should-n0t-ex1st--" ${_testdir}/pbench.log >> ${_testout} 2>&1
+        cat ${_testdir}/pbench.log >> ${_testout} 2>&1
         echo "--- pbench.log file contents" >> ${_testout}
     fi
+    for mdlog in ${_testdir}/*/metadata.log; do
+        if [[ -f ${mdlog} ]]; then
+            mddir=$(basename $(dirname "${mdlog}"))
+            if [[ "${mddir}" == "tmp" ]]; then
+                continue
+            fi
+            echo "+++ ${mddir}/metadata.log file contents" >> ${_testout}
+            cat ${_testdir}/${mddir}/metadata.log >> ${_testout} 2>&1
+            echo "--- ${mddir}/metadata.log file contents" >> ${_testout}
+        fi
+    done
     if [[ -f ${_testlog} ]]; then
         echo "+++ test-execution.log file contents" >> ${_testout}
-        grep -HvF "\-\-should-n0t-ex1st--" ${_testlog} >> ${_testout} 2>&1
+        cat ${_testlog} >> ${_testout} 2>&1
         echo "--- test-execution.log file contents" >> ${_testout}
         rm -f ${_testlog}
     fi
@@ -135,64 +143,92 @@ function _dump_logs {
 
 function _verify_output {
     local sts tname tscrpt expected_status
-    sts=$1
-    tname=$2
-    tscrpt=$3
+    sts=${1}
+    tname=${2}
+    tscrpt=${3}
     expected_status=${4:-0}
     # fix up any pids that have snuck into the output.
     sed -e 's;tmp/\([a-z-]*\).[0-9][0-9]*;tmp/\1.NNNNN;g' \
         -e 's;raw_size = [0-9][0-9]*;raw_size = #####;g' \
-        -e 's;tar up [0-9][0-9]* bytes;tar up ##### bytes;g' $_testout |
-        diff -c $_tdir/gold/${tscrpt}/${tname}.txt -
-    if [[ $? -gt 0 ]]; then
-        echo "FAIL - $tname"
-        mv $_testout $_testroot/${tname}_output.txt
+        -e 's;tar up [0-9][0-9]* bytes;tar up ##### bytes;g' ${_testout} |
+        diff -c ${_tdir}/gold/${tscrpt}/${tname}.txt -
+    if [[ ${?} -gt 0 ]]; then
+        echo "FAIL - ${tname}"
+        mv ${_testout} ${_testroot}/${tname}_output.txt
         sts=1
     else
-        if [[ $sts -eq 0 ]]; then
-            echo "PASS - $tname"
-            rm $_testout
-        elif [[ $sts -eq $expected_status ]] ; then
-            echo "PASS - $tname exited with expected status: $sts"
-            rm $_testout
+        if [[ ${sts} -eq 0 ]]; then
+            echo "PASS - ${tname}"
+            rm ${_testout}
+        elif [[ ${sts} -eq ${expected_status} ]]; then
+            echo "PASS - ${tname} exited with expected status: ${sts}"
+            rm ${_testout}
             sts=0
         else
-            echo "FAIL - $tname: PASS output but execution returned non-zero exit status"
+            echo "FAIL - ${tname}: PASS output but execution returned non-zero exit status"
         fi
     fi
-    return $sts
+    return ${sts}
 }
 
 function _setup_state {
     local tool
     local tst
-    tst=$1
-    tool=$2
+    tst=${1}
+    tool=${2}
 
-    cp -a $_testopt/config/pbench-agent.cfg.example $_testopt/config/pbench-agent.cfg
-    if [[ $? -ne 0 ]]; then
+    cp -a ${_testopt}/config/pbench-agent.cfg.example ${_testopt}/config/pbench-agent.cfg
+    if [[ ${?} -ne 0 ]]; then
         echo "ERROR: failed to create default pbench-agent.cfg" >&2
         exit 1
     fi
-    mkdir $_testdir
-    if [[ $? -ne 0 ]]; then
-        echo "ERROR: failed to create test pbench directory, \"$_testdir\"" >&2
+    export CONFIG=${_testopt}/config/pbench-agent.cfg
+
+    mkdir ${_testdir}
+    if [[ ${?} -ne 0 ]]; then
+        echo "ERROR: failed to create test pbench directory, \"${_testdir}\"" >&2
         exit 1
     fi
-    if [ ! -z "$tool" -a ! -z "$tst" ] ;then
-        if [ -d $_tdir/samples/$tool/$tst ] ;then
-            cp -r $_tdir/samples/$tool/$tst/* $_testroot
+    if [[ ! -z "${tool}" && ! -z "${tst}" ]]; then
+        if [[ -d ${_tdir}/samples/${tool}/${tst} ]]; then
+            cp -r ${_tdir}/samples/${tool}/${tst}/* ${_testroot}
         fi
     fi
+
+    export pbench_install_dir=${_testopt}
+    export pbench_run=${_testdir}
+    export pbench_log=${_testdir}/pbench.log
+    export pbench_bspp_dir=${_testopt}/bench-scripts/postprocess
+    export pbench_lib_dir=${_testopt}/lib
+    export benchmark="fake-bm"
+    export benchmark_bin=${_testopt}/unittest-scripts/bm
+
+    # Discover the "benchmark_run_dir"
+    bm_run_dir="$(ls -1 ${_testdir} 2>/dev/null | grep -vE 'tmp|tools-.+|tool-triggers|tools\.default' 2>/dev/null)"
+    if [[ -z "${bm_run_dir}" ]]; then
+        bm_run_dir="mock-run"
+    fi
+    export benchmark_run_dir=${_testdir}/${bm_run_dir}
 }
 
 function _reset_state {
-    rm -f $_testopt/config/pbench-agent.cfg
-    rm -rf $_testdir
-    if [[ -d $_testdir ]]; then
+    rm ${_testopt}/config/pbench-agent.cfg
+    unset CONFIG
+
+    rm -rf ${_testdir}
+    if [[ -d ${_testdir} ]]; then
         echo "ERROR: unable to remove pbench hierarchy" >&2
         exit 1
     fi
+
+    unset benchmark_run_dir
+    unset benchmark_bin
+    unset benchmark
+    unset pbench_lib_dir
+    unset pbench_bspp_dir
+    unset pbench_log
+    unset pbench_run
+    unset pbench_install_dir
 }
 
 let errs=0
@@ -266,16 +302,16 @@ declare -A tools=(
 
 declare -A options=(
     [test-00]="--name=mpstat --group=default -- --interval=10"
-    [test-01]="--dir=$_testdir/tmp beg"
-    [test-02]="--dir=$_testdir/tmp beg"
-    [test-03]="--dir=$_testdir/tmp beg"
-    [test-04]="--dir=$_testdir/tmp beg"
-    [test-05]="--dir=$_testdir/tmp"
-    [test-06]="--dir=$_testdir/tmp"
-    [test-07]="--dir=$_testdir/tmp"
-    [test-08]="--dir=$_testdir/tmp"
-    [test-09]="--dir=$_testdir/tmp"
-    [test-10]="--dir=$_testdir/tmp"
+    [test-01]="--dir=${_testdir}/mock-run beg"
+    [test-02]="--dir=${_testdir}/mock-run beg"
+    [test-03]="--dir=${_testdir}/mock-run beg"
+    [test-04]="--dir=${_testdir}/mock-run beg"
+    [test-05]="--dir=${_testdir}/mock-run/mock-iteration"
+    [test-06]="--dir=${_testdir}/mock-run/mock-iteration"
+    [test-07]="--dir=${_testdir}/mock-run/mock-iteration"
+    [test-08]="--dir=${_testdir}/mock-run/mock-iteration"
+    [test-09]="--dir=${_testdir}/mock-run/mock-iteration"
+    [test-10]="--dir=${_testdir}/mock-run/mock-iteration"
     # fubar is assumed to *NOT* exist
     [test-11]="--remote=fubar"
     [test-11.2]="--interval=10"
@@ -298,14 +334,14 @@ declare -A options=(
     # verify --group option works along side --no-install
     [test-11.12]="--group=other --no-install"
     [test-11.13]="--help"
-    [test-13]="--dir=$_testdir/tmp --group=default --iteration=1"
-    [test-14]="$_testdir/tmp/pbench-agent.cfg"
+    [test-13]="--dir=${_testdir}/mock-run/mock-iteration --group=default --iteration=1"
+    [test-14]="${_testdir}/tmp/pbench-agent.cfg"
     [test-15]="--group=default --start-trigger=\"START DEFAULT\" --stop-trigger=\"STOP DEFAULT\""
     [test-17]="--group=default"
     [test-18]="--group=foo"
-    [test-20]="--dir=$_testdir/tmp --group=default --iteration=1"
+    [test-20]="--dir=${_testdir}/mock-run/mock-iteration --group=default --iteration=1"
     [test-21]="--remote=fubar2"
-    [test-22]="--dir=$_testdir end"
+    [test-22]="--dir=${_testdir}/mock-run end"
     [test-23]="--help"
     [test-24]="--options"
     [test-25]="--check --sysinfo=all"
@@ -353,14 +389,9 @@ declare -A expected_status=(
 )
 
 declare -A pre_hooks=(
-    [test-01]='export benchmark=fake-bm'
-    [test-02]='export benchmark=fake-bm'
-    [test-03]='export benchmark=fake-bm'
-    [test-04]='export benchmark=fake-bm'
-    [test-14]='rm $_testopt/config/pbench-agent.cfg; sed -i "s;_REPLACE_ME_;$_testopt;g" $_testdir/tmp/pbench-agent.cfg'
-    [test-20]='mkdir -p $_testdir/tmp/tools-default/iostat; touch $_testdir/tmp/tools-default/iostat/iostat-stdout.txt'
-    [test-22]='export benchmark=fake-bm'
-    [test-33]='(echo "+++ setup pbench results dir time stamps"; touch --date="2019-01-01 12:00:42" $_testdir/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.42; touch --date="2019-01-01 12:00:43" $_testdir/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.43; touch --date="2019-01-01 12:00:44" $_testdir/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.44; echo "--- setup pbench results dir time stamps") >> $_testout'
+    [test-14]='rm ${_testopt}/config/pbench-agent.cfg; sed -i "s;_REPLACE_ME_;${_testopt};g" ${_testdir}/tmp/pbench-agent.cfg'
+    [test-20]='mkdir -p ${_testdir}/mock-run/mock-iteration/tools-default/iostat; touch ${_testdir}/mock-run/mock-iteration/tools-default/iostat/iostat-stdout.txt'
+    [test-33]='(echo "+++ setup pbench results dir time stamps"; touch --date="2019-01-01 12:00:42" ${_testdir}/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.42; touch --date="2019-01-01 12:00:43" ${_testdir}/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.43; touch --date="2019-01-01 12:00:44" ${_testdir}/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.44; echo "--- setup pbench results dir time stamps") >> ${_testout}'
     [test-45]='mkdir ${_testdir}/tmp; printf -- "# good list\none.example.com\ntwo.example.com,labelTwo\n\nthree.example.com\n" > ${_testdir}/tmp/remotes.lis'
     [test-46]='mkdir ${_testdir}/tmp; printf -- "# bad list\none.example.com\ntwo.example.com,labelTwo\n\nthree.example.com,labelThree,junk\n" > ${_testdir}/tmp/remotes.lis'
     [test-47]='mkdir ${_testdir}/tmp; printf -- "# good list with no labels\none.example.com\ntwo.example.com\nthree.example.com\n" > ${_testdir}/tmp/remotes.lis'
@@ -368,54 +399,44 @@ declare -A pre_hooks=(
 )
 
 declare -A post_hooks=(
-    [test-01]='unset benchmark'
-    [test-02]='unset benchmark'
-    [test-03]='unset benchmark'
-    [test-04]='unset benchmark'
-    [test-22]='unset benchmark'
-    [test-31]='(echo "+++ metadata.log file contents"; cat ${_testdir}/pbench-user-benchmark_ndk-test-1_2018.05.23T03.21.32/metadata.log; echo "--- metadata.log file contents") >> ${_testout}'
-    [test-39]='(echo "+++ metadata.log file contents"; cat ${_testdir}/pbench-user-benchmark_ndk-test-1_2019.09.27T14.21.31/metadata.log; echo "--- metadata.log file contents") >> ${_testout}'
-    [test-40]='(echo "+++ metadata.log file contents"; cat ${_testdir}/pbench-user-benchmark_pap-test-1_2019.09.27T14.21.32/metadata.log; echo "--- metadata.log file contents") >> ${_testout}'
-    [test-41]='(echo "+++ metadata.log file contents"; cat ${_testdir}/pbench-user-benchmark_rht-test-1_2019.09.27T14.21.33/metadata.log; echo "--- metadata.log file contents") >> ${_testout}'
-    [test-49]='(echo "+++ metadata.log file contents"; cat ${_testdir}/pbench-user-benchmark_ndk-test30%-1_2018.05.23T03.21.32/metadata.log; echo "--- metadata.log file contents") >> ${_testout}'
 )
 
-tests="$*"
-if [ -z "$tests" ] ;then
+tests="${*}"
+if [[ -z "${tests}" ]]; then
     typeset -i len=${#tools[@]}
-    len=$len-1
+    len=${len}-1
     tests=$(echo ${!tools[*]} | tr ' ' '\n' | sort)
 fi
 
-for tst in $tests; do
-    tool=${tools[$tst]}
-    opts=${options[$tst]}
-    status=${expected_status[$tst]}
-    pre_hook=${pre_hooks[$tst]}
-    post_hook=${post_hooks[$tst]}
+for tst in ${tests}; do
+    tool=${tools[${tst}]}
+    opts=${options[${tst}]}
+    status=${expected_status[${tst}]}
+    pre_hook=${pre_hooks[${tst}]}
+    post_hook=${post_hooks[${tst}]}
 
-    _setup_state $tst $tool
-    eval "$pre_hook"
-    USER=nobody _run $tst $tool $opts
-    res=$?
+    _setup_state ${tst} ${tool}
+    eval "${pre_hook}"
+    USER=nobody _run ${tst} ${tool} ${opts}
+    res=${?}
     _save_tree
     _dump_logs
-    eval "$post_hook"
-    _verify_output $res $tst $tool $status
-    res=$?
-    let errs=$errs+$res
+    eval "${post_hook}"
+    _verify_output ${res} ${tst} ${tool} ${status}
+    res=${?}
+    let errs=${errs}+${res}
     _reset_state
 done
 
 # Clean up opt subdirectory, and attempt to remove test directory entirely;
 # if we fail, ignore it as it just means there are output files present for
 # failed tests.
-rm -rf $_testroot/opt
-rmdir $_testroot > /dev/null 2>&1
+rm -rf ${_testroot}/opt
+rmdir ${_testroot} > /dev/null 2>&1
 
-if [[ $errs -gt 0 ]]; then
+if [[ ${errs} -gt 0 ]]; then
     sts=1
 else
     sts=0
 fi
-exit $sts
+exit ${sts}
