Backport `pbench-move-results --controller`
This is a back-port of PR #1990, which also fixes the unit tests in
the `util-scripts` directory to check for dangling tests, and also
correctly test expected status.

diff --git a/agent/util-scripts/unittests b/agent/util-scripts/unittests
--- a/agent/util-scripts/unittests
+++ b/agent/util-scripts/unittests
@@ -199,16 +199,18 @@ function _verify_output {
         mv ${_testout} ${_testroot}/${tname}_output.txt
         sts=1
     else
-        if [[ ${sts} -eq 0 ]]; then
-            echo "PASS - ${tname}"
-            rm ${_testout}
-        elif [[ ${sts} -eq ${expected_status} ]]; then
-            echo "PASS - ${tname} exited with expected status: ${sts}"
-            rm ${_testout}
-            sts=0
+        if [[ ${sts} -eq ${expected_status} ]]; then
+            if [[ ${expected_status} -ne 0 ]]; then
+                echo "PASS - ${tname} exited with expected status: ${sts}"
+                sts=0
+            else
+                echo "PASS - ${tname}"
+            fi
         else
-            echo "FAIL - ${tname}: PASS output but execution returned non-zero exit status"
+            echo "FAIL - ${tname}: PASS output but execution returned unexpected exit status: ${sts}"
+            sts=1
         fi
+        rm ${_testout}
     fi
     return ${sts}
 }
@@ -355,6 +357,8 @@ declare -A tools=(
     [test-50]="test-pbench-metadata-log"
     [test-51]="pbench-start-tools"
     [test-52]="pbench-register-tool"
+    [test-53]="pbench-copy-results"
+    [test-54]="pbench-copy-results"
 )
 
 declare -A options=(
@@ -407,30 +411,44 @@ declare -A options=(
     [test-28]="--check --sysinfo=block,libvirt,kernel_config,sos,topology"
     [test-29]="--check --sysinfo=block,sos,bad,topology"
     [test-30]="--check --sysinfo=libvirt,default,kernel_config,all,topology,none"
+    # pbench-copy-results - verify prefix and user are recorded
     [test-31]="--prefix=foo/bar --user=ndk"
+    # pbench-copy-results
     [test-32]="--help"
+    # pbench-move-results
+    #[test-33]=""
+    # pbench-move-results
     [test-34]="--help"
     [test-35]="--group=default --start-trigger=\"START:DEFAULT\" --stop-trigger=\"STOP DEFAULT\""
     [test-36]="--group=default --start-trigger=\"START DEFAULT\" --stop-trigger=\"STOP:DEFAULT\""
+    # pbench-move-results
     [test-37]="--prefix="
+    # pbench-move-results
     [test-38]="--user="
+    # pbench-copy-results - verify just prefix
     [test-39]="--prefix=goo/tar"
+    # pbench-copy-results - verify just user
     [test-40]="--user=pap"
+    # pbench-copy-results - move one good result
+    #[test-41]=""
     [test-42]="--name=vmstat --group=default --no-install -- --interval=42"
     [test-43]="--name=turbostat --no-install --remotes=one.example.com,localhost,testhost.example.com,two.example.com"
     [test-44]="--name=mpstat --no-install --remotes=@${_testdir}/tmp/doesntexist.lis"
     [test-45]="--name=mpstat --no-install --remotes=@${_testdir}/tmp/remotes.lis"
     [test-46]="--name=mpstat --no-install --remotes=@${_testdir}/tmp/remotes.lis"
     [test-47]="--name=mpstat --no-install --remotes=@${_testdir}/tmp/remotes.lis --labels=labelOne,labelTwo"
+    # pbench-copy-results - verify handling of "%"
     [test-49]="--prefix=foo/bar3% --user=ndk20%"
     [test-51]="--dir=${_testdir}/mock-run/mock-iteration/mock-sample --group=default"
     [test-52]="--name=tcpdump --group=default --no-install -- --interface=br1 --packets=1000"
+    # pbench-copy-results - same controller specified as in metadata.log, no-op
+    [test-53]="--controller=testhost.example.com"
+    # pbench-copy-results - explicit controller different from recorded controller
+    [test-54]="--controller=my-controller.example.com"
 )
 
 declare -A expected_status=(
     [test-01]=1
-    [test-05]=1
-    [test-06]=1
     [test-11]=4
     [test-11.7]=1
     [test-11.8]=1
@@ -463,6 +481,36 @@ declare -A pre_hooks=(
 
 declare -A post_hooks=(
 )
+
+# Verify that there are no dangling gold files and sample directories.
+let cnt=0
+while read -r _path; do
+    if [[ -z "${_path}" ]]; then
+        continue
+    fi
+    _name="$(basename ${_path})"
+    tool=${tools[${_name}]}
+    if [[ -z "${tool}" ]]; then
+        printf -- "Dangling sample: ${_path}\n" >&2
+        (( cnt = cnt + 1 ))
+    fi
+done <<< "$(ls -1d ${_tdir}/samples/*/test-*)"
+while read -r _path; do
+    if [[ -z "${_path}" ]]; then
+        continue
+    fi
+    _name="$(basename ${_path})"
+    tool=${tools[${_name%.*}]}
+    if [[ -z "${tool}" ]]; then
+        printf -- "Dangling gold: ${_path}\n" >&2
+        (( cnt = cnt + 1 ))
+    fi
+done <<< "$(ls -1d ${_tdir}/gold/*/test-*)"
+
+if [[ ${cnt} -gt 0 ]]; then
+    printf -- "INTERNAL ERROR - Gold or Sample files not accounted for in test list.\n" >&2
+    exit 1
+fi
 
 tests="${*}"
 if [[ -z "${tests}" ]]; then
