Add local and remote pre-check for linpack
This is a back-port of commit b51b11672 (PR #2856) from `main`.

We add a local and remote pre-check function for linpack.

We now wait at most 60 seconds for the linpack process to start, and
then we wait for the PID to exit instead of a file to exist.  That way
if a file is never written that we expect, but the PID has died, we'll
not wait forever.

Further, we move the "version" check (of sorts) to the linpack driver
script to allow for the remote check to work without having the code in
two places.

diff --git a/agent/bench-scripts/driver/linpack-wait b/agent/bench-scripts/driver/linpack-wait
--- a/agent/bench-scripts/driver/linpack-wait
+++ b/agent/bench-scripts/driver/linpack-wait
@@ -3,7 +3,30 @@
 
 # A very simple method to wait for the linpack driver to report it has
 # finished.
-while [[ ! -e "${1}/linpack.meta" ]]; do
+
+if [[ ! -d "${1}" ]]; then
+	printf -- "linpack-wait: target directory, '${1}', does not exist!\n" >&2
+	exit 1
+fi
+
+# Wait for the linpack pid file to show up.
+let cnt=60
+while [[ ${cnt} -gt 0 && -d "${1}" && ! -e "${1}/linpack.pid" ]]; do
+	sleep 1
+	(( cnt-- ))
+done
+if [[ ! -d "${1}" ]]; then
+	printf -- "linpack-wait: target directory, '${1}', no longer exists!\n" >&2
+	exit 1
+fi
+if [[ ! -e "${1}/linpack.pid" ]]; then
+	printf -- "linpack-wait: linpack pid file, '${1}/linpack.pid', failed to show up\n" >&2
+	exit 1
+fi
+
+# At this point, we wait for the linpack process to stop running.
+pid=$(< "${1}/linpack.pid")
+while [[ -d /proc/${pid} ]]; do
 	sleep 1
 done
 exit 0
