Apply code review feedback

diff --git a/agent/bench-scripts/driver/linpack b/agent/bench-scripts/driver/linpack
--- a/agent/bench-scripts/driver/linpack
+++ b/agent/bench-scripts/driver/linpack
@@ -8,7 +8,7 @@
 #
 # The linpack binary expects an input file with 7 lines in it:
 #
-#     Line 1: Header (disgarded)
+#     Line 1: Header (discarded)
 #     Line 2: Sub-Header (emitted as-is to stdout)
 #     Line 3: Positive integer number of tests to run
 #     line 4: Number of equations to solve (problem size)
@@ -27,8 +27,8 @@
 #     line 6:     2     2     2
 #     line 7:     4     4     4
 #
-# This script provides optional input parameters for lines 1, 2, 4 - 7, and
-# then calculates the number of tests to be run from those inputs to fill in
+# This script offers input parameters for lines 1, 2, 4 - 7, with default values
+# and then calculates the number of tests to be run from those inputs to fill in
 # line 3 of the LINPACK input file.
 #
 # Additionally, it offers input parameters to control the use of OpenMP during
@@ -41,6 +41,9 @@
 #    ${output_dir}/linpack.input  -  Constructed seven line LINPACK input file
 #    ${output_dir}/linpack.meta   -  All input parameters provided as key=val
 #    ${output_dir}/linpack.out    -  The output generated by the LINPACK binary
+#
+# The script exits with 0 on success, 1 for any operational failures, and 2 for
+# an invocation errors.
 #
 
 script_name="$(basename ${0})"
@@ -78,11 +81,11 @@ function usage() {
 }
 
 # Process options and arguments
-opts=$(getopt -q -o h --longoptions "binary:,header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,help" -n "getopt.sh" -- "${@}")
+opts=$(getopt -q -o h --longoptions "binary:,header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,help" -n "${script_name}" -- "${@}")
 if [[ ${?} -ne 0 ]]; then
 	printf -- "%s %s\n\n\tunrecognized option specified\n\n" "${script_name}" "${*}" >&2
 	usage >&2
-	exit 1
+	exit 2
 fi
 eval set -- "${opts}"
 while true; do
@@ -187,40 +190,38 @@ if [[ -z "${output_dir}" || ! -d "${output_dir}" ]]; then
 fi
 if [[ -z "${binary}" ]]; then
 	printf -- "[%s] ERROR: You must specify --binary\n" "${script_name}" >&2
-	exit 3
+	exit 2
 fi
-if [[ ! -e "${binary}" || ! -x "${binary}" ]]; then
+if [[ ! -x "${binary}" ]]; then
 	printf -- "[%s] ERROR: The --binary must exist and be executable\n" "${script_name}" >&2
-	exit 4
+	exit 2
 fi
 if [[ "${use_omp}" != "y" && "${use_omp}" != "n" ]]; then
-	printf -- "[%s] ERROR: --use-omp must either by 'y' or 'n'\n" "${script_name}" >&2
-	exit 5
+	printf -- "[%s] ERROR: --use-omp must either be 'y' or 'n'\n" "${script_name}" >&2
+	exit 2
 fi
-num_problem_sizes=$(echo "${problem_sizes}" | wc -w)
-num_leading_dimensions=$(echo "${leading_dimensions}" | wc -w)
-num_run_trials=$(echo "${run_trials}" | wc -w)
-num_alignment_values=$(echo "${alignment_values}" | wc -w)
-if [[ "${num_problem_sizes}" != "${num_leading_dimensions}" || "${num_leading_dimensions}" != "${num_run_trials}" || "${num_run_trials}" != "${num_alignment_values}" ]]; then
-	printf -- "[%s] ERROR: You must have the same number of elements for --problem-sizes, --leading-dimensions, --run-trials, and --alignment-values\n" >&2
-	exit 6
+ps_list=(${problem_sizes})
+ls_list=(${leading_dimensions})
+rt_list=(${run_trials})
+av_list=(${alignment_values})
+if [[ ${#ps_list[*]} -ne ${#ls_list[*]} || \
+      ${#ls_list[*]} -ne ${#rt_list[*]} || \
+      ${#rt_list[*]} -ne ${#av_list[*]} ]]; then
+    printf -- "[%s] ERROR: You must have the same number of elements for --problem-sizes, --leading-dimensions, --run-trials, and --alignment-values\n" >&2
+    exit 2
 fi
-number_of_tests=${num_problem_sizes}
+number_of_tests=${#ps_list[*]}
 
 linpack_input_file="${output_dir}/${linpack_input_file_name}"
 linpack_metadata_file="${output_dir}/${linpack_metadata_file_name}"
 linpack_output_file="${output_dir}/${linpack_output_file_name}"
 
-numactl_cmd=""
-if [[ -n "${numactl_args}" ]]; then
-	# N.B. - Trailing whitespace is required.
-	numactl_cmd="numactl ${numactl_args} "
-fi
+# N.B. - Trailing whitespace is required.
+numactl_cmd=${numactl_args:+"numactl ${numactl_args} "}
 
 if [[ "${use_omp}" == "y" ]]; then
-	if [[ -z "${threads_arg}" ]]; then
-		threads_arg=$(cat /proc/cpuinfo | grep processor | wc -l)
-	fi
+	threads_arg=${threads_arg:-$(grep -c processor /proc/cpuinfo)}
+
 	# N.B. - Trailing whitespace is required.
 	omp_num_threads="OMP_NUM_THREADS=${threads_arg} "
 	# N.B. - Trailing whitespace is required.
@@ -234,27 +235,27 @@ else
 	omp_num_threads=""
 	kmp_affinity=""
 fi
-final_cmd="${omp_num_threads}${kmp_affinity}${numactl_cmd}${binary} ${linpack_input_file} | stdbuf --input=0 tee -i ${linpack_output_file}"
+final_cmd="${omp_num_threads}${kmp_affinity}${numactl_cmd}${binary}"
+final_cmd+=" ${linpack_input_file} |"
+final_cmd+=" stdbuf --input=0 tee -i ${linpack_output_file}"
 
-if [[ -z "${header}" ]]; then
-	# Line 1 default
-	header="Pbench - LINPACK Benchmark data file (${linpack_input_file})"
-fi
-if [[ -z "${subheader}" ]]; then
-	# Line 2 default header
-	subheader="Pbench LINPACK Benchmark data -- ${final_cmd}"
-fi
+# Line 1, prividing a default header
+header=${header:-"Pbench - LINPACK Benchmark data file (${linpack_input_file})"}
+# Line 2, providing a default sub-header
+subheader=${subheader:-"Pbench LINPACK Benchmark data -- ${final_cmd}"}
 
-# Create the LINPACK input file.
-printf -- "%s\n%s\n%d # number of tests\n%s # problem sizes\n%s # leading dimensions\n%s # times to run a test\n%s # alingment values (in KBytes)\n" \
-	"${header}" \
-	"${subheader}" \
-	"${number_of_tests}" \
-	"${problem_sizes}" \
-	"${leading_dimensions}" \
-	"${run_trials}" \
-	"${alignment_values}" \
-	> ${linpack_input_file}
+# Create the LINPACK input file.  Note the comment lines are redundant but
+# provided in a spirit of consistency with the example input files provided by
+# linpack RPM.
+cat > ${linpack_input_file} <<-__EOF__
+	${header}
+	${subheader}
+	${number_of_tests} # number of tests
+	${problem_sizes} # problem sizes
+	${leading_dimensions} # leading dimensions
+	${run_trials} # times to run a test
+	${alignment_values} # alingment values (in KBytes)
+	__EOF__
 
 # Now we can execute the final LINPACK command.
 eval ${final_cmd}
@@ -263,15 +264,15 @@ exit_code=${?}
 # Create the linpack.meta file containing all the metadata used for invoking
 # LINPACK (does not include "header" or "subheader").  This serves as the marker
 # file for its completion.
-printf -- "binary=%s\nuse_omp=%s\nthreads=%s\nkmp_affinity=%s\nnumactl_cmd=%s\nproblem_sizes=%s\nleading_dimensions=%s\nalignment_values=%s\n" \
-	"${binary}" \
-	"${use_omp}" \
-	"${threads_arg}" \
-	"${kmp_affinity_args}" \
-	"${numactl_cmd}" \
-	"${problem_sizes}" \
-	"${leading_dimensions}" \
-	"${alignment_values}" \
-	> ${linpack_metadata_file}
+cat > ${linpack_metadata_file} <<-__EOF__
+	binary=${binary}
+	use_omp=${use_omp}
+	threads=${threads_arg}
+	kmp_affinity=${kmp_affinity_args}
+	numactl_cmd=${numactl_cmd}
+	problem_sizes=${problem_sizes}
+	leading_dimensions=${leading_dimensions}
+	alignment_values=${alignment_values}
+	__EOF__
 
 exit ${exit_code}
