Not done yet -- max header length 254
The header and sub-header lines in a `linpack.input` file can only be
at most 254 characters (plus a new-line character).  So the headers
are truncated unconditionally.

Since the idea was to place the final command line used in the header,
we now write the final command to a file, `linpack.cmd`, in the output
directory in case the header is truncated.

diff --git a/agent/bench-scripts/driver/linpack b/agent/bench-scripts/driver/linpack
--- a/agent/bench-scripts/driver/linpack
+++ b/agent/bench-scripts/driver/linpack
@@ -9,8 +9,9 @@ script_name="$(basename ${0})"
 linpack_input_file_name="linpack.input"
 linpack_metadata_file_name="linpack.meta"
 linpack_output_file_name="linpack.out"
+linpack_command_file_name="linpack.cmd"
 
-linpack_binary=""
+binary=""
 
 # Input file defaults, only lines 4-7 (headers defined below).
 header=""
@@ -41,15 +42,46 @@ numactl_args=""
 output_dir=""
 
 function usage() {
-	printf -- "Pbench ${script_name} linpack driver\n\n"
 	cat <<-__EOF__
-Responsible for transforming pbench-linpack command line inputs into the
-the linpack invocation requirements.
+Pbench ${script_name} linpack driver
+
+Usage: ${script_name} [--problem-sizes=#[[,#]...]] [--leading-dimenions=#[[,#]...]]
+        [--run-trials=#[[,#]]...] [--alignment-values=#[[,#]...]] [--use-omp={[y]|n}]
+        [--threads=#] [--kmp-affinity=<options,>] [--numactl-args=<args,>]
+        [--output-dir=<directory>] <linpack binary path>
+
+Optional output control:
+
+    --output-dir   Location to store the generated input file, metadata file,
+                   and LINPACK generated output (defaults to current working
+                   directory)
+
+Optional command line parameters to specify values for the LINPACK input file:
+
+    --header               Line 1 header to use (default provided)
+    --subheader            Line 2 sub-header to use (default provided)
+    --problem-sizes        Values for line 4 (defaults to ${problem_sizes_def})
+    --leading-dimensions   Values for line 5 (defaults to ${leading_dimensions_def})
+    --run-trials           Values for line 6 (defaults to ${run_trials_def})
+    --alignment-values     Values for line 7 (defaults to ${alignment_values_def})
+
+Optional parameters to direct the use of OpenMP:
+
+    --use-omp        Use OpenMP; either 'y' or 'n' (default is '${use_omp_def}')
+    --threads        Number of threads to use under OpenMP (defaults to host CPU count)
+    --kmp-affinity   KMP_AFFINITY setting for OpenMP (defaults to ${kmp_affinity_args_def})
+
+Optional NUMA control parameter:
+
+    --numactl-args   \`numactl\` command parameters (no default provided)
+
+${script_name} is responsible for transforming pbench-linpack command line inputs
+into the the linpack invocation requirements.
 
 The linpack binary expects an input file with 7 lines in it:
 
-    Line 1: Header (discarded)
-    Line 2: Sub-Header (emitted as-is to stdout)
+    Line 1: Header (discarded; max 254 bytes + new line)
+    Line 2: Sub-Header (emitted as-is to stdout; max 254 bytes + new line)
     Line 3: Positive integer number of tests to run
     line 4: Number of equations to solve (problem size)
     line 5: Leading dimension of array
@@ -77,36 +109,12 @@ the LINPACK run, along with the OMP_NUM_THREADS and KMP_AFFINITY environment
 variables used by OpenMP, and if any NUMA controls should be applied (via
 \`numactl\`).  These parameters are provided in the default "Sub-Header".
 
-The script generates three files:
+The script generates four files:
 
+   {output-dir}/linpack.cmd    -  Command that was actually executed
    {output-dir}/linpack.input  -  Constructed seven line LINPACK input file
    {output-dir}/linpack.meta   -  All input parameters provided as key=val
    {output-dir}/linpack.out    -  The output generated by the LINPACK binary
-
-Required command line parameters:
-
-    --binary       Location of the LINPACK binary to use
-    --output-dir   Location to store the generated input file, metadata file,
-                   and LINPACK generated output
-
-Optional command line parameters to specify values of the input file:
-
-    --header               Line 1 header to use (default provided)
-    --subheader            Line 2 sub-header to use (default provided)
-    --problem-sizes        Values for line 4 (defaults to ${problem_sizes_def})
-    --leading-dimensions   Values for line 5 (defaults to ${leading_dimensions_def})
-    --run-trials           Values for line 6 (defaults to ${run_trials_def})
-    --alignment-values     Values for line 7 (defaults to ${alignment_values_def})
-
-Optional parameters to direct the use of OpenMP:
-
-    --use-omp        Either 'y' or 'n' (default is '${use_omp_def}')
-    --threads        Number of threads to use (defaults to CPU count)
-    --kmp-affinity   KMP_AFFINITY variable (defaults to ${kmp_affinity_args_def}
-
-Optional NUMA control parameter:
-
-    --numactl-args   \`numactl\` command parameters (no default provided)
 
 The script exits with 0 on success, 1 for any operational failures, and 2 for
 an invocation errors.
@@ -114,7 +122,7 @@ an invocation errors.
 }
 
 # Process options and arguments
-opts=$(getopt -q -o h --longoptions "binary:,header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,help" -n "${script_name}" -- "${@}")
+opts=$(getopt -q -o h --longoptions "header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,help" -n "${script_name}" -- "${@}")
 if [[ ${?} -ne 0 ]]; then
 	printf -- "%s %s\n\n\tunrecognized option specified\n\n" "${script_name}" "${*}" >&2
 	usage >&2
@@ -125,12 +133,6 @@ while true; do
 	arg="${1}"
 	shift
 	case "${arg}" in
-	--binary)
-		if [[ -n "${1}" ]]; then
-			binary="${1}"
-			shift
-		fi
-		;;
 	--header)
 		# Values for line 1 of the LINPACK input file
 		if [[ -n "${1}" ]]; then
@@ -217,16 +219,19 @@ while true; do
 	esac
 done
 
-if [[ -z "${output_dir}" || ! -d "${output_dir}" ]]; then
-	printf -- "[%s] ERROR: Specified --output-dir '${output_dir}' is not a directory\n" "${script_name}" >&2
-	exit 2
-fi
+binary=${1}
 if [[ -z "${binary}" ]]; then
-	printf -- "[%s] ERROR: You must specify --binary\n" "${script_name}" >&2
+	printf -- "[%s] ERROR: You must specify the location of the LINPACK binary\n" "${script_name}" >&2
 	exit 2
 fi
 if [[ ! -x "${binary}" ]]; then
 	printf -- "[%s] ERROR: The --binary must exist and be executable\n" "${script_name}" >&2
+	exit 2
+fi
+if [[ -z "${output_dir}" ]]; then
+	output_dir=$(pwd)
+elif [[ ! -d "${output_dir}" ]]; then
+	printf -- "[%s] ERROR: Specified --output-dir '${output_dir}' is not a directory\n" "${script_name}" >&2
 	exit 2
 fi
 use_omp=${use_omp:-${use_omp_def}}
@@ -254,6 +259,7 @@ number_of_tests=${#ps_list[*]}
 linpack_input_file="${output_dir}/${linpack_input_file_name}"
 linpack_metadata_file="${output_dir}/${linpack_metadata_file_name}"
 linpack_output_file="${output_dir}/${linpack_output_file_name}"
+linpack_command_file="${output_dir}/${linpack_command_file_name}"
 
 # N.B. - Trailing whitespace is required.
 numactl_cmd=${numactl_args:+"numactl ${numactl_args} "}
@@ -277,20 +283,25 @@ else
 	kmp_affinity=""
 fi
 final_cmd="${omp_num_threads}${kmp_affinity}${numactl_cmd}${binary}"
+display_cmd="${omp_num_threads}${kmp_affinity}${numactl_cmd}${binary}"
 final_cmd+=" ${linpack_input_file} |"
 final_cmd+=" stdbuf --input=0 tee -i ${linpack_output_file}"
+# Save the actual command we'll use below
+printf -- "${final_cmd}\n" > ${linpack_command_file}
 
-# Line 1, providing a default header
+# Line 1, providing a default header (truncated to 254 characters)
 header=${header:-"Pbench - LINPACK Benchmark data file (${linpack_input_file})"}
-# Line 2, providing a default sub-header
-subheader=${subheader:-"Pbench LINPACK Benchmark data -- ${final_cmd}"}
+printf -v input_header "%.254s" "${header}"
+# Line 2, providing a default sub-header (truncated to 254 characters)
+subheader=${subheader:-"Pbench - LINPACK Command: '${display_cmd}'"}
+printf -v input_subheader "%.254s" "${subheader}"
 
 # Create the LINPACK input file.  Note the comment lines are redundant but
 # provided in a spirit of consistency with the example input files provided by
 # linpack RPM.
 cat > ${linpack_input_file} <<-__EOF__
-	${header}
-	${subheader}
+	${input_header}
+	${input_subheader}
 	${number_of_tests} # number of tests
 	${problem_sizes} # problem sizes
 	${leading_dimensions} # leading dimensions
@@ -299,7 +310,7 @@ cat > ${linpack_input_file} <<-__EOF__
 	__EOF__
 
 # Now we can execute the final LINPACK command.
-eval ${final_cmd}
+source ${linpack_command_file}
 exit_code=${?}
 
 # Create the linpack.meta file containing all the metadata used for invoking
