Add local and remote pre-check for linpack

diff --git a/agent/bench-scripts/driver/linpack b/agent/bench-scripts/driver/linpack
--- a/agent/bench-scripts/driver/linpack
+++ b/agent/bench-scripts/driver/linpack
@@ -41,12 +41,15 @@ numactl_args=""
 # Output directory required.
 output_dir=""
 
+# By default we don't perform only a pre-check.
+pre_check=0
+
 function usage() {
 	cat <<-__EOF__
 Usage: ${script_name} [--problem-sizes=#[[,#]...]] [--leading-dimenions=#[[,#]...]]
         [--run-trials=#[[,#]]...] [--alignment-values=#[[,#]...]] [--use-omp={y|n}]
         [--threads=#] [--kmp-affinity=<options>] [--numactl-args=<args>]
-        [--output-dir=<directory>] <linpack binary path>
+        [--output-dir=<directory>] <linpack version number installed>
 
 Optional output control:
 
@@ -128,7 +131,7 @@ an invocation errors.
 }
 
 # Process options and arguments
-opts=$(getopt -q -o h --longoptions "header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,help" -n "${script_name}" -- "${@}")
+opts=$(getopt -q -o h --longoptions "header:,subheader:,problem-sizes:,leading-dimensions:,alignment-values:,run-trials:,threads:,use-omp:,kmp-affinity:,numactl-args:,output-dir:,pre-check,help" -n "${script_name}" -- "${@}")
 if [[ ${?} -ne 0 ]]; then
 	printf -- "%s %s\n\n\tunrecognized option specified\n\n" "${script_name}" "${*}" >&2
 	usage >&2
@@ -211,6 +214,9 @@ while true; do
 			shift
 		fi
 		;;
+	--pre-check)
+		pre_check=1
+		;;
 	-h|--help)
 		help
 		exit 0
@@ -225,16 +231,22 @@ while true; do
 	esac
 done
 
-binary=${1}
-if [[ -z "${binary}" ]]; then
-	printf -- "[%s] ERROR: You must specify the location of the LINPACK binary\n\n" "${script_name}" >&2
+ver=${1}
+if [[ -z "${ver}" ]]; then
+	printf -- "[%s] ERROR: You must specify the version of the LINPACK binary\n\n" "${script_name}" >&2
 	usage >&2
 	exit 2
 fi
+binary="/usr/local/pbench-linpack-${ver}/benchmarks/linpack/xlinpack_xeon64"
 if [[ ! -x "${binary}" ]]; then
 	printf -- "[%s] ERROR: The --binary must exist and be executable\n" "${script_name}" >&2
 	exit 2
 fi
+
+if [[ ${pre_check} -ne 0 ]]; then
+	exit 0
+fi
+
 output_dir=${output_dir:-$(pwd)}
 if [[ ! -d "${output_dir}" ]]; then
 	printf -- "[%s] ERROR: Specified --output-dir '${output_dir}' is not a directory\n" "${script_name}" >&2
