Move test environment out of the way
Move test environment from `server/bin` to `server/test`.

diff --git a/server/test/run b/server/test/run
--- a/server/test/run
+++ b/server/test/run
@@ -13,16 +13,24 @@ unset _PBENCH_SERVER_CONFIG
 export LANG=C
 export LC_ALL=C
 
-export _tdir=$(dirname $(readlink -f ${0}))
-export _gitdir=$(dirname $(dirname ${_tdir}))
-export _tlib=${_tdir}/../lib
+function _log_exit {
+    echo "${1}" >&2
+    exit 1
+}
+
+export _server=$(dirname $(dirname $(realpath "${0}")))
+export _bdir=${_server}/bin
+test -d "${_bdir}" || _log_exit "ERROR: \"${_bdir}\" not a directory"
+export _ldir=${_server}/lib
+test -d "${_ldir}" || _log_exit "ERROR: \"${_ldir}\" not a directory"
+export _tdir=${_server}/test
+test -d "${_tdir}" || _log_exit "ERROR: \"${_tdir}\" not a directory"
+export _webs=$(dirname "${_server}")/web-server
+test -d "${_webs}" || _log_exit "ERROR: \"${_webs}\" not a directory"
 export _testbase=/var/tmp/pbench-test-server
 rm -rf ${_testbase}
 mkdir ${_testbase}
-if [[ ! -d ${_testbase} ]]; then
-    echo "ERROR: failed to create test base directory, \"${_testbase}\"" >&2
-    exit 1
-fi
+test -d ${_testbase} || _log_exit "ERROR: Failed to create test base directory, \"${_testbase}\""
 
 alias logger="logger --no-act --stderr"
 
@@ -39,6 +47,7 @@ function remove_path {
     # PATH => /bin:/sbin
     echo ${WORK}
 }
+# Remove potential conflicts with installed RPMs.
 PATH=$(remove_path /opt/pbench-server/bin ${PATH})
 PATH=$(remove_path /opt/pbench-agent/bench-scripts ${PATH})
 export PATH=$(remove_path /opt/pbench-agent/util-scripts ${PATH})
@@ -68,7 +77,7 @@ function _run_activate {
     # test, but just emit the resulting crontab and activation log file contents
     # generated by the test framework itself.
     echo "+++ Verifying server activation" >> ${_testout}
-    sed -i 's;'${_gitdir}'/server/;/home/user/repo/pbench/server/;' ${_testactout}
+    sed -i 's;'${_server}'/;/home/user/repo/pbench/server/;' ${_testactout}
     cat ${_testactout} >> ${_testout}
     echo "++++ ${_testopt}/lib/crontab/crontab" >> ${_testout}
     cat ${_testopt}/lib/crontab/crontab >> ${_testout}
@@ -169,7 +178,7 @@ function _dump_logs {
                 while read fname; do
                     echo "+++++ ${fname}" >> ${_testout}
                     _normalize_output ${dir}/logs/${fname} >> ${_testout} 2>&1
-                    ${_tdir}/test-bin/verify_cee ${dir}/logs/${fname} >> ${_testout} 2>&1 || echo "Bad CEE JSON in ${dir}/logs/${fname}" >> ${_testout} 2>&1
+                    ${_tdir}/bin/verify_cee ${dir}/logs/${fname} >> ${_testout} 2>&1 || echo "Bad CEE JSON in ${dir}/logs/${fname}" >> ${_testout} 2>&1
                     echo "----- ${fname}" >> ${_testout}
                 done
             echo "---- $(basename ${dir})/logs" >> ${_testout}
@@ -198,11 +207,10 @@ function _verify_output {
               -e 's/"_parent": "[0-9a-f]+",/"_parent": "babb1e70015c01055a15ca1ab1eb0a75",/' \
               -e 's/"@generated-by": "[0-9a-f]+",/"@generated-by": "70015f01dedbadbeefc105edcafedead",/' ${_testout}
     diff -c ${_tdir}/gold/${tname}.txt ${_testout} > ${_testdiff} 2>&1
-    if [[ ${?} -gt 0 ]]; then
-        let res=1
+    res=${?}
+    if [[ ${res} -gt 0 ]]; then
         echo "FAIL" > ${_testres}
     else
-        let res=0
         echo "PASS" > ${_testres}
         rm ${_testout} ${_testdiff}
     fi
@@ -221,25 +229,25 @@ function _setup_state {
     local res=0
     mkdir -p ${_testopt}/unittest-scripts/
     let res=res+${?}
-    cp -a ${_tdir}/test-bin/* ${_testopt}/unittest-scripts/
+    cp -a ${_tdir}/bin/* ${_testopt}/unittest-scripts/
     let res=res+${?}
     mkdir -p ${_testopt}/bin
     let res=res+${?}
-    cp -a ${_tdir}/{unittests,getconf.py,pbench*} ${_testopt}/bin
+    cp -a ${_bdir}/{getconf.py,pbench*} ${_testopt}/bin
     let res=res+${?}
     mkdir -p ${_testopt}/html/static/{js,css}/v0.{2,3}
     let res=res+${?}
-    cp -a ${_tdir}/../../web-server/v0.2/js/ ${_testopt}/html/static/js/v0.2
+    cp -a ${_webs}/v0.2/js/ ${_testopt}/html/static/js/v0.2
     let res=res+${?}
-    cp -a ${_tdir}/../../web-server/v0.3/js/ ${_testopt}/html/static/js/v0.3
+    cp -a ${_webs}/v0.3/js/ ${_testopt}/html/static/js/v0.3
     let res=res+${?}
-    cp -a ${_tdir}/../../web-server/v0.2/css/ ${_testopt}/html/static/css/v0.2
+    cp -a ${_webs}/v0.2/css/ ${_testopt}/html/static/css/v0.2
     let res=res+${?}
-    cp -a ${_tdir}/../../web-server/v0.3/css/ ${_testopt}/html/static/css/v0.3
+    cp -a ${_webs}/v0.3/css/ ${_testopt}/html/static/css/v0.3
     let res=res+${?}
-    cp -a ${_tdir}/../lib ${_testopt}
+    cp -a ${_ldir} ${_testopt}/
     let res=res+${?}
-    cp -a ${_tdir}/../../lib/* ${_testopt}/lib
+    cp -a ${_server}/../lib/* ${_testopt}/lib
     let res=res+${?}
     mkdir -p ${_testhtml}
     let res=res+${?}
@@ -389,10 +397,16 @@ function _run_test {
     export _testopt=${_testroot}/opt/pbench-server
 
     _setup_state ${testname}
+    if [[ ${?} -gt 0 ]]; then
+        echo "ERROR: failed to setup test state for \"${testname}\"" >&2
+        exit 1
+    fi
+
     # echo ${testname}: ${cmd}
     SECONDS=0
-    ${cmd} $*
+    ${cmd} ${*}
     echo "${SECONDS} secs" > ${_testdur}
+
     _audit_server
     rmdir ${_testtmp} > /dev/null 2>&1
     _save_tree
