Fix tool stop/postprocess handling
We first verify `stop` and `postprocess` tool actions have a tool
directory that exist.

The `stop` and `postprocess` actions are now captured in their own log
files in the `${tool_output_dir}`.  That reduces unnecessary output now
that `tool-scripts` operations are not captured in the `pbench.log` file
as of 53dba5f (PR #1460).

We also remove unneeded `tmp` directory trees in the samples.

diff --git a/agent/tool-scripts/base-tool b/agent/tool-scripts/base-tool
--- a/agent/tool-scripts/base-tool
+++ b/agent/tool-scripts/base-tool
@@ -747,6 +747,10 @@ start)
 	popd > /dev/null
 	;;
 stop)
+	if [[ ! -d ${tool_output_dir} ]]; then
+		printf -- "%s: WARNING - stop - tool output directory, '%s', missing\n" "${tool_name}" "${tool_output_dir}" >&2
+		exit 1
+	fi
 	enable -n kill
 	printf -- "%s: stopping\n" "${tool_name}"
 	if [[ -s "${tool_pid_file}" ]]; then
@@ -828,6 +832,10 @@ stop)
 	fi
 	;;
 postprocess)
+	if [[ ! -d ${tool_output_dir} ]]; then
+		printf -- "%s: WARNING - postprocess - tool output directory, '%s', missing\n" "${tool_name}" "${tool_output_dir}" >&2
+		exit 1
+	fi
 	case ${tool} in
 	user-tool)
 		_script_path="${postprocess_script}"
