Use perf archive and stop generating per-CPU reports
The generation of per-CPU perf reports can take a long time to generate
when there are many CPUs present, since it is performed serially to avoid
memory usage bloat processing them all in parallel.

We have moved all of the logic for post-processing perf reports to the
perf-postprocess Perl script, and now use perf archive to capture all
the necessary data to process the perf data off host.

diff --git a/agent/tool-scripts/perf b/agent/tool-scripts/perf
--- a/agent/tool-scripts/perf
+++ b/agent/tool-scripts/perf
@@ -1,12 +1,12 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; sh-indent-for-case-alt: + -*-
 
-script_path=`dirname $0`
-script_name=`basename $0`
-pbench_bin="`cd ${script_path}/..; /bin/pwd`"
+script_name="$(basename $0)"
+script_path="$(dirname $(realpath $0))"
+pbench_bin="$(dirname ${script_path})"
 
 # source the base script
-. "$pbench_bin"/base
+. "${pbench_bin}"/base
 
 # Perftool scripts must provide the following functions
 # 1) Install the tool
@@ -15,97 +15,114 @@ pbench_bin="`cd ${script_path}/..; /bin/pwd`"
 # 4) post-process the data
 
 # Defaults
-tool=perf
-tool_bin=/usr/bin/$tool
+tool=${script_name}
+tool_bin=/usr/bin/${tool}
+tool_package_name=${tool}
 group=default
-dir="/tmp"
+dir=""
 mode=""
 iteration="1"
 options="none"
 record_opts="record -a --freq=100"
 report_opts="report --show-nr-samples -I"
 
+function usage {
+	printf "The following options are available for the ${script_name} tool: \n\n"
+	printf -- "\t-h     --help,			this usage message\n"
+	printf -- "\t       --install,			install this perf tool\n"
+	printf -- "\t       --start|stop|postprocess	start/stop/post-process the data collection\n"
+	printf -- "\t-i int --iteration=int 		the iteration (required)\n"
+	printf -- "\t-g str --group=str			the perftool group (required)\n"
+	printf -- "\t-d str --dir=str			directory to store data collection (required)\n"
+	printf -- "\t       --callgraph			generate a call graph (--record-opts and --report-opts should not be used with this option)\n"
+	printf -- "\t-r str --record-opts=str		options one would use to record perf data, for example: 'record -a'\n"
+	printf -- "\t-p str --report-opts=str		options one would use to report perf data, for example: 'report'\n"
+}
+
 # Process options and arguments
-opts=$(getopt -o d --longoptions "dir:,group:,iteration:,callgraph,record-opts:,report-opts:,start,stop,install,postprocess" -n "getopt.sh" -- "$@");
+opts=$(getopt -o d:hg:i:r:p: --longoptions "dir:,group:,iteration:,callgraph,record-opts:,report-opts:,start,stop,install,postprocess,help" -n "getopt.sh" -- "$@");
 if [ $? -ne 0 ]; then
 	printf "\n"
 	printf "$script_name: you specified an invalid option\n\n"
-	printf "The following options are available: \n\n"
-	printf -- "\t--install,			install this perf tool\n"
-	printf "\n"
-	printf -- "\t--start|stop|postprocess	start/stop/post-process the data collection\n"
-	printf -- "\t--iteration=int 		the iteration (required)\n"
-	printf -- "\t--group=str		the perftool group (required)\n"
-	printf -- "\t--dir=str			directory to store data collection (required)\n"
-	printf -- "\t--callgraph		generate a call graph (--record-opts and --report-opts should not be used with this option)\n"
-	printf -- "\t--record-opts=str		options one would use to record perf data, for example: 'record -a'\n"
-	printf -- "\t--report-opts=str		options one would use to report perf data, for example: 'report'\n"
+	usage
 	exit 1
 fi
 eval set -- "$opts";
 while true; do
 	case "$1" in
-		--install)
+	--install)
 		mode="install"
 		shift;
 		;;
-		--start)
+	--start)
 		mode="start"
 		shift;
 		;;
-		--stop)
+	--stop)
 		mode="stop"
 		shift;
 		;;
-		--postprocess)
+	--postprocess)
 		mode="postprocess"
 		shift;
 		;;
-		-d|--dir)
+	-d|--dir)
 		shift;
 		if [ -n "$1" ]; then
 			dir="$1"
 			shift
 		fi
 		;;
-		-g|--group)
+	-g|--group)
 		shift;
 		if [ -n "$1" ]; then
 			group="$1"
 			shift
 		fi
 		;;
-		-i|--iteration)
+	-i|--iteration)
 		shift;
 		if [ -n "$1" ]; then
 			iteration="$1"
 			shift
 		fi
 		;;
-		--callgraph)
+	--callgraph)
 		shift;
 		if [ -n "$1" ]; then
 			record_opts="record -a --freq=100 -g"
 			report_opts="report -I -g"
 		fi
 		;;
-		-r|--record-opts)
+	-r|--record-opts)
 		shift;
 		if [ -n "$1" ]; then
 			record_opts="$1"
 			shift
 		fi
 		;;
-		-p|--report-opts)
+	-p|--report-opts)
 		shift;
 		if [ -n "$1" ]; then
 			report_opts="$1"
 			shift
 		fi
 		;;
-		--)
+	-h|--help)
+		shift;
+		usage
+		exit 0
+		;;
+	--)
 		shift;
 		break;
+		;;
+	*)
+		shift;
+		printf "\n"
+		printf "$script_name: you specified an invalid option or parameter, $1\n\n"
+		usage
+		exit 1
 		;;
 	esac
 done
@@ -118,63 +135,81 @@ tool_pid_file=$pbench_tmp/$group.$iteration.$tool.pid
 tool_output_file=$tool_output_dir/$tool.txt
 case "$mode" in
 	install)
-        ;;
+		check_install_rpm $tool_package_name
+        	;;
 	start)
-	if ! cat /proc/mounts | grep -q debugfs; then
-		mount -t debugfs none /sys/kernel/debug
-	fi
-	mkdir $tool_output_dir
-	pushd $tool_output_dir >/dev/null
-        echo "$tool_cmd" >$tool_cmd_file
-	# call the tool and background it...
-	$tool_cmd > "$tool_output_dir/perf-stdout.txt" 2> "$tool_output_dir/perf-stderr.txt" & echo $! >"$tool_pid_file"
-	wait
-	popd >/dev/null
-	;;
-	stop)
-	if [[ -s "$tool_pid_file" ]]; then
-		pushd $tool_output_dir >/dev/null
-		pid=`cat "$tool_pid_file"`
-		if [ ! -z "$pid" ]; then
-			kill -SIGINT $pid
-			# wait for perf to finish recording.
-			# if you do not wait, 'perf report' will not be correct.
-			# perf is not a child process, so we cannot use "wait".
-			# this is an alternative.
-			pidcmd=`ps -p $pid | tail -1 | awk '{print $4}'`
-			while [ -d /proc/$pid ]; do
-				debug_log "waiting for PID $pid ($pidcmd) to finish"
-				sleep 0.5
-			done
+		if ! cat /proc/mounts | grep -q debugfs; then
+			mount -t debugfs none /sys/kernel/debug
 		fi
-		/bin/rm "$tool_pid_file"
-		popd >/dev/null
-	else
-		warn_log "[$script_name]: tool is not running, nothing to kill"
-	fi
-	;;
+		mkdir $tool_output_dir
+		if [ $? -ne 0 ]; then
+			error_log "$script_name: start -- unable to create directory $tool_output_dir"
+			exit 1
+		fi
+	        echo "$tool_cmd" > $tool_cmd_file
+		# call the tool and background it...
+		$tool_cmd --output=$tool_output_dir/perf.data > "$tool_output_dir/perf-stdout.txt" 2> "$tool_output_dir/perf-stderr.txt" & echo $! > "$tool_pid_file"
+		wait
+		exit_status=0
+		;;
+	stop)
+		if [[ -s "$tool_pid_file" ]]; then
+			pid=`cat "$tool_pid_file"`
+			if [ ! -z "$pid" ]; then
+				kill -SIGINT $pid
+				# wait for perf to finish recording.
+				# if you do not wait, 'perf report' will not be correct.
+				# perf is not a child process, so we cannot use "wait".
+				# this is an alternative.
+				pidcmd=`ps -p $pid | tail -1 | awk '{print $4}'`
+				while [ -d /proc/$pid ]; do
+					debug_log "waiting for PID $pid ($pidcmd) to finish"
+					sleep 0.5
+				done
+			fi
+			/bin/rm "$tool_pid_file"
+			if [ -f $tool_output_dir/perf.data ]; then
+				exit_status=0
+			else
+				warn_log "$script_name: stop - missing ${tool_output_dir}/perf.data file!"
+				exit_status=1
+			fi
+		else
+			warn_log "[$script_name]: tool is not running, nothing to stop"
+			exit_status=1
+		fi
+		;;
 	postprocess)
-	pushd $tool_output_dir >/dev/null
-	$tool_bin $report_opts -i ./perf.data --stdio >perf-report.txt 2>&1
-	# report per-cpu
-	mkdir -p perf-percpu
-	for cpu_id in `cat /proc/cpuinfo  | grep processor | awk -F: '{print $2}'`; do
-		$tool_bin $report_opts -i ./perf.data --stdio --cpu $cpu_id >./perf-percpu/perf-report-cpu_$cpu_id.txt 2>/dev/null
-		xz --threads=0 perf-percpu/perf-report-cpu_$cpu_id.txt
-		chmod go+r perf-percpu/perf-report-cpu_$cpu_id.txt.xz
-	done
-	if [ -f perf.data ]; then
-		xz --threads=0 perf.data
-		chmod go+r perf.data.xz
-	fi
-	# only postprocess the perf report if the default options are used
-	if echo $record_opts | grep -E -q -- -g\|--callgraph; then
-		debug_log "Not going to run perf postprocess script since this report contains a callgraph"
-	else
-		$script_path/postprocess/$script_name-postprocess .
-	fi
-	xz --threads=0 perf-report.txt
-	chmod go+r perf-report.txt.xz
-	popd >/dev/null
-	;;
+		if [ -f ${tool_output_dir}/perf.data ]; then
+			# Collect the archive of perf information so the perf data can be
+			# processed off host.  We explicitly ignore any errors since we
+			# have already stopped the tool.  Note we have to use push/popd
+			# since the "perf archive" command always creates the tar ball in
+			# the local directory.
+			pushd ${tool_output_dir} > /dev/null 2>&1
+			$tool_bin archive ./perf.data > ./perf-archive.log 2>&1
+			popd > /dev/null 2>&1
+			# Generate the initial report.
+			$tool_bin $report_opts -i ${tool_output_dir}/perf.data --stdio > ${tool_output_dir}/perf-report.txt 2> ${tool_output_dir}/perf-report.err
+			xz --threads=0 ${tool_output_dir}/perf.data
+			# only postprocess the perf report if the default options are used
+			if echo $record_opts | grep -E -q -- -g\|--callgraph; then
+				debug_log "$script_name: not going to run perf postprocess script since this report contains a callgraph"
+			else
+				$script_path/postprocess/$script_name-postprocess ${tool_output_dir}
+			fi
+			xz --threads=0 ${tool_output_dir}/perf-report.txt
+			# Provide a README file to help users work with perf data locally.
+			copy ${script_path}/${script_name}.README ${tool_output_dir}/README
+			exit_status=0
+		else
+			warn_log "$script_name: postprocess - missing ${tool_output_dir}/perf.data file!"
+			exit_status=1
+		fi
+		;;
+	*)
+		error_log "$script_name: unexpected mode: $mode, no action taken"
+		exit_status=1
+		;;
 esac
+exit $exit_status
