Enable minimum RPM version support
Fixes #2142.

We need to support a minimum version of an RPM in addition to an exact
version.  We use the `rpmdev-vercmp` from the `rpmdevtools` RPM in order
to perform the matching.

diff --git a/agent/tool-scripts/unittests b/agent/tool-scripts/unittests
--- a/agent/tool-scripts/unittests
+++ b/agent/tool-scripts/unittests
@@ -76,9 +76,10 @@ if [[ ${?} -ne 0 ]]; then
     echo "ERROR: failed to create util-scripts directory" >&2
     exit 1
 fi
-cp ${_tdir}/../util-scripts/require-rpm ${_optdir}/util-scripts/ 2> /dev/null
+printf -- "#!/bin/bash\n\n_ver=\"\${2}\"\nif [[ ! -z \"\${_ver}\" ]]; then _ver=\"-\${_ver}\"; fi\necho \"\${1}\${_ver}\"\nexit 0\n" > ${_optdir}/util-scripts/require-rpm
+chmod 775 ${_optdir}/util-scripts/require-rpm
 if [[ ${?} -ne 0 ]]; then
-    echo "ERROR: failed to copy util-scripts/require-rpm" >&2
+    echo "ERROR: failed to create ${_optdir}/util-scripts/require-rpm" >&2
     exit 1
 fi
 
diff --git a/agent/util-scripts/require-rpm b/agent/util-scripts/require-rpm
--- a/agent/util-scripts/require-rpm
+++ b/agent/util-scripts/require-rpm
@@ -1,20 +1,65 @@
 #!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 4; sh-indentation: 4; tab-width: 8 -*-
 
+# require-rpm - check to see if a RPM with the required version is installed.
+#
+# Returns 0 (success) if it is; 1 if it isn't; 2 if an error occured during
+# operation.
+
 _rpm="${1}"
 if [[ ! -z "${2}" ]]; then
     _version="-${2}"
 else
     _version=""
 fi
-if [[ ! -z "${_PBENCH_UNIT_TESTS}" ]]; then
-    # Package changes are always successful for unit tests.
-    exit 0
+if [[ ! -z "${3}" ]]; then
+    _match="${3}"
+else
+    _match="eq"
 fi
 
-_status=$(rpm --query ${_rpm}${_version})
+_status=$(rpm --query --queryformat="%{EVR}" ${_rpm} 2>/dev/null)
 rc=0
 if echo ${_status} | grep -q "is not installed"; then
     rc=1
+else
+    # Some RPMs might have multiple version installed, iterate through all of
+    # them.
+    for rpm_installed in ${_status}; do
+		# Exit status is 0 if the EVR's are equal, 11 if EVR1 is newer, and 12
+        # if EVR2 is newer.  Other exit statuses indicate problems.
+        rpmdev-vercmp ${rpm_installed} ${_rpm}${_version} > /dev/null 2>&1
+        res=${?}
+        if [[ ${res} != 0 && ${res} != 11 && ${res} != 12 ]]; then
+            exit 2
+        fi
+        if [[ "${_match}" == "eq" ]]; then
+            if [[ ${res} == 0 ]]; then
+                rc=0
+                echo "${rpm_installed}"
+                break
+            else
+                rc=1
+            fi
+        fi
+        if [[ "${_match}" == "ge" ]]; then
+            if [[ ${res} == 0 || ${res} == 11 ]]; then
+                rc=0
+                echo "${rpm_installed}"
+                break
+            else
+                rc=1
+            fi
+        fi
+        if [[ "${_match}" == "gt" ]]; then
+            if [[ ${res} == 11 ]]; then
+                rc=0
+                echo "${rpm_installed}"
+                break
+            else
+                rc=1
+            fi
+        fi
+    done
 fi
 exit ${rc}
