Refactor tool-scripts to use one script
Addresses issue #1459 following "Proposal 1".

This is a fairly invasive and major change to the tool sub-system.
The interface to the `pbench-start/stop/postprocess-tools` has
changed, and changes to various interfaces and behaviors of the
individual tools.

The first change is that the pbench-agent no longer tries to install
*ANY* RPMs via yum.

This is significant in that all of the benchmark scripts now only
*check* that their required RPMs are installed, and all the tools
during registration only perform a check that their requirements are
satistified.

Again, no RPMs are installed by the pbench-agent any longer.

All of the tool datalogs have been enhanced to check for their
required environment and error messages describing what is not met.

We are removing knowledge of how bench-scripts handle iterations
and samples so that the tools are only given a directory to work
with and no longer use `$pbench_tmp`.  All that they need to do
with files are managed in that given directory. This then allowed
us to remove the `--iteration` and `--group` parameters from all
the tools, and in turn, remove the --iteration parameter from the
invocation of the `pbench-start/stop/postprocess-tools`.  This
prevents knowledge of how benchmark scripts work from leaking into
the various tools.

Further, we now have three scripts that implement the methods for
running tools:

 * `base-tool`
    * a merger of all the previous tool scripts
    * with #1248, this will be replaced by Tool Meister code
 * `user-tool`
    * dedicated to just handling the user
 * `external-data-source`
    * place-holder for the no-op external data source

We also add the notion of a "stop-postprocess" script so that when
tools are stopped (when `pbench-stop-tools` is invoked), any
post-processing required to be performed on the host on which the
tool is running can be executed.  This allows us to run all the
normal post-procesing of data to generate charts and graphs during
the `pbench-postprocess-tools` phase only on the local controller, or
at a later time.

We have added unit tests for all the tools in the `tool-scripts`
directory, and in the `tool-scripts/datalog` directory as well.

One major behavior change to the `systemtap` tool is worth noting.
The systemtap script argument is now the "compiled" systemtap
script. The user is not responsible for making sure the provided
script is available to the systemtap tool on all the hosts it is
registered.

This is a work-in-progress!

We still have a few tools to re-factor to support:

 * [ ] haproxy-ocp
 * [ ] oc
 * [ ] pcp
 * [ ] pprof
 * [ ] prometheus-metrics

Unit test considerations:

 * [ ] consider how to unit-test the new *-stop-postprocess scripts

diff --git a/agent/tool-scripts/datalog/disk-datalog b/agent/tool-scripts/datalog/disk-datalog
--- a/agent/tool-scripts/datalog/disk-datalog
+++ b/agent/tool-scripts/datalog/disk-datalog
@@ -1,10 +1,24 @@
 #!/bin/bash
+# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; tab-width: 8 -*-
 
-interval=$1
-file=$2
+PROG="$(basename ${0})"
 
-while true; do
+interval="${1}"
+if [[ -z "${interval}" ]]; then
+	printf -- "%s: missing required 'interval' argument\n" "${PROG}" >&2
+	exit 1
+fi
+
+command -v df > /dev/null
+if [[ ${?} -ne 0 ]]; then
+	printf -- "%s: missing required 'df' command\n" "${PROG}" >&2
+	exit 1
+fi
+
+rc=0
+while [[ ${rc} -eq 0 ]]; do
 	# we display the output in kilobytes.
-	/usr/bin/df --output=source,target,fstype,itotal,iused,iavail,size,used,avail,file | grep -v openshift_local_volumes | grep -vw Filesystem | pbench-log-timestamp | awk -F ' ' '{gsub(/\:/,"",$1); print}' >> $file
-	sleep $interval
+	df --output=source,target,fstype,itotal,iused,iavail,size,used,avail,file | grep -v openshift_local_volumes | grep -vw Filesystem | pbench-log-timestamp | awk -F ' ' '{gsub(/\:/,"",$1); print}'
+	sleep ${interval}
+	rc=${?}
 done
diff --git a/agent/tool-scripts/datalog/openvswitch-datalog b/agent/tool-scripts/datalog/openvswitch-datalog
--- a/agent/tool-scripts/datalog/openvswitch-datalog
+++ b/agent/tool-scripts/datalog/openvswitch-datalog
@@ -1,61 +1,77 @@
 #!/bin/bash
+# -*- mode: shell-script; indent-tabs-mode: t; sh-basic-offset: 8; sh-indentation: 8; tab-width: 8 -*-
 
-interval=$1
-dir=$2
-bridges_file=$dir/bridges.txt
-stats_file=$dir/ovs-stats.txt
-rxq_mapping_file=$dir/pmd-rxq-show.txt
+PROG="$(basename ${0})"
 
-version_file=$dir/ovs-version.txt
-ovs-vsctl --version >$version_file
-echo >> $version_file
-rpm -qif `readlink -e /proc/$(pidof ovs-vswitchd)/exe` >>$version_file 2>/dev/null
-
-info_file=$dir/ovs-info.txt
-ovs-vsctl show >$info_file
-
-cfg_file=$dir/ovs-cfg.txt
-ovs-vsctl get Open_vSwitch . other_config >$cfg_file
-
-bridge=`ovs-vsctl list-br | head -n 1`
-protocol_string=""
-ovs-ofctl show ${bridge} > /dev/null 2>&1
-ret_val=$?
-if [ ${ret_val} != 0 ]; then
-    protocols_string="--protocols OpenFlow13"
-    protocols_file=$dir/ovs-protocols.txt
-    echo "OpenFlow13" >$protocols_file
+tool_output_dir="${1}"
+if [[ ! -d "${tool_output_dir}" ]]; then
+	printf -- "%s: invalid tool output directory, '%s'\n" "${PROG}" "${tool_output_dir}" >&2
+	exit 1
 fi
 
-bridges=`ovs-vsctl list-br`
-echo "$bridges" >$bridges_file
-# mapping below used in postprocess
-for b in $bridges; do
-	ports_file=$dir/$b-port-mappings.txt
-	ovs-ofctl show $b ${protocols_string} >$ports_file
-done
-ovs-appctl dpif-netdev/pmd-rxq-show >$rxq_mapping_file
+interval="${2}"
+if [[ -z "${interval}" ]]; then
+	printf -- "%s: missing required 'interval' argument\n" "${PROG}" >&2
+	exit 1
+fi
 
-cat /dev/null >$stats_file
-if [ ! -z "$bridges" ]; then
+command -v ovs-vsctl > /dev/null
+if [[ ${?} -ne 0 ]]; then
+	printf -- "%s: missing required 'ovs-vsctl' command\n" "${PROG}" >&2
+	exit 1
+fi
+
+version_file=${tool_output_dir}/ovs-version.txt
+echo "$(ovs-vsctl --version)" >> ${version_file}
+rpm -qif $(readlink -e /proc/$(pidof ovs-vswitchd)/exe) >> ${version_file}
+
+info_file=${tool_output_dir}/ovs-info.txt
+ovs-vsctl show > ${info_file}
+
+cfg_file=${tool_output_dir}/ovs-cfg.txt
+ovs-vsctl get Open_vSwitch . other_config > ${cfg_file}
+
+bridge=$(ovs-vsctl list-br | head -n 1)
+protocol_string=""
+ovs-ofctl show ${bridge} > /dev/null 2>&1
+ret_val=${?}
+if [[ ${ret_val} != 0 ]]; then
+    protocols_string="--protocols OpenFlow13"
+    protocols_file=${tool_output_dir}/ovs-protocols.txt
+    echo "OpenFlow13" > ${protocols_file}
+fi
+
+bridges_file=${tool_output_dir}/bridges.txt
+bridges="$(ovs-vsctl list-br | tee ${bridges_file})"
+# mapping below used in postprocess
+for b in ${bridges}; do
+	ports_file=${tool_output_dir}/${b}-port-mappings.txt
+	ovs-ofctl show ${b} ${protocols_string} > ${ports_file}
+done
+rxq_mapping_file=${tool_output_dir}/pmd-rxq-show.txt
+ovs-appctl dpif-netdev/pmd-rxq-show > ${rxq_mapping_file}
+
+stats_file=${tool_output_dir}/ovs-stats.txt
+> ${stats_file}
+if [[ ! -z "${bridges}" ]]; then
 	while true; do
-		printf "\ntimestamp: `date +%s.%N`\n" >>$stats_file
-		for bridge in $bridges; do
+		printf "\ntimestamp: $(date +%s.%N)\n" >> ${stats_file}
+		for bridge in ${bridges}; do
 			# ovs-ofctl
 			for cmd in dump-ports dump-flows; do
-				echo "bridge: $bridge stats: $cmd" >>$stats_file
-				ovs-ofctl $cmd $bridge ${protocols_string} >>$stats_file
+				echo "bridge: ${bridge} stats: ${cmd}" >> ${stats_file}
+				ovs-ofctl ${cmd} ${bridge} ${protocols_string} >> ${stats_file}
 			done
 			# ovs-appctl
 			for cmd in fdb/show; do
-				echo "bridge: $bridge stats: $cmd" >>$stats_file
-				ovs-appctl $cmd $bridge | awk 'BEGIN { } { if ($0 !~ /port/) { ports[$1]++; } } END { for (p in ports) { printf(" port=%s count=%d\n", p, ports[p]); } }' >>$stats_file
+				echo "bridge: ${bridge} stats: ${cmd}" >> ${stats_file}
+				ovs-appctl ${cmd} ${bridge} | awk 'BEGIN { } { if ($0 !~ /port/) { ports[$1]++; } } END { for (p in ports) { printf(" port=%s count=%d\n", p, ports[p]); } }' >> ${stats_file}
 			done
 		done
 		# DPDK stats
-		echo "dpdk-stats: pmd-stats-show" >>$stats_file
-		ovs-appctl dpif-netdev/pmd-stats-show >>$stats_file
+		echo "dpdk-stats: pmd-stats-show" >> ${stats_file}
+		ovs-appctl dpif-netdev/pmd-stats-show >> ${stats_file}
 		ovs-appctl dpif-netdev/pmd-stats-clear
-		sleep $interval
+		sleep ${interval}
 	done
 fi
