Use systemctl to launch the Pbench Server container when deploying Since we use systemctl to run the containerized Pbench Server in the Staging deployment (and since we'll do the same in Production), use the same mechanism when running the Server for functional test or development.

diff --git a/jenkins/run-server-func-tests b/jenkins/run-server-func-tests
--- a/jenkins/run-server-func-tests
+++ b/jenkins/run-server-func-tests
@@ -76,11 +76,41 @@ function dump_journal {
     printf -- "\n--- journalctl dump ---\n\n"
 }
 
+function sc_disable {
+    # Run systemctl to disable the Pbench Server unit and clean up after any
+    # resulting failures attempting to do so.
+
+    # Send the command output to the bitbucket; capture stderr in a variable.
+    o=$(systemctl --user --runtime disable --now pbench-server 2>&1 >/dev/null)
+    r=${?}
+    if (( r != 0 )); then
+        # Ignore the expected error
+        if [[ ${o} != *"Unit file"*"does not exist"* ]]; then
+            echo "systemctl disable: ${o}"
+            return ${r}
+        fi
+    fi
+
+    o=$(systemctl --user --runtime reset-failed pbench-server 2>&1 >/dev/null)
+    r=${?}
+    if (( r != 0 )); then
+        # Ignore the expected error
+        if [[ ${o} != *"Unit"*"not found"* && ${o} != *"Unit"*"not loaded"* ]]; then
+            echo "systemctl reset-failed: ${o}"
+            return ${r}
+        fi
+    fi
+
+    return ${r}
+}
+
 function cleanup {
     if (( cleanup_flag )); then
         # Remove the Pbench Server container and the dependencies pod which we
         # just created and ran; remove any dangling containers; and then remove
         # any dangling images.
+        echo "Disabling the pbench-server service..." >&2
+        sc_disable
         echo "Forcefully removing the Pbench Server container..." >&2
         podman rm --force --ignore ${PB_SERVER_CONTAINER_NAME}
         echo "Forcefully removing the Pbench Support Services pod..." >&2
@@ -158,7 +188,7 @@ if (( ! cleanup_flag )); then
 fi
 
 echo "Stopping the Pbench Server container..."
-podman stop ${PB_SERVER_CONTAINER_NAME}
+sc_disable
 stop_status=${?}
 if [[ ${exit_status} -eq 0 ]]; then
     exit_status=${stop_status}
