Correct UID template resolution
Backport of PRs #3029 (665132a89) and #3035 (4822f75af).

When a template key maps to a non-string value, an error is encountered
like:

    "TypeError: decoding to str: need a bytes-like object, float found"

The code now converts all non-string values to strings, and ignores any
keys which don't map to a value with one of the types: `string`, `int`,
or `float`.

A set of unit tests for this operation is provided, and the function
name was renamed to ensure its intended use is clear.

Unfortunately, as the bits have aged the backport of the unit tests is
a bit more difficult.  To make this all work we had to:

 * Remove fallback `elasticsearch` import, it just confused things

 * Move `pytest` invocation under `jenkins-unittests` since we can't
   use `--current-env` with `py3-server`

 * Fix `PYTHONPATH` for unit tests to include the server code

 * Delineate the CI steps a bit more cleanly

diff --git a/jenkins/run-unittests b/jenkins/run-unittests
--- a/jenkins/run-unittests
+++ b/jenkins/run-unittests
@@ -7,7 +7,9 @@ source $(dirname "${0}")/python-setup.sh
 
 typeset -i errors=0
 
-printf -- "black --check ...\n"
+printf -- "\n\n\nrun-unittests started ...\n"
+
+printf -- "\n\nblack --check ...\n"
 black --check .
 black_sts=${?}
 if [[ ${black_sts} -ne 0 ]]; then
@@ -15,14 +17,23 @@ if [[ ${black_sts} -ne 0 ]]; then
     (( errors++ ))
 fi
 
-printf -- "\nflake8 --verbose ...\n"
+printf -- "\n\nflake8 --verbose ...\n"
 flake8 --verbose .
 flake_sts=${?}
 if [[ ${flake_sts} -ne 0 ]]; then
     printf -- "FAILED: flake8 --verbose .\n" >&2
     (( errors++ ))
 fi
-printf -- "\n"
+
+printf -- "\n\npytests ...\n"
+pytest server/lib/pbench/test/unit
+pytest_sts=${?}
+if [[ ${pytest_sts} -ne 0 ]]; then
+    printf -- "FAILED: pytest server/lib/pbench/test/unit\n" >&2
+    (( errors++ ))
+fi
+
+printf -- "\n\n\n"
 
 export PBENCH_UNITTEST_SERVER_MODE=parallel
 
@@ -79,9 +90,9 @@ for env in ${envs}; do
 done
 
 if [[ ${errors} -gt 0 ]]; then
-    printf -- "\n\nTests failed! (%d errors)\n" ${errors}
+    printf -- "\n\nrun-unittests ... Tests failed! (%d errors)\n\n\n" ${errors}
     exit 1
 else
-    printf -- "\n\nTests succeeded.\n"
+    printf -- "\n\nrun-unittests ... Tests succeeded.\n"
     exit 0
 fi
