Pass long `--cleanup`; support only the 9s
All arguments to `jenkins/runlocal` are passed along to
`jenkins/run-server-unit-tests` as a simple way to support the
`--cleanup` option on `jenkins/runlocal`

Further, we only support defaulting to a `ubi9:latest` or
`centos:stream9` image in those respective environments.

Lastely, we add support for `BASE_IMAGE` to be defined ahead of time.

diff --git a/jenkins/runlocal b/jenkins/runlocal
--- a/jenkins/runlocal
+++ b/jenkins/runlocal
@@ -3,6 +3,11 @@
 # Build the Pbench Server RPM and container, and run functional tests locally.
 # Requires a Fedora, CentOS, or RHEL environment to run.
 
+# NOTE WELL: By default, when the functional tests are run, the infrastructure
+# pod and Pbench Server container are left running by default.  Add the switch,
+# `--cleanup` to direct `jenkins/run-server-func-tests` to cleanup when
+# finished (success or failure).
+
 # Build the pbench-server RPM locally, then build the containers locally, and
 # then run the functional tests against the locally built CI container image.
 export PB_SERVER_IMAGE_NAME=pbench-server
@@ -22,20 +27,26 @@ ls -ld ${RPM_PATH}
 
 source /etc/os-release
 
-if [[ ${ID} == "fedora" ]]; then
-    BASE_IMAGE=${ID}:${VERSION_ID}
-elif [[ ${ID} == "centos" ]]; then
-    BASE_IMAGE=stream${VERSION_ID%%.*}:latest
-elif [[ ${ID} == "rhel" ]]; then
-    BASE_IMAGE=ubi${VERSION_ID%%.*}:latest
-else
-    echo "Unsupported local OS, ${ID}:${VERSION_ID}" >&2
-    exit 1
+if [[ -z ${BASE_IMAGE} ]]; then
+    major=${VERSION_ID%%.*}
+    if [[ ${ID} == "fedora" ]]; then
+        # Any Fedora is okay.
+        BASE_IMAGE=${ID}:${major}
+    elif [[ ${ID} == "centos" && "${major}" == "9" ]]; then
+        # Only CentOS 9 is supported
+        BASE_IMAGE=${ID}:stream${major}
+    elif [[ ${ID} == "rhel" && "" == "9" ]]; then
+        # Only RHEL 9 is supported
+        BASE_IMAGE=ubi${major}:latest
+    else
+        echo "Unsupported local OS, ${ID}:${VERSION_ID}" >&2
+        exit 1
+    fi
+    export BASE_IMAGE
 fi
-export BASE_IMAGE
 
 # Build the canned Pbench Server container from the RPM built above.
 server/pbenchinacan/container-build.sh
 
 # Run the functional tests using the locally built image.
-jenkins/run-server-func-tests
+jenkins/run-server-func-tests "${@}"
