Review feedback:  whitespace (indentation) changes

diff --git a/jenkins/set-expiration b/jenkins/set-expiration
--- a/jenkins/set-expiration
+++ b/jenkins/set-expiration
@@ -23,11 +23,11 @@
 #
 
 if [[ $# -ne 4 ]] ; then
-  echo "Incorrect number of arguments (expected 4, got $#)" >&2
-  exit 2
+    echo "Incorrect number of arguments (expected 4, got $#)" >&2
+    exit 2
 elif [[ -z ${PB_IMAGE_BEARER_TOKEN} ]]; then
-  echo "Missing bearer token (PB_IMAGE_BEARER_TOKEN not defined)" >&2
-  exit 2
+    echo "Missing bearer token (PB_IMAGE_BEARER_TOKEN not defined)" >&2
+    exit 2
 fi
 
 expiration="{\"expiration\": ${1}}"
@@ -37,8 +37,8 @@ image_tag=${4}
 content_length=$(( $(wc -c <<< "${expiration}") - 1 ))  # Don't count newline
 
 curl -fs -X PUT -d "${expiration}" \
-  -w "Set expiration response: %{response_code}\n" \
-  -H "Authorization: Bearer ${PB_IMAGE_BEARER_TOKEN}" \
-  -H "Content-Type: application/json" \
-  -H "Content-Length: ${content_length}" \
-  https://${image_reg}/api/v1/repository/${image_name}/tag/${image_tag}
+    -w "Set expiration response: %{response_code}\n" \
+    -H "Authorization: Bearer ${PB_IMAGE_BEARER_TOKEN}" \
+    -H "Content-Type: application/json" \
+    -H "Content-Length: ${content_length}" \
+    https://${image_reg}/api/v1/repository/${image_name}/tag/${image_tag}
