Update .eslintrc with linting rules targeting es6
Running `yarn lint` will run the project linter on all *.js files.
The unittests integrated with Travis CI will catch any errors
associated with the linter during tests.

diff --git a/web-server/v0.4/unittests b/web-server/v0.4/unittests
--- a/web-server/v0.4/unittests
+++ b/web-server/v0.4/unittests
@@ -11,4 +11,9 @@ if [[ $? -ne 0 ]]; then
   echo "yarn unit tests failed!" >&2
   exit 1
 fi
+yarn lint
+if [[ $? -ne 0 ]]; then
+  echo "yarn lint failed!" >&2
+  exit 1
+fi
 exit 0
