Get UI unit tests working again w latest enzyme pkg
For whatever reason, the latest version of Enzyme requires an `Adapter` to
be configured.

We also run the linting before the unit tests since linting can actually
catch errors in the code before they cause the unit tests to fail.

diff --git a/web-server/v0.4/unittests b/web-server/v0.4/unittests
--- a/web-server/v0.4/unittests
+++ b/web-server/v0.4/unittests
@@ -1,19 +1,19 @@
 #!/bin/bash
 
-cd $(dirname $0)
-yarn --network-timeout 1000000
-if [[ $? -ne 0 ]]; then
-  echo "yarn failed!" >&2
-  exit 1
-fi
-yarn test
-if [[ $? -ne 0 ]]; then
-  echo "yarn unit tests failed!" >&2
+cd $(dirname ${0})
+yarn install --network-timeout 1000000
+if [[ ${?} -ne 0 ]]; then
+  echo "yarn install failed!" >&2
   exit 1
 fi
 yarn lint
-if [[ $? -ne 0 ]]; then
+if [[ ${?} -ne 0 ]]; then
   echo "yarn lint failed!" >&2
+  exit 1
+fi
+yarn test
+if [[ ${?} -ne 0 ]]; then
+  echo "yarn unit tests failed!" >&2
   exit 1
 fi
 exit 0
