Move pbench-agent to python3

diff --git a/agent/base b/agent/base
--- a/agent/base
+++ b/agent/base
@@ -8,6 +8,18 @@
 # will catch any ssh failure
 set -o pipefail
 
+if which python3 > /dev/null 2>&1 ;then
+    # All python programs/scripts have headers using "python3" by default.
+    :
+elif which scl_source > /dev/null 2>&1 ;then
+    # If we don't have python3, but we do have SCL, we only support
+    # Python 3.6.
+    source scl_source enable rh-python36
+else
+    printf -- "${script_name}: python3 required, either directly or through SCL\n" >&2
+    exit 1
+fi
+
 # very first thing to do is figure out which pbench we are
 if [[ -z "$pbench_run" ]]; then
     pbench_run=$(getconf.py pbench_run pbench-agent)
diff --git a/agent/tool-scripts/datalog/unittests b/agent/tool-scripts/datalog/unittests
--- a/agent/tool-scripts/datalog/unittests
+++ b/agent/tool-scripts/datalog/unittests
@@ -44,6 +44,18 @@ export PATH=${_tdir}/mock-bin:${PATH}
 # timestamps will show a constant offset.
 export TZ=UTC
 
+if which python3 > /dev/null 2>&1 ;then
+    # All python programs/scripts have headers using "python3" by default.
+    :
+elif which scl > /dev/null 2>&1 ;then
+    # If we don't have python3, but we do have SCL, we only support
+    # Python 3.6.
+    source scl_source enable rh-python36
+else
+    printf -- "python3 required, either directly or through SCL\n" >&2
+    exit 1
+fi
+
 declare -A options=(
     [prometheus-metrics]="example.host.com 3 tool_log 9042 cert false key"
 )
