Catch pipeline failures and return proper error status.
Scripts where pipelines like this: ssh remote command | process output
are used do not deal with ssh errors properly. The pipeline returns
the status of the last command.

Set the pipefail option in base: that way pipelines will return the
status of the last failed command in the pipeline, not that of the
last command.

o pbench-register-tool now exits with the correct status of the
  pipeline.  pbench-register-tool-set counts pbench-register-tool
  failures and exits with status equal to the number of failed
  pbench-register-tool calls.

o Extend ssh status checking to pbench-clear-tools.

  There are two cases to consider: pbench-clear-tools is called
  with or without a --name=foo option.

  In the first case, the intent is to clear a single
  tool. pbench-clear-tools will try to ssh to all the remotes and
  clear the tool; it will also try to count how many tools are left
  (with another ssh) and if none, it will delete the local @remote
  entry.  If the first ssh fails, we do not continue to the second: we
  just count it as a failure, but since we cannot find out the state
  of the remote, we assume that it still has tools left and we do not
  remove the local entry for the remote.

  In the second case, the intent is to clear all tools, so even if the
  ssh fails, we remove the local entry for the remote. IOW,
  pbench-clear-tools with no --name argument might leave junk lying
  around on the remote if we can't get to it, but it clears everything
  locally.

  In either case, we return the number of ssh failures as the exit
  status of the command.

o pbench-start-tools now checks its ssh pipeline for errors and returns
  status properly.

  In addition, pbench-start-tools is modified to call
  pbench-kill-tools before starting a new run. It has often been the
  case that tools from earlier runs are not cleaned up properly,
  particularly when the run is interrupted. Although that is a problem
  that should be resolved in the calling script, using "trap
  'pbench-kill-tools' INT QUIT EXIT", this is an attempt to make tool
  handling more robust and avoid the most common failure scenarios.

diff --git a/agent/base b/agent/base
--- a/agent/base
+++ b/agent/base
@@ -1,6 +1,10 @@
 #!/bin/bash
 
 export PBENCH_debug_mode=0
+# pipeline status is set to the status of the last command that *failed*
+# in the pipeline (or 0 if all succeed): this way "ssh foo | sed '...' "
+# will catch any ssh failure
+set -o pipefail
 
 # very first thing to do is figure out which pbench
 # we are
