Switch to tarball MD5 as Dataset resource_id (#2890)
Switch to tarball MD5 as Dataset resource_id

PBENCH-744

Change the Dataset table to make resource_id the primary key. This must
be unique due to Elasticsearch constraints, and the change allows us to
"demote" dataset name (which is just script+config+date) to metdata that
we can allow the user to set arbitrarily.

This change ripples through the code, resulting in a lot of diffs. Most
of these are fairly straightforward.

Note that this removes legacy test-5.2; PR #2611 also removes this as it
finally drops pbench-server-prep-shim-002 entirely, but the fairly
twisted things test-5.2 does with duplicate and MD5 errors simply don't
apply to the 1.0 server and it's not worth trying to fix it.

diff --git a/server/bin/utils/run-unittest b/server/bin/utils/run-unittest
--- a/server/bin/utils/run-unittest
+++ b/server/bin/utils/run-unittest
@@ -463,7 +463,12 @@ function _setup_state {
         local state
         local user
         while read -r controller name state user; do
-            pbench-state-manager --create=${user} --name=${name} --state=${state}
+            tarball=$(find ${_testdir} -name ${name}.tar.xz -type f)
+            pbench-state-manager --create=${user} --path=${tarball} --state=${state}
+            if [[ ${?} -gt 0 ]]; then
+                echo "ERROR: unable to create ${tarball} dataset" >&2
+                exit 1
+            fi
         done < ${_state_db}
     fi
 }
